src/main/java/net/causw/adapters/web/UserController.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/UserDetailDto.java
src/main/java/net/causw/domain/model/UserDomainModel.java
src/main/java/net/causw/domain/spi/UserPort.java
src/main/java/net/causw/infra/BaseEntity.java
src/main/java/net/causw/infra/Role.java
src/main/java/net/causw/infra/User.java
src/main/java/net/causw/infra/UserRepository.java
src/main/java/net/causw/infra/port/UserPortImpl.java
src/main/resources/application.yaml

- None
Implement example of hexagonal architecture using user entity.
- None

feat: Implement example

---

.github/workflows/ci.yml

chore: ci 기본적인 부분 우선 구성

---

src/main/java/net/causw/application/dto/UserDetailDto.java
src/main/java/net/causw/domain/model/UserDomainModel.java
src/main/java/net/causw/infra/User.java
src/main/java/net/causw/web/UserController.java

기본 구조이긴 하지만, 적용했으면 하는 부분과 컨벤션 적용을 좀 해두었습니다.
- `UserDetailDto` 는 예제가 아니라 추후에도 쓰일 것 같아서, 우선 `password` 는 뺐습니다.
- `UserDetailDto` 에서 처럼, 파라미터가 많아지면 가독성을 위해 각 파라미터를 띄어쓰기 해주세요.
- `Adapter/web` 패키지를 본 프로젝트에서는 별도의 Adapter 내부 추가 패키지가 필요 없을 것 같아서, `web` 패키지로 변경했습니다.

fix: update user model and convention

---

src/main/resources/application-dev.yaml
src/main/resources/application-local.yaml
src/main/resources/application-prod.yaml

- #3 
Application 설정을 분리하였습니다.
local에서 실행 시, `SPRING_PROFILES_ACTIVE=local` 로 환경변수 설정해서 실행해주세요.

feat: divide properties for active profile

---

src/main/java/net/causw/application/dto/UserDetailDto.java
src/main/java/net/causw/infra/UserAuthLog.java
src/main/java/net/causw/infra/UserAuthLogRepository.java

feat: impl user_auth_log entity

---

src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/PostService.java
src/main/java/net/causw/application/dto/BoardDetailDto.java
src/main/java/net/causw/application/dto/PostDetailDto.java
src/main/java/net/causw/application/dto/UserDetailDto.java
src/main/java/net/causw/domain/model/BoardDomainModel.java
src/main/java/net/causw/domain/model/PostDomainModel.java
src/main/java/net/causw/domain/spi/BoardPort.java
src/main/java/net/causw/domain/spi/PostPort.java
src/main/java/net/causw/infra/Board.java
src/main/java/net/causw/infra/BoardRepository.java
src/main/java/net/causw/infra/Post.java
src/main/java/net/causw/infra/PostRepository.java
src/main/java/net/causw/infra/port/BoardPortImpl.java
src/main/java/net/causw/infra/port/PostPortImpl.java
src/main/java/net/causw/infra/port/UserPortImpl.java
src/main/java/net/causw/web/BoardController.java
src/main/java/net/causw/web/PostController.java

- #7 
Implement skel of board and post entity

feat: Impl skel of board and post entity

---

src/main/java/net/causw/application/UserAuthService.java
src/main/java/net/causw/application/dto/UserAuthDto.java
src/main/java/net/causw/domain/spi/UserAuthPort.java
src/main/java/net/causw/infra/UserAuth.java
src/main/java/net/causw/infra/UserAuthRepository.java
src/main/java/net/causw/infra/port/UserAuthPortImpl.java
src/main/java/net/causw/web/UserController.java

fix: update user auth model

---

src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/PostService.java
src/main/java/net/causw/application/UserAuthService.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/BoardDetailDto.java
src/main/java/net/causw/application/dto/PostDetailDto.java
src/main/java/net/causw/application/dto/UserAuthDto.java
src/main/java/net/causw/application/dto/UserCreateRequestDto.java
src/main/java/net/causw/application/dto/UserDetailDto.java
src/main/java/net/causw/application/spi/BoardPort.java
src/main/java/net/causw/application/spi/PostPort.java
src/main/java/net/causw/application/spi/UserAuthPort.java
src/main/java/net/causw/application/spi/UserPort.java
src/main/java/net/causw/domain/model/BoardDomainModel.java
src/main/java/net/causw/domain/model/PostDomainModel.java
src/main/java/net/causw/domain/model/UserDomainModel.java
src/main/java/net/causw/domain/spi/BoardPort.java
src/main/java/net/causw/domain/spi/PostPort.java
src/main/java/net/causw/domain/spi/UserAuthPort.java
src/main/java/net/causw/domain/spi/UserPort.java
src/main/java/net/causw/infra/User.java
src/main/java/net/causw/infra/port/BoardPortImpl.java
src/main/java/net/causw/infra/port/PostPortImpl.java
src/main/java/net/causw/infra/port/UserAuthPortImpl.java
src/main/java/net/causw/infra/port/UserPortImpl.java
src/main/java/net/causw/web/UserController.java

- #17 
회원 가입 구현
- 회원 가입 구현
- 구조 변경
- domain model은 비즈니스 로직만을 가지고, service에서 호출하는 식
- DB에 조회 저장 수정하는 흐름에서는 domain model과 관계없이 이루어지는 식으로 변경
- 이로 인해, spi 패키지는 application 패키지로 이동

feat: Implement user sign up

---

build.gradle
src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/application/dto/CircleDto.java
src/main/java/net/causw/application/spi/CirclePort.java
src/main/java/net/causw/config/SwaggerConfig.java
src/main/java/net/causw/domain/model/CircleDomainModel.java
src/main/java/net/causw/infra/Circle.java
src/main/java/net/causw/infra/CircleRepository.java
src/main/java/net/causw/infra/User.java
src/main/java/net/causw/infra/port/CirclePortImpl.java
src/main/java/net/causw/web/CircleController.java

- \#5
Swaager 적용 및 Circle entity 기본 구조 작성
- Swagger 적용
- Circle Entity 작성

Swaager 적용 및 Circle entity 기본 구조 작성

---

src/main/java/net/causw/adapter/db/Board.java
src/main/java/net/causw/application/dto/BoardDetailDto.java

- None
Board 테이블에 is_deleted 컬럼 추가

refac: Add isDeleted column at board table

---

src/main/java/net/causw/adapter/db/Circle.java
src/main/java/net/causw/adapter/db/port/UserPortImpl.java
src/main/java/net/causw/adapter/web/GlobalExceptionHandler.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/spi/UserPort.java
src/main/java/net/causw/config/SwaggerConfig.java

fix
- Circle model의 오류 수정
- UserPortImpl의 `findByEmail` 에서 `INVALID_SIGNIN` 에러를 던지는 부분 수정 (Service에서 에러를 던지도록)
- Enum의 `valueOf()` 함수 사용을 대비하여 `IllegalArgumentException` 에 대한 핸들링 추가
- SwaggerConfig의 작은 수정

fix: update circle model and user port impl, add illegal exception model

---

src/main/java/net/causw/adapter/persistence/BaseEntity.java
src/main/java/net/causw/adapter/persistence/Board.java
src/main/java/net/causw/adapter/persistence/BoardRepository.java
src/main/java/net/causw/adapter/persistence/Circle.java
src/main/java/net/causw/adapter/persistence/CircleRepository.java
src/main/java/net/causw/adapter/persistence/Post.java
src/main/java/net/causw/adapter/persistence/PostRepository.java
src/main/java/net/causw/adapter/persistence/User.java
src/main/java/net/causw/adapter/persistence/UserAuth.java
src/main/java/net/causw/adapter/persistence/UserAuthRepository.java
src/main/java/net/causw/adapter/persistence/UserRepository.java
src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
src/main/java/net/causw/adapter/persistence/port/CirclePortImpl.java
src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
src/main/java/net/causw/adapter/persistence/port/UserAuthPortImpl.java
src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/BoardDetailDto.java
src/main/java/net/causw/application/dto/CircleDto.java
src/main/java/net/causw/application/dto/PostDetailDto.java
src/main/java/net/causw/application/dto/UserAuthDto.java
src/main/java/net/causw/application/dto/UserCreateRequestDto.java
src/main/java/net/causw/application/dto/UserDetailDto.java
src/main/java/net/causw/application/dto/UserFullDto.java
src/main/java/net/causw/domain/model/UserDomainModel.java

- #50 
Add student id column at User table

refac: Add student id column at User table

---

src/main/java/net/causw/adapter/persistence/UserRepository.java
src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/EmailDuplicatedCheckDto.java
src/main/java/net/causw/application/spi/UserPort.java

API 구현
- Email 중복 체크
- 이름으로 검색
1. Changes Detail에서 이전 PR (#43) 과 겹치는 부분은 해당 PR 머지되면 제거됩니다 : 해당 PR에서 수정한 내용을 이용해야 해서 어쩔 수 없이 거기서 Branch 따왔습니다
2. PortImpl에서 exception을 던지는 기존 구조는 잘못된 구조입니다. Optional을 이용해서 Service에서 Exception을 던지도록 합니다. 이 PR을 참고해서 다른 모델에도 적용해주세요 @ase3238 @dlsrks1021 @als95 @dokyeongK

feat: impl user api - email duplicate check and find by name

---

src/main/java/net/causw/adapter/persistence/Board.java
src/main/java/net/causw/adapter/persistence/Circle.java
src/main/java/net/causw/adapter/persistence/Locker.java
src/main/java/net/causw/adapter/persistence/Post.java
src/main/java/net/causw/adapter/persistence/User.java
src/main/java/net/causw/adapter/persistence/UserAuth.java

- none
Entity에 nullable 및 default value 명시

fix: Specify nullable and default value in table column

---

build.gradle
docker-compose.yaml
src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/application/LockerService.java
src/main/java/net/causw/application/PostService.java
src/main/java/net/causw/application/UserAuthService.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/UserCreateRequestDto.java
src/main/resources/application-test.yaml
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #11 
Spock test with example test case
- UserService의 exception handling 관련 수정
- test를 위한 database를 5433 포트로 동작시켰고, active profile을 annotation으로 넘겨주었습니다.
- 예제 TC로 user -> sign-up 부분 구현했습니다. 
- TC는 가능한 자세히 작업해주세요. 본 PR에서도 모자란 부분이 있을 지 꼼꼼히 봐주세요.

feat: spock test

---

src/main/java/net/causw/adapter/persistence/LockerLog.java
src/main/java/net/causw/adapter/persistence/LockerLogRepository.java
src/main/java/net/causw/adapter/persistence/port/LockerLogPortImpl.java
src/main/java/net/causw/adapter/web/LockerController.java
src/main/java/net/causw/application/LockerService.java
src/main/java/net/causw/application/dto/LockerLogDetailDto.java
src/main/java/net/causw/application/spi/LockerLogPort.java
src/main/java/net/causw/domain/model/LockerLogAction.java

제곧내
- locker number / user email / user name 각각 관계를 끊어낸 채로 생성
- locker id로 locker를 꺼내서 locker number를 통해 log를 가져오게 함

feat: LockerLog entity 정의 및 사물함 log api 구현

---

build.gradle
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/UserDetailDto.java
src/main/java/net/causw/config/JwtAuthenticationFilter.java
src/main/java/net/causw/config/JwtTokenProvider.java
src/main/java/net/causw/config/WebSecurityConfig.java

- #19 
Implement to create JWT token

feat: Implement to create JWT token

---

src/main/java/net/causw/adapter/persistence/Circle.java
src/main/java/net/causw/adapter/persistence/User.java
src/main/java/net/causw/adapter/persistence/UserCircle.java
src/main/java/net/causw/adapter/persistence/UserCircleRepository.java
src/main/java/net/causw/adapter/persistence/UserCircleStatus.java
src/main/java/net/causw/adapter/persistence/port/UserCirclePortImpl.java
src/main/java/net/causw/adapter/web/UserCircleController.java
src/main/java/net/causw/application/UserCircleService.java
src/main/java/net/causw/application/dto/UserCircleDto.java
src/main/java/net/causw/application/spi/UserCirclePort.java
src/main/java/net/causw/domain/model/UserCircleDomainModel.java

UserCircle entity 기본 구조 작성
- UserCircle Entity 작성

feat: UserCircle Entity 구현

---

src/main/java/net/causw/adapter/persistence/Circle.java
src/main/java/net/causw/adapter/persistence/CircleRepository.java
src/main/java/net/causw/adapter/persistence/User.java
src/main/java/net/causw/adapter/persistence/UserRepository.java
src/main/java/net/causw/adapter/persistence/port/CirclePortImpl.java
src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/application/Delegation.java
src/main/java/net/causw/application/DelegationFactory.java
src/main/java/net/causw/application/DelegationLeaderAlumni.java
src/main/java/net/causw/application/DelegationLeaderCircle.java
src/main/java/net/causw/application/DelegationPresident.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/CircleDto.java
src/main/java/net/causw/application/dto/LockerDetailDto.java
src/main/java/net/causw/application/dto/UserAuthDto.java
src/main/java/net/causw/application/dto/UserCircleDto.java
src/main/java/net/causw/application/dto/UserFullDto.java
src/main/java/net/causw/application/dto/UserResponseDto.java
src/main/java/net/causw/application/dto/UserUpdateRoleRequestDto.java
src/main/java/net/causw/application/spi/CirclePort.java
src/main/java/net/causw/application/spi/UserPort.java
src/main/java/net/causw/config/JwtTokenProvider.java
src/main/java/net/causw/domain/model/UserDomainModel.java
src/main/java/net/causw/domain/validation/UpdatableGrantedRoleValidator.java
src/main/java/net/causw/domain/validation/UpdatableGranteeRoleValidator.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #46 
Implement update user role
- 위임 부여 모든 경우의 update 구현
- 업데이트할 권한과 업데이트 대상에 대한 validator 따로 구현
- User의 findById 리턴을 UserFullDto로 변경

feat: Implement update user role

---

src/main/java/net/causw/adapter/persistence/port/UserCirclePortImpl.java
src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
src/main/java/net/causw/adapter/web/BoardController.java
src/main/java/net/causw/adapter/web/CircleController.java
src/main/java/net/causw/adapter/web/PostController.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/UserUpdateRequestDto.java
src/main/java/net/causw/domain/exceptions/ErrorCode.java
src/main/java/net/causw/domain/validation/AdmissionYearValidator.java
src/main/java/net/causw/domain/validation/PasswordFormatValidator.java
src/main/java/net/causw/domain/validation/UserStateValidator.java

지금까지의  Feature들에 대한 소정의 Refactoring 수행
- `Circle` `Board` `Post` 의 `findById()` 를 TODO 로 전환하였습니다 : PortImpl 등에 리팩토링 필요 (추후 API 구현 시 작업 필요)
- User update API에서 Password를 제거했습니다 : 비밀번호 수정은 별도 API로 분리
- Errorcode을 노션의 것과 동기화했습니다 -> 추후 개발 시 앞에 붙이지 말고, 반드시 뒤에 붙여주세요.

fix: refactor user APIs

---

src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/config/JwtTokenProvider.java
src/main/java/net/causw/config/WebSecurityConfig.java

fix: Fix bug JWT

---

src/main/java/net/causw/application/DelegationLeaderAlumni.java
src/main/java/net/causw/application/DelegationLeaderCircle.java
src/main/java/net/causw/application/DelegationPresident.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/domain/exceptions/ErrorCode.java
src/main/java/net/causw/domain/validation/UpdatableGrantedRoleValidator.java
src/main/java/net/causw/domain/validation/UpdatableGranteeRoleValidator.java

권한 위임에 대한 부분이 복잡해서, 주석 처리 작업을 수행했습니다.
기타 리팩토링 작업을 수행했습니다.
- 권한 위임에 대한 주석 추가
- 클라이언트 예외 처리 지원을 위해, 2가지 예외에 대한 `ErrorCode` 구분
- 지정자가 `소모임장` 혹은 `동문회장` 인 경우, `None` 상태인 유저에게도 권한이 부여되던 현상 제거

fix: refactor grant process

---

src/test/groovy/net/causw/application/UserServiceTest.groovy

fix: Fix bug in user test

---

src/main/java/net/causw/adapter/persistence/Circle.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/dto/CommentCreateRequestDto.java
src/main/java/net/causw/application/dto/UserCircleDto.java
src/main/java/net/causw/domain/model/UserDomainModel.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

- None
Refactoring test code of user service

refac: Refactoring test code of user service

---

src/main/java/net/causw/adapter/web/GlobalExceptionHandler.java
src/main/java/net/causw/domain/exceptions/ErrorCode.java

개발 과정에서 자주 발생하는 실수에 대한 처리를 지원하기 위해, HTTP Method가 적합하지 않은 경우에 대한 예외 처리 추가

fix: add http request method exception for develop

---

.gitignore
src/main/java/net/causw/adapter/persistence/Board.java
src/main/java/net/causw/adapter/persistence/Circle.java
src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
src/main/java/net/causw/adapter/persistence/port/CirclePortImpl.java
src/main/java/net/causw/adapter/web/BoardController.java
src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/dto/BoardCreateRequestDto.java
src/main/java/net/causw/application/dto/BoardResponseDto.java
src/main/java/net/causw/application/dto/PostDetailDto.java
src/main/java/net/causw/application/spi/BoardPort.java
src/main/java/net/causw/domain/model/BoardDomainModel.java
src/main/java/net/causw/domain/validation/BoardRoleValidator.java
src/main/java/net/causw/domain/validation/CorrectCircleLeaderValidator.java
src/test/groovy/net/causw/application/BoardServiceTest.groovy

feat: Implement create board

---

src/main/java/net/causw/adapter/persistence/Board.java
src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
src/main/java/net/causw/adapter/web/BoardController.java
src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/application/dto/BoardFullDto.java
src/main/java/net/causw/application/dto/BoardResponseDto.java
src/main/java/net/causw/application/dto/BoardUpdateRequestDto.java
src/main/java/net/causw/application/spi/BoardPort.java
src/main/java/net/causw/domain/model/CommentDomainModel.java
src/main/java/net/causw/domain/validation/TargetIsDeletedValidator.java
src/test/groovy/net/causw/application/BoardServiceTest.groovy

- #68 
Implement to update board
- 보드 업데이트 구현
- CircleStateValidator -> TargetIsDeletedValidator로 일반화

feat: Implement to update board

---

src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/application/dto/BoardCreateRequestDto.java
src/main/java/net/causw/application/dto/BoardUpdateRequestDto.java

fix: refactor optional logics on circle and board

---

src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/config/WebSecurityConfig.java

feat: Implement to find me

---

src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/UserPasswordUpdateRequestDto.java
src/main/java/net/causw/application/spi/UserPort.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #84 
Implement to update user password

feat: Implement to update user password

---

src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/domain/model/UserDomainModel.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

- None
Refactor static factory method in UserDomainModel
- 생성용 static factory method를 UserDomainModel에 추가
- findById에 User Role validator 추가

refac: Refactor static factory method in UserDomainModel

---

src/main/java/net/causw/adapter/persistence/port/CirclePortImpl.java
src/main/java/net/causw/adapter/web/CircleController.java
src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/application/dto/CircleUpdateRequestDto.java
src/main/java/net/causw/application/spi/CirclePort.java
src/test/groovy/net/causw/application/CircleServiceTest.groovy

- #88 
Implement to update circle

feat: Implement to update circle

---

src/main/java/net/causw/adapter/persistence/CircleMemberRepository.java
src/main/java/net/causw/adapter/persistence/port/CircleMemberPortImpl.java
src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/spi/CircleMemberPort.java
src/main/java/net/causw/application/spi/UserPort.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #48 
Implement to leave user
- 이름 검색 시에만 요청 사용자 권한 검증하도록 수정
- 소모임 수정 시, 권한이 소모임장일 때만 수정 소모임의 소모임장이 맞는지 확인하도록 수정

feat: Implement to leave user

---

src/main/java/net/causw/adapter/persistence/port/CircleMemberPortImpl.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/spi/CircleMemberPort.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #49 
Implement to get circle to which the user has joined

feat: Implement to get circle to which the user has joined

---

src/main/java/net/causw/adapter/persistence/BoardRepository.java
src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
src/main/java/net/causw/adapter/web/BoardController.java
src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/spi/BoardPort.java
src/main/java/net/causw/domain/validation/CircleMemberInvalidStatusValidator.java
src/test/groovy/net/causw/application/BoardServiceTest.groovy

- #112 
Implement board find by circle id
- FindByCircleId 구현
- CircleMemberInvalidStatusValidator에 REJECT 케이스 추가

feat: Implement board find by circle id

---

src/main/java/net/causw/adapter/persistence/CircleMemberRepository.java
src/main/java/net/causw/adapter/persistence/port/CircleMemberPortImpl.java
src/main/java/net/causw/adapter/web/CircleController.java
src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/application/spi/CircleMemberPort.java
src/test/groovy/net/causw/application/CircleServiceTest.groovy

- #87 
Implement to get user list in circle

feat: Implement to get user list in circle

---

src/main/java/net/causw/adapter/persistence/UserRepository.java
src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/spi/UserPort.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #113 
Implement find by role
- find by name 결과 값 list 로 변경

feat: Implement find by role

---

src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/domain/exceptions/ErrorCode.java
src/main/java/net/causw/domain/validation/TargetIsNullValidator.java
src/test/groovy/net/causw/application/CircleServiceTest.groovy

- #123 
Add student id validate in user apply circle

fix: Add student id validate in user apply circle

---

src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/application/DelegationFactory.java
src/main/java/net/causw/application/DelegationLeaderCircle.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/domain/validation/CircleMemberStatusValidator.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #125 
Add circle member validate in delegate leader circle

fix: Add circle member validate in delegate leader circle

---

src/main/java/net/causw/adapter/persistence/CircleMemberRepository.java
src/main/java/net/causw/adapter/persistence/port/CircleMemberPortImpl.java
src/main/java/net/causw/adapter/web/CircleController.java
src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/application/dto/CircleResponseDto.java
src/main/java/net/causw/application/spi/CircleMemberPort.java

- #127 #114 
Implement get num member of circle
- 소모임 인원 수를 받는 것은 상당히 많은 request를 예상하기 때문에, circle이 있는지 확인하는 것 외에는 예외 처리는 두지 않았습니다.
- 필요 시 circle이 있는지 확인 하는 예외 처리도 제거 할 수 있습니다.

feat: Implement get num member of circle

---

src/main/java/net/causw/adapter/persistence/BoardRepository.java
src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
src/main/java/net/causw/adapter/web/BoardController.java
src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/dto/BoardCreateRequestDto.java
src/main/java/net/causw/application/dto/BoardUpdateRequestDto.java
src/main/java/net/causw/application/spi/BoardPort.java
src/test/groovy/net/causw/application/BoardServiceTest.groovy

- #66 
Board findAll
- circleId = null, isDeleted = false 인 케이스로 조회
- Service 단위에서의 테스트 불필요

feat: board find all

---

src/main/java/net/causw/adapter/persistence/CommentRepository.java
src/main/java/net/causw/adapter/persistence/PostRepository.java
src/main/java/net/causw/adapter/persistence/port/CommentPortImpl.java
src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
src/main/java/net/causw/adapter/web/BoardController.java
src/main/java/net/causw/adapter/web/PostController.java
src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/PostService.java
src/main/java/net/causw/application/dto/PostAllResponseDto.java
src/main/java/net/causw/application/spi/CommentPort.java
src/main/java/net/causw/application/spi/PostPort.java
src/test/groovy/net/causw/application/PostServiceTest.groovy

- #109 
Implement post find all
- 보드 findById 삭제
- 포스트 findAll 구현

feat: Implement post find all

---

src/main/java/net/causw/adapter/persistence/PostRepository.java
src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
src/main/java/net/causw/adapter/web/BoardController.java
src/main/java/net/causw/adapter/web/CircleController.java
src/main/java/net/causw/adapter/web/PostController.java
src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/application/DelegationLeaderCircle.java
src/main/java/net/causw/application/PostService.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/CommentResponseDto.java
src/main/java/net/causw/application/dto/PostAllResponseDto.java
src/main/java/net/causw/application/dto/PostResponseDto.java

- #148 
- #156 
- #157 
Refactor exception
- API 명세 정의
- 필요 없는 Validate 제거 및 필요한 Validate 추가

refac: Refactor exception

---

src/main/java/net/causw/adapter/persistence/PostRepository.java
src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
src/main/java/net/causw/adapter/web/BoardController.java
src/main/java/net/causw/adapter/web/CommentController.java
src/main/java/net/causw/adapter/web/PostController.java
src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/PostService.java
src/main/java/net/causw/application/dto/BoardOfCircleResponseDto.java
src/main/java/net/causw/application/dto/BoardResponseDto.java
src/main/java/net/causw/application/spi/PostPort.java
src/test/groovy/net/causw/application/BoardServiceTest.groovy
src/test/groovy/net/causw/application/PostServiceTest.groovy

- #164 
Refactor board find by circle id
- Board의 findByCircleId의 Response를 화면에 맞게 수정

refac: Refactor board find by circle id

---

src/main/java/net/causw/adapter/persistence/LockerLocation.java
src/main/java/net/causw/adapter/persistence/LockerLocationRepository.java
src/main/java/net/causw/adapter/persistence/LockerRepository.java
src/main/java/net/causw/adapter/persistence/port/LockerLocationPortImpl.java
src/main/java/net/causw/adapter/web/LockerController.java
src/main/java/net/causw/application/LockerService.java
src/main/java/net/causw/application/dto/LockerLocationCreateRequestDto.java
src/main/java/net/causw/application/dto/LockerLocationResponseDto.java
src/main/java/net/causw/application/dto/LockerLocationUpdateRequestDto.java
src/main/java/net/causw/application/spi/LockerLocationPort.java
src/main/java/net/causw/domain/model/LockerLocationDomainModel.java

locker location create, update 구현

feat: locker location create, update implementation

---

src/main/java/net/causw/adapter/persistence/Circle.java
src/main/java/net/causw/adapter/persistence/port/CirclePortImpl.java
src/main/java/net/causw/adapter/web/CircleController.java
src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/CircleAllResponseDto.java
src/main/java/net/causw/application/dto/CircleResponseDto.java
src/main/java/net/causw/application/spi/CirclePort.java
src/main/java/net/causw/domain/model/CircleDomainModel.java
src/test/groovy/net/causw/application/CircleServiceTest.groovy

- #115 
Implement delete circle

feat: Implement delete circle

---

src/main/java/net/causw/adapter/persistence/Post.java
src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
src/main/java/net/causw/adapter/web/PostController.java
src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/PostService.java
src/main/java/net/causw/application/spi/PostPort.java
src/main/java/net/causw/domain/validation/ContentsAdminValidator.java

- #111 
소모임 삭제
- 삭제의 경우 게시글 작성자 or 관리자만 가능
- 관리자는 소모임 게시판인 경우 소모임장, 그렇지 않은 경우 학생회장을 의미
- `Update` 에서도 공통으로 사용할 수 있는, `ContentsAdminValidator` 제작

feat: post delete

---

src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
src/main/java/net/causw/adapter/web/PostController.java
src/main/java/net/causw/application/PostService.java
src/main/java/net/causw/application/dto/PostUpdateRequestDto.java
src/main/java/net/causw/application/spi/PostPort.java
src/main/java/net/causw/domain/validation/ContentsAdminValidator.java
src/main/java/net/causw/domain/validation/UserRoleValidator.java

- #110 
게시글 수정
- `UserRoleValidator` 와 `ContentsAdminValidator` 에서의 관리자 검증 로직의 순서를 바꾸었습니다.

feat: post update

---

src/main/java/net/causw/adapter/web/PostController.java
src/main/java/net/causw/application/PostService.java
src/main/java/net/causw/application/dto/PostAllWithBoardResponseDto.java
src/test/groovy/net/causw/application/PostServiceTest.groovy

- #190 
Refactor to find post all

refac: Refactor to find post all

---

src/main/java/net/causw/application/dto/PostResponseDto.java

- #192 
Refactor to post response dto

refac: Refactor to post response dto

---

src/main/java/net/causw/adapter/persistence/FavoriteBoard.java
src/main/java/net/causw/adapter/persistence/FavoriteBoardRepository.java
src/main/java/net/causw/adapter/persistence/PageableFactory.java
src/main/java/net/causw/adapter/persistence/port/FavoriteBoardPortImpl.java
src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
src/main/java/net/causw/adapter/web/HomePageController.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/HomePageService.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/HomePageResponseDto.java
src/main/java/net/causw/application/spi/FavoriteBoardPort.java
src/main/java/net/causw/application/spi/PostPort.java
src/main/java/net/causw/config/WebSecurityConfig.java
src/main/java/net/causw/domain/model/FavoriteBoardDomainModel.java

- #195 
홈 화면 구성 API 개발
- Favorite Board (즐겨찾는 게시판) Entity 구성
- Favorite Board create API 구성 (User)
- Post Pagination의 Overroading을 통한 Page Size 지정
- CORS 수정 임시 구성

feat: impl home page & favorite board

---

src/main/java/net/causw/adapter/web/CommentController.java
src/main/java/net/causw/application/CommentService.java
src/main/java/net/causw/application/PostService.java
src/main/java/net/causw/application/dto/CommentResponseDto.java
src/main/java/net/causw/application/dto/PostResponseDto.java
src/main/java/net/causw/domain/model/CircleDomainModel.java

- #192 #193 
Refactor post & comment response

Refactor post & comment response

---

src/test/groovy/net/causw/application/PostServiceTest.groovy

feat: impl post update test case

---

src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
src/main/java/net/causw/adapter/persistence/port/CircleMemberPortImpl.java
src/main/java/net/causw/adapter/persistence/port/CirclePortImpl.java
src/main/java/net/causw/adapter/persistence/port/CommentPortImpl.java
src/main/java/net/causw/adapter/persistence/port/DomainModelMapper.java
src/main/java/net/causw/adapter/persistence/port/FavoriteBoardPortImpl.java
src/main/java/net/causw/adapter/persistence/port/LockerLocationPortImpl.java
src/main/java/net/causw/adapter/persistence/port/LockerLogPortImpl.java
src/main/java/net/causw/adapter/persistence/port/LockerPortImpl.java
src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
src/main/java/net/causw/adapter/persistence/port/UserAdmissionPortImpl.java
src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java

- #170 
Refactor entity to domain model mapper

refac: Refactor entity to domain model mapper

---

src/main/java/net/causw/adapter/persistence/Locker.java
src/main/java/net/causw/adapter/persistence/LockerLog.java
src/main/java/net/causw/adapter/persistence/LockerRepository.java
src/main/java/net/causw/adapter/persistence/port/DomainModelMapper.java
src/main/java/net/causw/adapter/persistence/port/LockerLogPortImpl.java
src/main/java/net/causw/adapter/persistence/port/LockerPortImpl.java
src/main/java/net/causw/adapter/web/LockerController.java
src/main/java/net/causw/application/LockerService.java
src/main/java/net/causw/application/dto/LockerCreateRequestDto.java
src/main/java/net/causw/application/dto/LockerMoveRequestDto.java
src/main/java/net/causw/application/dto/LockerResponseDto.java
src/main/java/net/causw/application/dto/LockerUpdateRequestDto.java
src/main/java/net/causw/application/spi/LockerLogPort.java
src/main/java/net/causw/application/spi/LockerPort.java
src/main/java/net/causw/domain/model/LockerDomainModel.java

- #135 
- #136 
사물함 신규생성, 수정, 위치 이동 API 구현
- 사물함 생성 api 구현
- 사물함 수정 api 구현 (신청, 반납, 활성화, 비활성화 구분)
- 사물함 위치 이동 api 구현

feat: 사물함 신규생성, 수정, 위치이동 api 구현

---

src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/UserAdmissionResponseDto.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #177 
Implement accept & reject admission

Implement accept & reject admission

---

src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/domain/validation/UserRoleWithoutAdminValidator.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

feat: Implement drop user

---

src/test/groovy/net/causw/application/PostServiceTest.groovy

feat: impl post delete test case

---

src/main/java/net/causw/application/CommentService.java
src/test/groovy/net/causw/application/CommentServiceTest.groovy

- #139 
- #140 
TC 작업, 로직 수정
- Comment update & delete에 대한 TC 작성
- Comment service에서의 검증 로직 오류 사항에 대한 수정

feat: impl comment update & delete test case

---

src/main/java/net/causw/adapter/persistence/LockerRepository.java
src/main/java/net/causw/adapter/persistence/port/LockerLocationPortImpl.java
src/main/java/net/causw/adapter/persistence/port/LockerPortImpl.java
src/main/java/net/causw/adapter/web/LockerController.java
src/main/java/net/causw/application/LockerService.java
src/main/java/net/causw/application/spi/LockerLocationPort.java
src/main/java/net/causw/application/spi/LockerPort.java

- #137 
locker, lockerLocation delete 구현

feat: locker, lockerLocation delete impl

---

src/main/java/net/causw/application/LockerAction.java
src/main/java/net/causw/application/LockerActionDisable.java
src/main/java/net/causw/application/LockerActionEnable.java
src/main/java/net/causw/application/LockerActionFactory.java
src/main/java/net/causw/application/LockerActionRegister.java
src/main/java/net/causw/application/LockerActionReturn.java
src/main/java/net/causw/application/LockerService.java
src/main/java/net/causw/config/LockerActionConfig.java

Locker update 내의 enum별 동작에 Supplier를 사용한 Factory pattern 적용
- 각 ENUM별 class 생성 및 Factory에서 HashMap을 사용해 각 LockerAction class 반환

refac: refactor locker update factory pattern with supplier

---

src/main/java/net/causw/application/CommentService.java
src/main/java/net/causw/application/PostService.java
src/test/groovy/net/causw/application/CommentServiceTest.groovy
src/test/groovy/net/causw/application/PostServiceTest.groovy

- #217 
Refactor target is deleted validator in post & comment

refac: Refactor target is deleted validator in post & comment

---

build.gradle
src/main/java/net/causw/adapter/persistence/User.java
src/main/java/net/causw/adapter/web/StorageController.java
src/main/java/net/causw/application/StorageService.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/UploadImageResponseDto.java
src/main/java/net/causw/application/dto/UserCreateRequestDto.java
src/main/java/net/causw/application/dto/UserUpdateRequestDto.java
src/main/java/net/causw/domain/model/ImageLocation.java
src/main/resources/application-local.yaml
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #189 
- #133 
Connect to GCS
- user profile image 추가

feat: Connect to GCS

---

src/main/java/net/causw/adapter/persistence/UserAdmissionRepository.java
src/main/java/net/causw/adapter/persistence/port/UserAdmissionPortImpl.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/spi/UserAdmissionPort.java
src/main/java/net/causw/domain/exceptions/ErrorCode.java

refac: Refactor sign in

---

src/main/java/net/causw/domain/model/LockerDomainModel.java

LockerDomainModel의 lockerLocation NotNull 어노테이션 추가

fix: LockerDomainModel location 필수처리

---

src/main/java/net/causw/adapter/persistence/BoardRepository.java
src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/UserAdmissionCreateRequestDto.java
src/main/java/net/causw/application/spi/BoardPort.java
src/main/java/net/causw/domain/model/UserDomainModel.java

- #199 
유저 가입 시 즐겨찾는 게시판 자동 등록
- 관리자가 가입 승인을 진행하는 경우 자동 등록
- 가장 오래된 게시판 3개 등록
- (버그 수정) admission 등록의 경우 JWT 토큰을 발급받지 못했기 때문에, `UserAdmissionCreateRequestDto` 에서 `email` 를 받도록 수정
- 따라서 `signIn` 진행 시 최초 로그인인 경우를 판별하여, 이 경우 response에 user id를 리턴하도록 구현 필요

feat: impl auto create favorite board

---

src/main/java/net/causw/adapter/persistence/CommentRepository.java
src/main/java/net/causw/adapter/persistence/port/CommentPortImpl.java
src/main/java/net/causw/application/PostService.java
src/main/java/net/causw/application/dto/PostAllResponseDto.java
src/main/java/net/causw/application/dto/PostResponseDto.java

Post, Comment Response 수정
- 댓글 정렬 순서 내림차순 -> 오름차순 변경
- 게시글 정보에 작성자 이름, 학번, 댓글 갯수 포함

fix: modify response for post and comment

---

src/main/java/net/causw/config/WebSecurityConfig.java

fix: solve cors issue

---

src/main/java/net/causw/CauswApplication.java

feat: set time zone to UTC+9

---

src/main/java/net/causw/config/WebSecurityConfig.java

fix: allow cors for all origin

---

src/main/java/net/causw/adapter/web/CommentController.java

fix: typo in comment controller

---

src/main/java/net/causw/adapter/persistence/CommentRepository.java
src/main/java/net/causw/adapter/persistence/port/CommentPortImpl.java
src/main/java/net/causw/application/dto/CommentResponseDto.java

fix: Fix bug about comment

---

src/main/java/net/causw/adapter/persistence/BoardRepository.java
src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
src/main/java/net/causw/adapter/web/PostController.java
src/main/java/net/causw/application/PostService.java
src/main/java/net/causw/application/spi/BoardPort.java
src/main/resources/application-local.yaml

- #221 
Add app notice board
- 앱 공지사항 구현 (앱 공지사항 게시판 조회, 게시글 생성, 수정, 식제 접근 권한 설정)
- 스프링 시작 시, 앱 공지사항 자동 삽입 추가

feat: Add app notice board

---

src/main/java/net/causw/domain/model/LockerDomainModel.java
src/main/java/net/causw/domain/model/LockerLocationDomainModel.java
src/test/groovy/net/causw/application/LockerServiceTest.groovy

- #235 
locker service TC 구현
- lokcer create TC implement
- locker update TC implement
- locker move TC implement
- locker location create TC implement
- locker location update TC implement

test: lockerService TC 구현

---

src/main/java/net/causw/adapter/persistence/LockerLog.java
src/main/java/net/causw/adapter/persistence/UserAdmissionLog.java
src/main/java/net/causw/adapter/persistence/UserAdmissionLogRepository.java
src/main/java/net/causw/adapter/persistence/UserAdmissionRepository.java
src/main/java/net/causw/adapter/persistence/port/UserAdmissionLogPortImpl.java
src/main/java/net/causw/adapter/persistence/port/UserAdmissionPortImpl.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/LockerActionEnable.java
src/main/java/net/causw/application/LockerService.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/spi/UserAdmissionLogPort.java
src/main/java/net/causw/application/spi/UserAdmissionPort.java
src/main/java/net/causw/config/WebSecurityConfig.java
src/main/java/net/causw/domain/model/UserAdmissionLogAction.java
src/main/java/net/causw/domain/model/UserDomainModel.java
src/main/java/net/causw/domain/validation/UserStateIsNotDropAndActiveValidator.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #236
- #250 
Refactor create admission and Add admission log
- 유저 신청 로그 추가
- 유저 신청 accept, reject시 유저 신청은 삭제, 그리고 신청 내용은 로그에 추가
- 유저 신청이 있을 때는 다시 신청 안되는 검증 추가
- 유저가 drop, active 상태에는 신청 안되는 검증 추가

refac: Refactor create admission and Add admission log

---

src/main/java/net/causw/domain/model/CircleDomainModel.java
src/test/groovy/net/causw/application/CircleServiceTest.groovy

- #209 
Add exception about main image of circle

refac: Add exception about main image of circle

---

src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/domain/validation/UserStateIsDropValidator.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #237 
Implement restore dropped user

feat: Implement restore dropped user

---

src/main/java/net/causw/adapter/persistence/ChildComment.java
src/main/java/net/causw/adapter/persistence/ChildCommentRepository.java
src/main/java/net/causw/adapter/persistence/Comment.java
src/main/java/net/causw/adapter/persistence/CommentRepository.java
src/main/java/net/causw/adapter/persistence/port/ChildCommentPortImpl.java
src/main/java/net/causw/adapter/persistence/port/CommentPortImpl.java
src/main/java/net/causw/adapter/persistence/port/DomainModelMapper.java
src/main/java/net/causw/adapter/web/ChildCommentController.java
src/main/java/net/causw/application/ChildCommentService.java
src/main/java/net/causw/application/PostService.java
src/main/java/net/causw/application/dto/ChildCommentCreateRequestDto.java
src/main/java/net/causw/application/dto/ChildCommentResponseDto.java
src/main/java/net/causw/application/dto/ChildCommentUpdateRequestDto.java
src/main/java/net/causw/application/spi/ChildCommentPort.java
src/main/java/net/causw/domain/exceptions/BadRequestException.java
src/main/java/net/causw/domain/exceptions/BaseRuntimeException.java
src/main/java/net/causw/domain/exceptions/InternalServerException.java
src/main/java/net/causw/domain/exceptions/UnauthorizedException.java
src/main/java/net/causw/domain/model/ChildCommentDomainModel.java
src/main/java/net/causw/domain/model/CommentDomainModel.java
src/main/java/net/causw/domain/validation/ChildCommentNotEqualValidator.java
src/main/java/net/causw/domain/validation/UserNameEqualValidator.java
src/test/groovy/net/causw/application/BoardServiceTest.groovy
src/test/groovy/net/causw/application/ChildCommentServiceTest.groovy
src/test/groovy/net/causw/application/CommentServiceTest.groovy
src/test/groovy/net/causw/application/PostServiceTest.groovy

- #254 
- #253 
Implement child comment

feat: Implement child comment

---

src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/ChildCommentService.java
src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/application/CommentService.java
src/main/java/net/causw/application/LockerActionDisable.java
src/main/java/net/causw/application/LockerActionEnable.java
src/main/java/net/causw/application/LockerActionRegister.java
src/main/java/net/causw/application/LockerActionReturn.java
src/main/java/net/causw/application/LockerService.java
src/main/java/net/causw/application/PostService.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/LockerUpdateRequestDto.java
src/main/java/net/causw/domain/model/BoardDomainModel.java
src/main/java/net/causw/domain/model/ChildCommentDomainModel.java
src/main/java/net/causw/domain/model/CircleDomainModel.java
src/main/java/net/causw/domain/model/CommentDomainModel.java
src/main/java/net/causw/domain/model/LockerDomainModel.java
src/main/java/net/causw/domain/model/LockerLocationDomainModel.java
src/main/java/net/causw/domain/model/LockerLogAction.java
src/main/java/net/causw/domain/model/PostDomainModel.java
src/main/java/net/causw/domain/model/UserDomainModel.java
src/main/java/net/causw/domain/validation/LockerIsActiveValidator.java
src/main/java/net/causw/domain/validation/LockerIsDeactivatedValidator.java
src/test/groovy/net/causw/application/BoardServiceTest.groovy
src/test/groovy/net/causw/application/ChildCommentServiceTest.groovy
src/test/groovy/net/causw/application/CircleServiceTest.groovy
src/test/groovy/net/causw/application/CommentServiceTest.groovy
src/test/groovy/net/causw/application/LockerServiceTest.groovy
src/test/groovy/net/causw/application/PostServiceTest.groovy
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #257 
Refactor update domain model

refac: Refactor update domain model

---

src/main/java/net/causw/application/dto/CircleResponseDto.java

- #265 
Add createdAt in circle response dto
- 
-

refac: Add createdAt in circle response dto

---

src/main/java/net/causw/adapter/persistence/PostRepository.java
src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
src/main/java/net/causw/adapter/web/PostController.java
src/main/java/net/causw/application/PostService.java
src/main/java/net/causw/application/spi/PostPort.java
src/main/java/net/causw/domain/model/SearchOption.java
src/test/groovy/net/causw/application/PostServiceTest.groovy

feat: Implement search post

---

src/main/java/net/causw/adapter/persistence/PostRepository.java
src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/PostAllForUserResponseDto.java
src/main/java/net/causw/application/dto/UserPostResponseDto.java
src/main/java/net/causw/application/spi/PostPort.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #261 
Implement find my posts

feat: Implement find my posts

---

src/main/java/net/causw/adapter/persistence/Comment.java
src/main/java/net/causw/adapter/persistence/CommentRepository.java
src/main/java/net/causw/adapter/persistence/port/CommentPortImpl.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/CommentAllForUserResponseDto.java
src/main/java/net/causw/application/dto/CommentResponseDto.java
src/main/java/net/causw/application/dto/UserCommentResponseDto.java
src/main/java/net/causw/application/spi/CommentPort.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #262 
Implement find my comments

feat: Implement find my comments

---

src/main/java/net/causw/application/dto/BoardOfCircleResponseDto.java

- None
Refactor board of circle response dto

refac: Refactor board of circle response dto

---

build.gradle
src/main/java/net/causw/adapter/web/GlobalExceptionHandler.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/config/JwtTokenProvider.java
src/main/java/net/causw/config/MailProperties.java
src/main/java/net/causw/domain/exceptions/ErrorCode.java
src/main/java/net/causw/domain/exceptions/ServiceUnavailableException.java
src/main/java/net/causw/domain/model/ImageLocation.java
src/main/java/net/causw/infrastructure/GoogleMailSender.java
src/main/resources/application-local.yaml
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #180 
Add email service skel

feat: Add email service skel

---

src/main/java/net/causw/adapter/persistence/port/CircleMemberPortImpl.java

fix: refactor circle join status in circle all response dto

---

src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/UserResponseDto.java
src/main/resources/application-local.yaml

Refactor findCurrentUser
- 소모임장인 경우, 소모임 정보를 포함
- [] Test case

fix: refactor findCurrentUser to include circle info if leader

---

src/main/java/net/causw/application/dto/ChildCommentCreateRequestDto.java
src/main/java/net/causw/application/dto/ChildCommentUpdateRequestDto.java

DTO에서의 Optional 변수 이용 상 오류 수정
- 
-

fix: refactor optional variable in dto

---

src/main/java/net/causw/adapter/persistence/ChildCommentRepository.java
src/main/java/net/causw/adapter/persistence/port/ChildCommentPortImpl.java

fix: refactor child commnent order to ASC

---

src/main/java/net/causw/adapter/web/ChildCommentController.java
src/main/java/net/causw/application/ChildCommentService.java
src/main/java/net/causw/application/dto/ChildCommentAllResponseDto.java

- #282 
답글 findAll에 원댓글 정보 포함
- 
-

fix: refactor ChildCommentDto to include parent comment information

---

src/main/java/net/causw/application/ChildCommentService.java
src/main/java/net/causw/application/dto/ChildCommentCreateRequestDto.java
src/main/java/net/causw/application/dto/ChildCommentUpdateRequestDto.java
src/main/java/net/causw/domain/model/ChildCommentDomainModel.java
src/test/groovy/net/causw/application/ChildCommentServiceTest.groovy
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #290 
Refactor ref comment and tag user of child comment
- 수정에서 tag name과 ref comment 삭제
- 생성에서 tag name 삭제
- test code 모두 수정

refac: Refactor ref comment and tag user of child comment

---

src/main/java/net/causw/adapter/persistence/CommentRepository.java
src/main/java/net/causw/adapter/persistence/PostRepository.java
src/main/java/net/causw/adapter/persistence/port/CommentPortImpl.java
src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
src/main/java/net/causw/application/UserService.java

- None
Fix find posts and comments of user
- 내가 쓴 게시글, 댓글 조회 쿼리 수정
- 사용자 업데이트 시 프로필 반영 안되는 버그 수정

fix: Fix find posts and comments of user

---

src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/StorageService.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/UserAdmissionCreateRequestDto.java
src/main/java/net/causw/infrastructure/GcpFileUploader.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #296 
Refactor type of attachImage in user apply string to multipartfile

refac: Refactor type of attachImage in user apply string to multipartfile

---

src/main/java/net/causw/adapter/persistence/CommentRepository.java
src/main/java/net/causw/adapter/persistence/PostRepository.java

- None
Fix query about find posts and comments of user

fix: Fix query about find posts and comments of user

---

src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/CommentAllForUserResponseDto.java
src/main/java/net/causw/application/dto/PostAllForUserResponseDto.java
src/main/java/net/causw/domain/model/UserDomainModel.java
src/main/java/net/causw/infrastructure/PasswordGenerator.java
src/main/resources/application-local.yaml
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #298 
Refactor generate random password

refac: Refactor generate random password

---

src/main/java/net/causw/adapter/web/LockerController.java
src/main/java/net/causw/application/LockerService.java
src/main/java/net/causw/application/dto/LockerResponseDto.java

- #302 
LockerResponseDto 에 `isMine` 필드 추가
- DTO 수정
- JWT로부터 `userId` 를 받지 않는 일부 API 수정

fix: refactor LockerResponseDto to include isMine field

---

src/main/java/net/causw/adapter/web/LockerController.java
src/main/java/net/causw/application/LockerService.java
src/main/java/net/causw/application/dto/LockerAllResponseDto.java
src/main/java/net/causw/application/dto/LockerResponseDto.java

`LockerResponseDto` 수정
- 불필요한 정보 삭제
- LockerLocation 이름 추가

fix: refactor LockerResponseDto to include location name

---

src/main/java/net/causw/adapter/persistence/LockerLogRepository.java
src/main/java/net/causw/adapter/persistence/port/LockerLogPortImpl.java
src/main/java/net/causw/application/LockerAction.java
src/main/java/net/causw/application/LockerActionDisable.java
src/main/java/net/causw/application/LockerActionEnable.java
src/main/java/net/causw/application/LockerActionRegister.java
src/main/java/net/causw/application/LockerActionReturn.java
src/main/java/net/causw/application/LockerService.java
src/main/java/net/causw/application/dto/LockerLogDetailDto.java
src/main/java/net/causw/application/spi/LockerLogPort.java
src/main/java/net/causw/domain/model/LockerDomainModel.java
src/test/groovy/net/causw/application/LockerServiceTest.groovy

- #305 #306 #308 
fix register locker

fix: fix register locker

---

src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/UserUpdateRoleRequestDto.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #310 
Add President user give Leader Circle role

refac: Add President user give Leader Circle role

---

src/main/java/net/causw/application/UserService.java

- #316 
Refactor find by name for leader circle

refac: Refactor find by name for leader circle

---

src/main/java/net/causw/application/dto/UserAdmissionAllResponseDto.java

- None
Refactor find all user admission dto

refac: Refactor find all user admission dto

---

src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/UserAdmissionAllResponseDto.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #324 
Return locker in leave and drop user

refac: Return locker in leave and drop user

---

src/main/java/net/causw/adapter/persistence/UserRepository.java
src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/UserFindEmailRequestDto.java
src/main/java/net/causw/application/spi/UserPort.java
src/main/java/net/causw/config/WebSecurityConfig.java

feat: Implement find email

---

src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/domain/model/UserAdmissionDomainModel.java

- None
Fix user state bug in find by name
- 
-

fix: Fix user state bug in find by name

---

src/main/java/net/causw/domain/model/UserDomainModel.java

fix: remove exception process for admin account (TODO)

---

.gcloudignore
build.gradle
src/main/appengine/app.yaml

- \#(issue number)
Please include a summary of the change and which issue is fixed.
- 
-

feat: app engine 도입

---

.gitignore
src/main/appengine/app.yaml

Please include a summary of the change and which issue is fixed.
- 
-

fix: update deploy profile for app engine

---

src/main/java/net/causw/application/UserService.java

탈퇴한 이메일의 이메일 중복 체크 진행 시 handling 로직 추가
- 
-

fix: add handling for inactive & drop user rejoin

---

src/main/java/net/causw/adapter/persistence/Circle.java
src/main/java/net/causw/adapter/persistence/port/DomainModelMapper.java

소모임 삭제 시 `NullPointerException` 발생 제거
- 
-

fix: bug at removing circle

---

.github/workflows/ci.yml
build.gradle
src/test/groovy/net/causw/application/LockerServiceTest.groovy
src/test/groovy/net/causw/application/UserServiceTest.groovy

feat: Add test to CI

---

src/main/java/net/causw/domain/model/LockerDomainModel.java

Update isActive when register and return locker

fix: Update isActive when register and return locker

---

src/main/java/net/causw/application/UserService.java

최초 로그인 시 비밀번호 검증 로직이 동작하지 않는 현상 수정
- 
-

fix: exception for first sign-in

---

build.gradle

- \#(issue number)
Please include a summary of the change and which issue is fixed.
- 
-

feat: remove unused import

---

src/main/java/net/causw/application/dto/board/BoardCreateRequestDto.java
src/main/java/net/causw/application/dto/board/BoardUpdateRequestDto.java
src/main/java/net/causw/application/dto/circle/CircleCreateRequestDto.java
src/main/java/net/causw/application/dto/circle/CircleUpdateRequestDto.java
src/main/java/net/causw/application/dto/comment/ChildCommentCreateRequestDto.java
src/main/java/net/causw/application/dto/comment/ChildCommentUpdateRequestDto.java
src/main/java/net/causw/application/dto/comment/CommentCreateRequestDto.java
src/main/java/net/causw/application/dto/comment/CommentUpdateRequestDto.java
src/main/java/net/causw/application/dto/locker/LockerCreateRequestDto.java
src/main/java/net/causw/application/dto/locker/LockerLocationCreateRequestDto.java
src/main/java/net/causw/application/dto/locker/LockerLocationUpdateRequestDto.java
src/main/java/net/causw/application/dto/locker/LockerMoveRequestDto.java
src/main/java/net/causw/application/dto/locker/LockerUpdateRequestDto.java
src/main/java/net/causw/application/dto/post/PostCreateRequestDto.java
src/main/java/net/causw/application/dto/post/PostUpdateRequestDto.java
src/main/java/net/causw/application/dto/user/UserAdmissionCreateRequestDto.java
src/main/java/net/causw/application/dto/user/UserCreateRequestDto.java
src/main/java/net/causw/application/dto/user/UserFindEmailRequestDto.java
src/main/java/net/causw/application/dto/user/UserSignInRequestDto.java
src/main/java/net/causw/application/dto/user/UserUpdatePasswordRequestDto.java
src/main/java/net/causw/application/dto/user/UserUpdateRequestDto.java
src/main/java/net/causw/application/dto/user/UserUpdateRoleRequestDto.java

Request DTO의 Lombok annotation 수정
- Comment Update 의 에러 수정
-

fix: modify lombok annotation for request dto

---

readme.md

fix: update README to include app url

---

src/main/appengine/app.yaml

- \#(issue number)
Please include a summary of the change and which issue is fixed.
- 
-

feat: add default setting in yaml

---

src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/domain/model/CircleDomainModel.java

fix: change image field of circle into nullable

---

.gitignore
readme.md
src/main/appengine/app.yaml

README update (e-mail)
`app.yaml` 파일 제거
- 
-

fix: update README

---

src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/application/dto/circle/CircleMemberResponseDto.java
src/test/groovy/net/causw/application/CircleServiceTest.groovy

Refactor dto get user list of circle

refac: Refactor dto get user list of circle

---

src/main/java/net/causw/adapter/persistence/BoardRepository.java
src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
src/main/java/net/causw/adapter/web/CommonController.java
src/main/java/net/causw/application/HomePageService.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/spi/BoardPort.java

refac: Refactor home page

---

src/main/java/net/causw/application/LockerService.java
src/test/groovy/net/causw/application/LockerServiceTest.groovy

refac: Refactor to register locker

---

src/main/java/net/causw/application/CircleService.java

fix: Fix get user list of circle

---

src/main/java/net/causw/infrastructure/GcpFileUploader.java

fix: Fix GCS file path

---

.gitignore
src/main/java/net/causw/config/WebSecurityConfigProd.java
src/main/resources/application-local.yaml

Web Security 및 Config 파일 수정
- 운영서버와 개발서버에서 사용하는 `WebSecurityConfig` 파일의 분리
-

fix: modify Web Security for deployment

---

src/main/java/net/causw/infrastructure/GcpFileUploader.java

fix: Fix bug of gcs image upload

---

src/main/java/net/causw/application/dto/FileResponseDto.java
src/main/java/net/causw/application/dto/post/PostResponseDto.java
src/main/java/net/causw/domain/model/StaticValue.java
src/main/java/net/causw/domain/validation/PostNumberOfAttachmentsValidator.java

fix: update variable for attach file

---

src/main/java/net/causw/adapter/persistence/Circle.java
src/main/java/net/causw/adapter/persistence/Post.java
src/main/java/net/causw/adapter/persistence/User.java
src/main/java/net/causw/adapter/persistence/UserAdmission.java
src/main/java/net/causw/adapter/persistence/UserAdmissionLog.java

Change max length of image and attachment url

refac: Change max length of image and attachment url

---

src/main/java/net/causw/application/ChildCommentService.java
src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/application/CommentService.java
src/main/java/net/causw/application/PostService.java

- #359 
Allow admin related cirlce

refac: Allow admin related circle

---

src/main/java/net/causw/adapter/persistence/UserRepository.java
src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/spi/UserPort.java
src/main/java/net/causw/config/WebSecurityConfig.java
src/main/java/net/causw/config/WebSecurityConfigProd.java
src/main/java/net/causw/domain/validation/PasswordCorrectValidator.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

refac: Add password encoder

---

src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/spi/UserPort.java

fix: remove password all encoder

---

src/main/java/net/causw/adapter/persistence/Post.java
src/main/java/net/causw/adapter/persistence/port/DomainModelMapper.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/post/PostCreateRequestDto.java
src/main/java/net/causw/application/dto/post/PostUpdateRequestDto.java

- #370 
Fix null pointer exception of post attachments
- Post attachments 버그 수정
- Admin은 모든 동아리 조회 가능

fix: Fix null pointer exception of post attachments

---

src/main/java/net/causw/config/WebSecurityConfig.java
src/main/java/net/causw/config/WebSecurityConfigProd.java

- #376 
WebSecurityConfig 파일의 수정
- 
-

chore: update WebSecurityConfig

---

src/main/java/net/causw/adapter/persistence/Flag.java
src/main/java/net/causw/adapter/persistence/FlagRepository.java
src/main/java/net/causw/adapter/persistence/port/FlagPortImpl.java
src/main/java/net/causw/adapter/web/CommonController.java
src/main/java/net/causw/application/CommonService.java
src/main/java/net/causw/application/LockerAction.java
src/main/java/net/causw/application/LockerActionDisable.java
src/main/java/net/causw/application/LockerActionEnable.java
src/main/java/net/causw/application/LockerActionRegister.java
src/main/java/net/causw/application/LockerActionReturn.java
src/main/java/net/causw/application/LockerService.java
src/main/java/net/causw/application/spi/FlagPort.java
src/main/java/net/causw/domain/model/StaticValue.java
src/main/java/net/causw/domain/validation/LockerAccessValidator.java
src/main/java/net/causw/domain/validation/LockerInUseValidator.java
src/test/groovy/net/causw/application/LockerServiceTest.groovy

fix: modify check logic for locker register

---

src/main/java/net/causw/application/UserService.java

Fix bug of user admission in sign-in
- 
-

fix: Fix bug of user admission in sign-in

---

src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/application/dto/circle/CirclesResponseDto.java

fix: Get circle list for admin

---

src/main/java/net/causw/application/LockerService.java

- #383 
Fix bug of find all location for admin

fix: Fix bug of find all location for admin

---

src/main/java/net/causw/application/LockerActionRegister.java

사물함 신청 시 `ADMIN` 의 경우 `TimePassedValidator` 을 검사하지 않도록 변경
- 
-

fix: remove locker time pass check logic for admin

---

src/main/java/net/causw/adapter/persistence/LockerLog.java
src/main/java/net/causw/adapter/persistence/port/LockerLogPortImpl.java
src/main/java/net/causw/application/LockerActionRegister.java
src/main/java/net/causw/application/LockerService.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/spi/LockerLogPort.java

Add locker location name in locker location table

fix: Add locker location name in locker location table

---

src/main/java/net/causw/application/UserService.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #389 
Refactor user service and test code

refac: Refactor user service and test code

---

src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/CircleService.java
src/test/groovy/net/causw/application/BoardServiceTest.groovy
src/test/groovy/net/causw/application/CircleServiceTest.groovy

- #389 
Refactor circle service and test code

refac: Refactor circle and board service and test code

---

src/main/java/net/causw/adapter/persistence/LockerRepository.java
src/main/java/net/causw/adapter/persistence/port/LockerPortImpl.java
src/main/java/net/causw/application/CommentService.java
src/main/java/net/causw/application/LockerActionRegister.java
src/main/java/net/causw/application/LockerService.java
src/main/java/net/causw/application/PostService.java
src/main/java/net/causw/application/spi/LockerPort.java
src/test/groovy/net/causw/application/ChildCommentServiceTest.groovy
src/test/groovy/net/causw/application/CommentServiceTest.groovy
src/test/groovy/net/causw/application/LockerServiceTest.groovy
src/test/groovy/net/causw/application/PostServiceTest.groovy

- #389 
Refactor locker and post service and test code

refac: Refactor locker and post service and test code

---

src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/application/DelegationPresident.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/user/UserPrivilegedResponseDto.java
src/main/java/net/causw/domain/model/Role.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

- #397 
부학생회장 권한 추가
- 운영 서버 DB 변경 작업 필요
-

feat: add role vice_president

---

.github/PULL_REQUEST_TEMPLATE.md

None
refactor pull request template for github

refac: refactor pull request template for github

---

src/main/java/net/causw/adapter/persistence/Locker.java
src/main/java/net/causw/adapter/persistence/TextField.java
src/main/java/net/causw/adapter/persistence/TextFieldRepository.java
src/main/java/net/causw/adapter/persistence/port/LockerPortImpl.java
src/main/java/net/causw/adapter/persistence/port/TextFieldPortImpl.java
src/main/java/net/causw/adapter/web/LockerController.java
src/main/java/net/causw/application/LockerAction.java
src/main/java/net/causw/application/LockerActionDisable.java
src/main/java/net/causw/application/LockerActionEnable.java
src/main/java/net/causw/application/LockerActionExtend.java
src/main/java/net/causw/application/LockerActionFactory.java
src/main/java/net/causw/application/LockerActionRegister.java
src/main/java/net/causw/application/LockerService.java
src/main/java/net/causw/application/dto/locker/LockerExpiredAtRequestDto.java
src/main/java/net/causw/application/spi/TextFieldPort.java
src/main/java/net/causw/domain/exceptions/ErrorCode.java
src/main/java/net/causw/domain/model/LockerDomainModel.java
src/main/java/net/causw/domain/model/LockerLogAction.java
src/main/java/net/causw/domain/model/StaticValue.java
src/main/java/net/causw/domain/validation/ExtendLockerExpiredAtValidator.java
src/main/java/net/causw/domain/validation/LockerExpiredAtValidator.java
src/test/groovy/net/causw/application/LockerServiceTest.groovy

resolves #393 
resolves #400 
add set expire date for locker and extend expire date

feat: add set expire date for locker and extend expire date

---

src/main/java/net/causw/application/LockerActionExtend.java

resolves None
refactor extend locker validator

refac: refactor extend locker validator

---

src/main/java/net/causw/application/dto/locker/LockerResponseDto.java

resolves None
refactor locker dto

refac: refactor locker dto

---

src/main/java/net/causw/adapter/persistence/port/DomainModelMapper.java
src/main/java/net/causw/domain/model/LockerDomainModel.java
src/test/groovy/net/causw/application/LockerServiceTest.groovy

resolves None
fix bug about locker domain model

fix: fix bug about locker domain model

---

scripts/deploy-dev.sh
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/dto/duplicate/DuplicatedCheckResponseDto.java
src/main/java/net/causw/application/dto/user/UserAdmissionCreateRequestDto.java
src/main/java/net/causw/application/dto/user/UserAdmissionResponseDto.java
src/main/java/net/causw/application/dto/user/UserCreateRequestDto.java
src/main/java/net/causw/application/dto/user/UserResponseDto.java
src/main/java/net/causw/application/dto/user/UserSignInRequestDto.java
src/main/java/net/causw/application/dto/user/UserUpdateRequestDto.java
src/main/java/net/causw/application/dto/user/UserUpdateRoleRequestDto.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/config/swagger/SwaggerConfig.java

--
회원가입/로그인/승인 관련 API를 검증한 뒤 해당 엔드포인트 swagger 문서를 보강했습니다.
dto 단 설정이나 컨트롤러 validation 추가하는 코드 참고하시면 좋을 것 같습니다.
추후 UserDetailService 구현해서 토큰 자동 검증하는 코드 추가할 예정입니다.
--
개발기간: 1/20(토)~1/23(화)

feat : 회원가입/로그인/승인 관련 API 검증 및 스웨거 보강

---

src/main/java/net/causw/adapter/persistence/port/board/BoardPortImpl.java

#435 
board 업데이트 시 카테고리가 업데이트 되지 않는 문제를 확인하고 업데이트가 가능하도록 변경하였습니다.
개발기간: 20분

chore : 게시판 업데이트 시 category도 업데이트 되도록 수정

---

src/main/java/net/causw/adapter/web/PostController.java
src/main/java/net/causw/application/post/PostService.java
src/main/java/net/causw/domain/validation/CircleMemberStatusValidator.java

#439 
swagger 오류 응답값 추가를 완료하였습니다.
소모임에서 동아리로 명칭을 통일했습니다.
개발기간: 2시간

hotfix : 게시글 api swagger 오류 응답값 추가 완료

---

src/main/java/net/causw/adapter/web/BoardController.java
src/main/java/net/causw/application/board/BoardService.java
src/main/java/net/causw/domain/model/board/BoardDomainModel.java

게시글 생성시 createRoleList의 설정을 변경해주었습니다. ADMIN과 PRESIDENT는 관리자이기 때문에 별도로 설정하지 않아도 항상 입력이 되고, ALL이라고 입력시 모든 권한이 모두 입력되도록 설정해주었습니다.
validator 응답값을 일부 수정하였습니다.
개발기간: 2시간

update : 게시글 createRoleList 입력 내용 변경 및 validator 응답값 수정

---

appspec.yml
scripts/deploy.sh

fix : 쉘 스크립트 파일 분기 처리

---

.gitignore
scripts/deploy.sh

develop -> main

---

src/main/java/net/causw/domain/model/util/StaticValue.java

develop -> main 

---

src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/user/UserService.java

user API의 남은 부분에 대한 검증 및 수정을 완료하였습니다. 
시간 관계상 제가 작업한 부분들의 validation 오류 응답값 예시는 프론트 측과 상의하여 추가하지 않았습니다.
findPassword는 redis를 사용하여 변경 예정이기 때문에 제외하고 작업하였습니다.
개발기간: 3시간

feat : user API 검증 완료 후 스웨거 문서 추가

---

src/main/java/net/causw/adapter/persistence/port/user/UserPortImpl.java
src/main/java/net/causw/domain/validation/GrantableRoleValidator.java

#458 
권한이 common 일 시 권한 위임처리를 별도로 처리하지 않은 부분을 추가하였습니다.
개발기간: 15분

hotfix : 권한 위임 시 common 관련 로직 처리

---

src/main/java/net/causw/application/delegation/DelegationLeaderCircle.java
src/main/java/net/causw/application/user/UserService.java

#459 
동아리장 권한 위임 시 동아리 확인 로직을 변경하였습니다.
개발기간: 20분

hotfix : 동아리장 권한 위임 시 동아리 확인 및 권한 박탈 수정

---

src/main/java/net/causw/adapter/persistence/port/locker/LockerPortImpl.java
src/main/java/net/causw/adapter/persistence/repository/LockerRepository.java
src/main/java/net/causw/adapter/web/CommonController.java
src/main/java/net/causw/adapter/web/LockerController.java
src/main/java/net/causw/application/common/CommonService.java
src/main/java/net/causw/application/dto/locker/LockerExpiredAtRequestDto.java
src/main/java/net/causw/application/dto/locker/LockerResponseDto.java
src/main/java/net/causw/application/dto/locker/LockerUpdateRequestDto.java
src/main/java/net/causw/application/locker/LockerActionExtend.java
src/main/java/net/causw/application/locker/LockerActionRegister.java
src/main/java/net/causw/application/locker/LockerService.java
src/main/java/net/causw/application/spi/LockerPort.java

#461 
- 사물함 관련 api를 검증하였습니다. 
- 동시성 관련한 코드를 추가(lockerrepository에 비관적락 annotation 추가)하여 DB동시성을 보장하였고, 테스트 또한 완료했습니다. 
- 비관적락 수행 시 @transaction(readonly=true)일 때는 읽기 전용, @transactional일 때는 쓰기 전용 비관적 락을 고려하여 같은 메소드를 분리하였습니다. 이 과정에서 JPQL을 사용했습니다. 
test는 curl 기반으로 동시에 실행하였습니다. (test 코드 X)
개발기간:  2일

feat : 사물함 api 검증 및 동시성 구현

---

src/main/java/net/causw/adapter/persistence/port/locker/LockerPortImpl.java
src/main/java/net/causw/adapter/persistence/repository/LockerRepository.java
src/main/java/net/causw/adapter/web/CommonController.java
src/main/java/net/causw/adapter/web/LockerController.java
src/main/java/net/causw/application/common/CommonService.java
src/main/java/net/causw/application/dto/locker/LockerExpiredAtRequestDto.java
src/main/java/net/causw/application/dto/locker/LockerResponseDto.java
src/main/java/net/causw/application/dto/locker/LockerUpdateRequestDto.java
src/main/java/net/causw/application/locker/LockerActionExtend.java
src/main/java/net/causw/application/locker/LockerActionRegister.java
src/main/java/net/causw/application/locker/LockerService.java
src/main/java/net/causw/application/spi/LockerPort.java

Reverts CAUCSE/CAUSW_backend#463

Revert "feat : 사물함 api 검증 및 동시성 구현"

---

src/main/java/net/causw/adapter/persistence/repository/BoardRepository.java
src/main/java/net/causw/config/security/JwtAuthenticationEntryPoint.java
src/main/java/net/causw/domain/model/util/StaticValue.java

쿼리문 tb_board로 변경
access token 1분으로 임시변경
개발기간:

hotfix : homepage 접속시 쿼리문 오류로 인한 핫픽스

---

src/main/java/net/causw/adapter/persistence/circle/Circle.java
src/main/java/net/causw/adapter/persistence/circle/CircleMember.java
src/main/java/net/causw/adapter/persistence/comment/ChildComment.java
src/main/java/net/causw/adapter/persistence/comment/Comment.java
src/main/java/net/causw/adapter/persistence/repository/CommentRepository.java
src/main/java/net/causw/adapter/persistence/repository/PostRepository.java

hotfix : 사용자가 작성한 게시글과 댓글을 조회할때 쿼리문 상의 에러로 인해 작동하지 않던 것을 해결하였습니다.

---

src/main/java/net/causw/adapter/persistence/repository/UserAdmissionRepository.java

#480 
추가적으로 가입대기 사용자와 관련하여 에러가 발생해서 sql문의 테이블 명을 소문자로 변경하여 정상작동합니다.
개발기간:

hotfix : 유저 상태별 검색 중 가입대기 사용자와 관련한 sql 에러 해결

---

src/main/java/net/causw/adapter/persistence/port/user/UserAdmissionPortImpl.java
src/main/java/net/causw/adapter/persistence/port/user/UserPortImpl.java
src/main/java/net/causw/adapter/persistence/repository/UserAdmissionRepository.java
src/main/java/net/causw/adapter/persistence/repository/UserRepository.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/spi/UserAdmissionPort.java
src/main/java/net/causw/application/spi/UserPort.java
src/main/java/net/causw/application/user/UserService.java

#482 
유저 관리 기능에서 유저 상태에 따른 모든 유저를 검색하면서 해당 상태의 유저중에서 이름으로 검색이 가능하도록 기능을 추가하였습니다.
추가적으로 이름이 "윤민규" 일 경우 "윤"만 검색해도 검색 가능하도록 변경하였습니다.
개발기간: 2시간

feat : user 관리 시 검색 기능 추가

---

build.gradle
src/main/java/net/causw/CauswApplication.java
src/main/java/net/causw/adapter/web/StorageController.java
src/main/java/net/causw/application/storage/StorageService.java
src/main/java/net/causw/config/security/WebSecurityConfig.java
src/main/java/net/causw/config/storage/StorageConfig.java
src/main/java/net/causw/domain/model/util/S3Util.java

Spring Boot랑 Aws S3 버킷 저장소를 연결을 완료했습니다.
우선은 StorageController에 이미지를 저장하고 URL을 반환하는 API를 1개 만들어놓긴 했는데, 굳이 API를 쓰지 않고 다른 컨트롤러에서 StorageService를 참조하는 방식도 있습니다.
저는 그냥 이미지 저장소만 뚫어놨을 뿐 사실상 서비스 비즈니스 로직에 대한 이해도는 상제 명근 민규가 더 잘알것같아서 자율적으로 맡길게요
!!! Merge 하기 전
-  노션에 올려놓은 application-dev.yml / application-prod.yml 최신화 (본인 로컬 파일 + SSH로 서버상에서도 필수)
AWS에서 dev용, prod용 버킷에 모든 설정은 끝냈어요. 테스트하다가 에러나면 바로 호출부탁쓰

feat: S3 버킷 연동

---

src/main/java/net/causw/application/circle/CircleService.java

학생회장, 부학생회장 전체 동아리 조회 가능 기능 수정
개발기간: 10분

hotfix : 학생회장, 부학생회장 전체 동아리 조회 가능 기능 수정

---

src/main/java/net/causw/application/circle/CircleService.java

hotfix : findById 수정

---

src/main/java/net/causw/application/circle/CircleService.java

hotfix : circle update 메서드 수정

---

src/main/java/net/causw/adapter/persistence/port/user/UserPortImpl.java
src/main/java/net/causw/adapter/persistence/repository/UserRepository.java
src/main/java/net/causw/application/delegation/DelegationPresident.java
src/main/java/net/causw/application/dto/user/UserPrivilegedResponseDto.java
src/main/java/net/causw/application/spi/UserPort.java
src/main/java/net/causw/application/user/UserService.java

상태로 사용자를 검색할때 INACTIVE_N_DROP을 검색하면 탈퇴한 유저와 추방된 유저를 한번에 반환할 수 있게 합니다.
특별한 권한을 가진 사용자를 반환하면서 nullpointerexception이 발생하여서 리스트 타입으로 통일히였습니다.
개발기간:

hotfix : 상태 및 권한으로 유저 확인

---

src/main/java/net/causw/application/circle/CircleService.java
src/main/java/net/causw/application/dto/board/BoardOfCircleResponseDto.java
src/main/java/net/causw/application/dto/board/BoardResponseDto.java

createRoleList 로 writable을 판별할 때 로직을 변경하였습니다.
동아리가 생성될때 자동생성되는 게시판의 createRoleList가 _N_권한이 포함되어 있어서 수정하였습니다.
개발기간: 1시간

hotfix : createRoleList 관련 로직 및 값 수정

---

src/main/java/net/causw/application/dto/post/BoardPostsResponseDto.java

createRoleList에 따라서 게시글 권한이 설정되는 과정에서 로직을 추가적으로 수정하였습니다.
개발기간:

hotfix : BoardPostsResponseDto로 게시글의 정보를 반환할 때 writable 여부를 확인하는 코드 수정

---

src/main/java/net/causw/adapter/persistence/port/comment/CommentPortImpl.java
src/main/java/net/causw/adapter/persistence/repository/CommentRepository.java
src/main/java/net/causw/adapter/web/CircleController.java
src/main/java/net/causw/application/circle/CircleService.java

댓글 정렬 순서가 오름차순이 아닌 내림차순으로 되어있었습니다.

hotfix : 댓글 정렬 순서 변경

---

src/main/java/net/causw/adapter/persistence/port/comment/CommentPortImpl.java
src/main/java/net/causw/adapter/persistence/port/user/UserPortImpl.java
src/main/java/net/causw/domain/validation/GrantableRoleValidator.java

delegate 과정에서의 로직 오류를 수정하였습니다. 
개발기간:

hotfix : delgate 과정에서 로직을 수정하였습니다.

---

src/main/java/net/causw/application/locker/LockerActionRegister.java
src/main/java/net/causw/application/user/UserService.java

#532 
- 사물함 도메인 로직 변경(신청 기간엔 신청/반납 계속 가능)
- updateToken 로직 변경

fix : 사물함 도메인 로직 변경 및 updateToken 로직 변경

---

src/main/java/net/causw/application/locker/LockerActionRegister.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/domain/exceptions/ErrorCode.java
src/main/java/net/causw/domain/validation/LockerAccessValidator.java

#532 
사물함 FLAG관련 에러코드를 변경하였습니다.

fix : 사물함 errorcode 변경

---

src/main/java/net/causw/adapter/persistence/repository/UserRepository.java
src/main/java/net/causw/adapter/persistence/user/User.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/dto/user/UserCreateRequestDto.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/domain/model/enums/AcademicStatus.java
src/main/java/net/causw/domain/model/util/MessageUtil.java

#573 
새로 추가된 필드 (전화번호, 학부/학과, 학적상태, 현재 등록 완료된 학기, 졸업시기(년), 졸업시기(월)) 추가
학적상태를 나타내기 위한 enum추가
회원가입 과정에서 닉네임 중복 확인
이렇게 구현했습니다!!
아래에 테스트 결과 첨부하겠습니다
닉네임 중복시 에러
개발기간:

refactor : 회원가입 기능 리팩토링

---

build.gradle
src/main/java/net/causw/CauswApplication.java
src/main/java/net/causw/adapter/persistence/crawled/CrawledNotice.java
src/main/java/net/causw/adapter/persistence/crawled/LatestCrawl.java
src/main/java/net/causw/adapter/persistence/port/user/UserPortImpl.java
src/main/java/net/causw/adapter/persistence/repository/BoardRepository.java
src/main/java/net/causw/adapter/persistence/repository/CrawledNoticeRepository.java
src/main/java/net/causw/adapter/persistence/repository/LatestCrawlRepository.java
src/main/java/net/causw/adapter/persistence/repository/UserRepository.java
src/main/java/net/causw/adapter/web/BoardController.java
src/main/java/net/causw/adapter/web/PostController.java
src/main/java/net/causw/application/board/BoardService.java
src/main/java/net/causw/application/crawler/WebCrawlerService.java
src/main/java/net/causw/application/dto/board/BoardCreateRequestDto.java
src/main/java/net/causw/application/dto/board/BoardNameCheckRequestDto.java
src/main/java/net/causw/application/dto/board/BoardNameCheckResponseDto.java
src/main/java/net/causw/application/dto/user/UserFindPasswordRequestDto.java
src/main/java/net/causw/application/dto/util/DtoMapper.java
src/main/java/net/causw/application/post/PostService.java
src/main/java/net/causw/application/spi/UserPort.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/config/mail/MailConfig.java
src/main/java/net/causw/domain/model/enums/CrawlCategory.java
src/main/java/net/causw/infrastructure/GoogleMailSender.java

feat/webcrawler 브랜치 사용
#606 
연결된 이슈에 계획 했듯이 위와 같은 알고리즘으로 크롤러를 설계했습니다.
- 최신 공지가 뭐였는지 서버가 알고 있어야 했는데 처음에 Redis key-value 저장을 활용하려 했으나 인메모리 데이터베이스 특성상 영속성을 확보하기 힘들 것 같아 별도의 tb_latest_crawl 테이블을 만들었습니다. 확장성을 고려해 크롤링 작업을 한 사이트를 카테고리(enum)으로 추가했습니다.
- 크롤링으로 저장한 정보는 공지 여부, 제목, 내용, 연결되는 링크, 작성자, 작성일입니다. content의 경우 글자 수에 제한을 걸어야 하는 varchar보다 TEXT가 낫다고 판단했습니다. 나머지 컬럼은 스프링에 의해 varchar(255)로 매핑되어 있습니다.
- 제어문이 많아서 코드가 좀 지저분한 것 같은데 없어도 되거나 간단하게 할 수 있는 로직이 보이시는 분은 알려주세요!
```java
@Service
@RequiredArgsConstructor
public class WebCrawlerService {
private static final String LATEST_URL_KEY = "latestUrl";
private final CrawledNoticeRepository crawledNoticeRepository;
private final LatestCrawlRepository latestCrawlRepository;
//    @Scheduled(cron = "0 0 * * * *") // 매 시각 0분 0초에 실행 (배표용) …
```

feature  : 소프트웨어학부 공지사항 & 뉴스 크롤링해서 DB에 저장

---

src/main/java/net/causw/adapter/persistence/calendar/Calendar.java
src/main/java/net/causw/adapter/persistence/event/Event.java
src/main/java/net/causw/adapter/persistence/repository/CalendarRepository.java
src/main/java/net/causw/adapter/persistence/repository/EventRepository.java
src/main/java/net/causw/adapter/web/CalendarController.java
src/main/java/net/causw/adapter/web/EventController.java
src/main/java/net/causw/application/calendar/CalendarService.java
src/main/java/net/causw/application/dto/calendar/CalendarCreateRequestDto.java
src/main/java/net/causw/application/dto/calendar/CalendarResponseDto.java
src/main/java/net/causw/application/dto/calendar/CalendarUpdateRequestDto.java
src/main/java/net/causw/application/dto/calendar/CalendarsResponseDto.java
src/main/java/net/causw/application/dto/event/EventCreateRequestDto.java
src/main/java/net/causw/application/dto/event/EventResponseDto.java
src/main/java/net/causw/application/dto/event/EventUpdateRequestDto.java
src/main/java/net/causw/application/dto/event/EventsResponseDto.java
src/main/java/net/causw/application/dto/user/UserAdmissionCreateRequestDto.java
src/main/java/net/causw/application/dto/util/DtoMapper.java
src/main/java/net/causw/application/event/EventService.java
src/main/java/net/causw/domain/model/enums/ImageLocation.java
src/main/java/net/causw/domain/model/util/MessageUtil.java
src/main/java/net/causw/domain/model/util/StaticValue.java

#620 
홈 화면 관리 및 조회에 필요한 캘린더와 이벤트 배너 관련 기능을 개발하였습니다. 
개발기간: 1일

feature : 홈 화면 관리 관련 기능 개발

---

.github/workflows/dev.yml
.github/workflows/main.yml
.github/workflows/pr-dev.yml
.github/workflows/pr-main.yml
readme.md

깃허브 actions에서 발생하는 오류 수정하였습니다.
upload, download 시 v2버전의 경우 github에서 더 이상 지원하지 않아 v3버전으로 변경하였습니다
개발기간:

GitHub Actions yml 파일 에러 수정

---

src/main/java/net/causw/adapter/web/UserCouncilFeeController.java

hotfix: 학생회비 controller 오타 수정

---

src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/user/UserService.java

[회원가입 시 이미 회원가입 한 학번인지 확인하는 api](https://github.com/CAUCSE/CAUSW_backend/pull/577)
학번이 유니크값으로 변함에 따라 회원가입 과정 또는 그 외의 과정에서 이미 가입한 학번인지 확인하기 위한 api 생성하였습니다.
개발기간:

feat : 이미 가입한 학번인지 확인하는 api 추가

---

src/main/java/net/causw/application/user/UserService.java

유저 정보 업데이트에서 전화번호 / 학번을 체크하면서 중복된 학번 or 전화번호로 에러가 발생하고 있어 수정하였습니다.
개발기간:

hotfix : 개인정보 수정 학번,전화번호 체크 로직 삭제

---

src/main/java/net/causw/adapter/web/FormController.java
src/main/java/net/causw/application/dto/form/CircleRecruitFormCreateRequestDto.java
src/main/java/net/causw/application/form/FormService.java

🚩 관련사항
📢 전달사항
form api의 null 필드로 인해 동아리 모집 신청서 생성 api를 분리했습니다.
📸 스크린샷
📃 진행사항
done1
done2 (진행되었어야 하는데 미처 하지 못한 부분 혹은 관련하여 앞으로 진행되어야 하는 부분도 전부 적어서 체크 표시로 관리해주세요.)
⚙️ 기타사항
개발기간:

hotfix: Form API 동아리 모집 신청서 생성 분리

---

src/main/java/net/causw/adapter/persistence/board/BoardApply.java
src/main/java/net/causw/adapter/persistence/userAcademicRecord/UserAcademicRecordApplication.java
src/main/java/net/causw/adapter/persistence/userCouncilFee/UserCouncilFeeLog.java
src/main/java/net/causw/adapter/web/UserCouncilFeeController.java
src/main/java/net/causw/domain/model/enums/BoardApplyStatus.java

Controller의 swagger 오타 수정 및 Entity Enum 클래스들 Enumrated String으로 수정
개발기간:

fix: Controller의 swagger 오타 수정 및 Entity Enum 클래스들 Enumrated String으로 수정

---

.gitignore
build.gradle
src/main/java/net/causw/adapter/persistence/repository/circle/CircleMemberRepository.java
src/main/java/net/causw/adapter/web/CircleController.java
src/main/java/net/causw/adapter/web/UserAcademicRecordApplicationController.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/circle/CircleService.java
src/main/java/net/causw/application/dto/circle/ExportCircleMemberToExcelResponseDto.java
src/main/java/net/causw/application/dto/userAcademicRecordApplication/UserAcademicRecordApplicationResponseDto.java
src/main/java/net/causw/application/dto/util/dtoMapper/CircleDtoMapper.java
src/main/java/net/causw/application/dto/util/dtoMapper/custom/UuidFileToUrlDtoMapper.java
src/main/java/net/causw/application/excel/CircleExcelService.java
src/main/java/net/causw/application/excel/ExcelAbstractService.java
src/main/java/net/causw/application/excel/ExcelService.java
src/main/java/net/causw/application/excel/UserAcademicRecordExcelService.java
src/main/java/net/causw/application/excel/UserExcelService.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/application/userAcademicRecord/UserAcademicRecordApplicationService.java
src/main/java/net/causw/application/userCouncilFee/UserCouncilFeeService.java
src/main/java/net/causw/domain/model/enums/AcademicStatus.java
src/main/java/net/causw/domain/model/enums/FilePath.java
src/main/java/net/causw/domain/model/enums/GraduationType.java
src/main/java/net/causw/domain/model/enums/Role.java
src/main/java/net/causw/domain/model/enums/UserState.java

- 신청서(Form) 관심사 excel export 제외하고 모든 excel export api 구현
- 내장 WS Tomcat으로 변경
개발기간: 1일

feat: excel export 구현

---

src/main/java/net/causw/adapter/web/CircleController.java
src/main/java/net/causw/application/circle/CircleService.java

#666 
모든 권한의 유저가 (활동 중인) 동아리원 명단을 볼 수 있는 API를 구현하였습니다.
현재는 해당 동아리의 동아리원이 아니더라도 동아리원 명단을 볼 수 있게 설정하였고, 
동아리원이어야만 동아리원 명단을 볼 수 있게 해야한다면 수정하겠습니다!
테스트 결과
개발기간:

feat: 동아리 부원 명단 조회 기능 구현

---

src/main/resources/logback-spring.xml

fix: logback 오타 수정

---

.gitignore
src/main/resources/logback-spring.xml

fix: profile/log 수정

---

src/main/java/net/causw/adapter/web/CalendarController.java
src/main/java/net/causw/adapter/web/EventController.java
src/main/java/net/causw/adapter/web/UserController.java

MultipartFile 테스트 시 에러가 발생하여 NotNull, NotBlank 어노테이션을 삭제하였습니다.
개발기간:

hotfix: controller 단의 MultipartFile NotNull, NotBlank 어노테이션 삭제

---

src/main/java/net/causw/adapter/persistence/repository/vote/VoteRecordRepository.java
src/main/java/net/causw/application/dto/util/StatusUtil.java
src/main/java/net/causw/application/dto/util/dtoMapper/VoteDtoMapper.java
src/main/java/net/causw/application/dto/vote/VoteResponseDto.java
src/main/java/net/causw/application/post/PostService.java
src/main/java/net/causw/application/vote/VoteService.java

#660 
프론트엔드 측에서 파라미터 추가를 요청하셔서 추가하였습니다.

hotfix : VoteResponseDto에 hasVoted 파라미터 추가

---

src/main/java/net/causw/adapter/persistence/post/Post.java

게시글 삭제 API Test 도중에 Null Pointer Exception이 발생하는 것을 발견하여 Null 인지를 검사하는 로직을 추가하였습니다. 
검사 로직 추가 후 정상적으로 동작합니다.
개발기간:

Fix: Form이 Null 인 경우 NullPointer Exception이 발생하여, Null인지 검사하는 로직 추가

---

src/main/java/net/causw/adapter/persistence/user/User.java
src/main/java/net/causw/application/dto/user/UserUpdateRequestDto.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/domain/model/enums/uuidFile/FilePath.java
src/main/resources/logback-spring.xml

- 이미지 종류 변경
- user update request dto 변경
개발기간:

hotfix: post 파일 종류 변경

---

src/main/java/net/causw/adapter/web/PostController.java
src/main/java/net/causw/application/comment/ChildCommentService.java
src/main/java/net/causw/application/comment/CommentService.java
src/main/java/net/causw/application/dto/comment/ChildCommentResponseDto.java
src/main/java/net/causw/application/dto/comment/CommentResponseDto.java
src/main/java/net/causw/application/dto/post/PostCreateResponseDto.java
src/main/java/net/causw/application/dto/util/StatusUtil.java
src/main/java/net/causw/application/dto/util/dtoMapper/CommentDtoMapper.java
src/main/java/net/causw/application/dto/util/dtoMapper/PostDtoMapper.java
src/main/java/net/causw/application/post/PostService.java
src/main/java/net/causw/application/vote/VoteService.java

프론트 요청에 따라 코드를 수정했습니다. 빠르게 Merge 할 수 있게 Comment 부탁드립니다.
Post, Comment, ChildComment에 본인이 작성자인지 여부를 나타내는 isOwner 필드 추가
Post Create시 PostID 반환하도록 수정 (프론트에서 필요하다고 합니다.)
개발기간:

refactor: 게시글, 댓글, 대댓글 필드 추가 및 게시글 생성 반환값 수정

---

src/main/java/net/causw/adapter/web/LockerController.java
src/main/java/net/causw/application/common/CommonService.java
src/main/java/net/causw/application/dto/locker/LockerCreateRequestDto.java
src/main/java/net/causw/application/dto/locker/LockerLocationUpdateRequestDto.java
src/main/java/net/causw/application/dto/locker/LockerMoveRequestDto.java
src/main/java/net/causw/application/locker/LockerService.java

FE입장에서 직관적으로 이해가 가도록 path variable과 스웨거 설명을 수정했습니다.
개발기간:

hotfix: locker api들 스웨거 문서 설명 추가

---

src/main/java/net/causw/application/dto/post/PostResponseDto.java
src/main/java/net/causw/application/dto/util/dtoMapper/PostDtoMapper.java
src/main/java/net/causw/application/post/PostService.java

이전 작업에서 Post Response DTO에 isOwner (게시물 작성자인지 여부) 가 누락되어 추가하였습니다.
개발기간:

refactor: 게시글 반환값에 isOwner 필드 추가

---

src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/JoinEntity.java
src/main/java/net/causw/application/dto/util/dtoMapper/custom/UuidFileToUrlDtoMapper.java

기존에 uuidfile이 특정 api에서 영속성 컨텍스트가 끝나 제대로 join entity가 uuidfile entity를 불러오지 못해 LazyInitializationException이 발생하는 문제를 해결했습니다
관련 에러
개발기간:

hotfix: uuidfile joinEntity loading 방식 eager로 변경

---

src/main/java/net/causw/adapter/persistence/form/Form.java
src/main/java/net/causw/adapter/persistence/form/FormQuestion.java
src/main/java/net/causw/application/circle/CircleService.java
src/main/java/net/causw/application/dto/form/request/create/FormCreateRequestDto.java
src/main/java/net/causw/application/dto/form/request/create/OptionCreateRequestDto.java
src/main/java/net/causw/application/dto/form/request/create/QuestionCreateRequestDto.java
src/main/java/net/causw/application/post/PostService.java
src/main/java/net/causw/domain/model/util/MessageUtil.java

- Form validation 추가 및 수정(dto annotation valid와 일체화)
- 코드 가독성을 위한 form create 로직 모듈화
개발기간:

hotfix: form validation 로직 수정 및 모듈화

---

src/main/java/net/causw/adapter/persistence/userAcademicRecord/UserAcademicRecordApplication.java
src/main/java/net/causw/adapter/persistence/userAcademicRecord/UserAcademicRecordLog.java
src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/JoinEntity.java
src/main/java/net/causw/adapter/web/FormController.java
src/main/java/net/causw/adapter/web/UserAcademicRecordApplicationController.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/form/FormService.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/application/userAcademicRecord/UserAcademicRecordApplicationService.java
src/main/java/net/causw/application/uuidFile/UuidFileService.java
src/main/resources/logback-spring.xml

hotfix: form, user, login 버긋 ㅜ정

---

src/main/java/net/causw/adapter/persistence/repository/vote/VoteRecordRepository.java
src/main/java/net/causw/adapter/persistence/vote/Vote.java
src/main/java/net/causw/adapter/web/VoteController.java
src/main/java/net/causw/application/dto/util/StatusUtil.java
src/main/java/net/causw/application/dto/util/dtoMapper/VoteDtoMapper.java
src/main/java/net/causw/application/dto/vote/VoteOptionResponseDto.java
src/main/java/net/causw/application/dto/vote/VoteResponseDto.java
src/main/java/net/causw/application/post/PostService.java
src/main/java/net/causw/application/vote/VoteService.java

#660 
프론트측에서 원하는 파라미터 추가 및 투표 재시작 구현

fix : 투표 재시작 구현 및 VoteResponseDto에 파라미터 추가

---

src/main/java/net/causw/adapter/persistence/form/ReplySelectedOptionManager.java
src/main/java/net/causw/adapter/web/FormController.java
src/main/java/net/causw/application/form/FormService.java

hotfix: form 접근 권한 수정 및 null 방지

---

src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/config/security/JwtTokenProvider.java

fix: findCurrentUser 수정

---

src/main/java/net/causw/application/circle/CircleService.java
src/main/java/net/causw/application/dto/util/dtoMapper/CircleDtoMapper.java

circle excel export bug fix
개발기간:

fix: circle excel export

---

src/main/java/net/causw/adapter/persistence/user/User.java

fix: delete user refresh token

---

src/main/java/net/causw/adapter/persistence/repository/userAcademicRecord/UserAcademicRecordApplicationRepository.java
src/main/java/net/causw/application/userAcademicRecord/UserAcademicRecordApplicationService.java

academic record에서 repository query가 제대로 날아가지 않은 것을 발견해 수정했습니다
개발기간:

fix: 본인 학적 신청 조회 api 수정

---

src/main/java/net/causw/application/dto/userCouncilFee/UserCouncilFeeResponseDto.java
src/main/java/net/causw/application/dto/util/dtoMapper/UserCouncilFeeDtoMapper.java
src/main/java/net/causw/application/excel/CouncilFeeExcelService.java
src/main/java/net/causw/application/userCouncilFee/UserCouncilFeeService.java

학생회비 납부자 조회 시 닉네임도 함께 반환하도록 DTO에 닉네임 필드를 추가했습니다.
다만 그 과정에서 엑셀 쪽을 좀 건드려서 이 부분 반드시 확인 부탁드립니다..!
개발기간:

hotfix: 학생회비 납부자 조회 시 닉네임도 조회하도록 수정

---

src/main/java/net/causw/adapter/web/NotificationController.java
src/main/java/net/causw/application/notification/NotificationService.java

게시판에 알림설정 여부를 확인할 수 있게 추가했습니다.
개발기간:

hotfix : 알림설정 여부 확인 기능 추가

---

src/main/java/net/causw/application/post/PostService.java
src/main/java/net/causw/application/vote/VoteService.java

#660 
투표 구현과정에서 프론트 측 요구사항 추가하여 PR올립니다.

fix : voteResponseDto에 voteOption 정렬 추가

---

src/main/java/net/causw/adapter/persistence/uuidFile/UuidFile.java

fix: file url lengh fix

---

src/main/java/net/causw/application/post/PostService.java

fix: post to board

---

src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/config/security/SecurityService.java

fix: role 버그 삭제

---

src/main/java/net/causw/config/security/SecurityService.java

fix: user auth

---

src/main/java/net/causw/adapter/persistence/repository/form/ReplyRepository.java
src/main/java/net/causw/adapter/web/FormController.java
src/main/java/net/causw/application/dto/form/response/reply/UserReplyResponseDto.java
src/main/java/net/causw/application/dto/util/dtoMapper/FormDtoMapper.java
src/main/java/net/causw/application/form/FormService.java

현재 각 유저의 동아리 신청 응답 조회 API가 없어 구현하였습니다
개발기간:

feat: 각 유저의 동아리 신청 조회 API 구현

---

src/main/java/net/causw/application/dto/form/response/reply/UserReplyResponseDto.java
src/main/java/net/causw/application/dto/util/dtoMapper/FormDtoMapper.java
src/main/java/net/causw/application/form/FormService.java

프론트 요청에 따라 각 유저별 동아리 신청서 응답 조회시 질문도 같이 반환하도록 변경하였습니다.
개발기간:

refactor: 각 유저별 동아리 신청서 응답 조회시 질문도 같이 반환하도록 변경

---

src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/JoinEntity.java

fix: JoinEntity OneToOne -> ManyToOne

---

src/main/java/net/causw/application/dto/post/PostsResponseDto.java
src/main/java/net/causw/application/dto/util/dtoMapper/PostDtoMapper.java
src/main/java/net/causw/application/homepage/HomePageService.java
src/main/java/net/causw/application/post/PostService.java
src/main/java/net/causw/application/user/UserService.java

게시판에서 게시글 목록을 볼 때 썸네일을 포함하여 반환하도록 변경하였습니다.
썸네일은 게시글에 포함된 사진 목록 중 첫 번째 사진으로 설정하였습니다.
개발기간:

hotfix: 게시글 미리보기 시 썸네일을 표시하도록 변경

---

src/main/java/net/causw/application/post/PostService.java

fix: post 썸네일 파일 이미지 파일만 적용 되게 수정

---

.github/workflows/pr-qa.yml
.github/workflows/qa.yml

feat: 개발 환경 분리

---

src/main/java/net/causw/CauswApplication.java

chore: swagger default server url 변경(https 반영 위함)

---

src/main/java/net/causw/application/user/UserService.java

fix: user isV2 update 준영속 상태 버그 임시 수정

---

src/main/java/net/causw/adapter/persistence/user/User.java
src/main/java/net/causw/adapter/web/BoardController.java

- User의 CircleMember @OneToMany 설정이 제대로 되어 있지 않을 것을 발견해 의도한 DB 스키마에 맞게 수정했습니다
- Board 스웨거에서 response 오타를 수정해 문서화 반영을 했습니다.
개발기간:

hotfix: user OneToMany DB 칼럼명 오타 수정 및 Board 스웨거 오타 수정

---

src/main/java/net/causw/adapter/persistence/repository/user/UserAdmissionRepository.java

[fix : 가입 대기 사용자 확인 api 500에러 수정 #746](https://github.com/CAUCSE/CAUSW_backend/issues/746)
엔티티 변경 후 쿼리문이 변경되지 않아 500에러가 발생하고 있어 수정하였습니다
개발기간:

Fix : UserAdmission 쿼리문 500에러 수정 (#746)

---

src/main/java/net/causw/adapter/persistence/repository/user/UserAdmissionRepository.java
src/main/java/net/causw/application/user/UserService.java

- 기존 모든 user admission 조회는 user state가 await인 admission만 조회했는데, 거절 유저의 경우 재 신청을 하면 관리자 입장에서 조회가 되지 않는 문제 해결
- 거절, 추방 사유 조작자에게 업데이트 되는 버그 해결
개발기간: 3시간

fix: user admission 버그 픽스

---

src/main/java/net/causw/adapter/persistence/board/BoardApply.java
src/main/java/net/causw/application/board/BoardService.java
src/main/java/net/causw/application/dto/board/NormalBoardApplyRequestDto.java
src/main/java/net/causw/application/dto/board/NormalBoardApplyResponseDto.java
src/main/java/net/causw/application/dto/util/dtoMapper/BoardDtoMapper.java

- board 생성 관련 api에서 circle 제대로 인식 못하는 문제 수정
개발기간:

hotfix: board 생성 관련 api에서 circle 제대로 인식 못하는 문제 수정

---

src/main/java/net/causw/application/dto/locker/LockerExpiredAtRequestDto.java

locker set expiredAt request dto valid anotation 변경
개발기간:

hotfix: locker set expiredAt request dto valid anotation 변경

---

src/main/java/net/causw/adapter/web/LockerController.java

- locker controller 권한 검증 로직 수정
개발기간:

hotfix: locker controller 권한 검증 로직 수정

---

src/main/java/net/causw/application/post/PostService.java

기존에 게시글 작성자는 자신의 게시글을 삭제할 수 없는 문제를 해결하였습니다.
개발기간:

fix : 게시글 작성자도 게시글을 삭제할 수 있도록 수정

---

src/main/java/net/causw/adapter/web/LockerController.java
src/main/java/net/causw/application/post/PostService.java

- 게시글 생성에 기존 레거시 코드 validator를 제거했습니다.
개발기간:

fix: post 중복 validator 제거

---

src/main/java/net/causw/application/dto/ceremony/UpdateCeremonyStateRequestDto.java

fix : push-notification

---

src/main/java/net/causw/application/locker/LockerService.java

fix : update locker create

---

src/main/java/net/causw/application/dto/user/UserUpdateRoleRequestDto.java
src/main/java/net/causw/application/user/UserService.java

기존에 role이 COMMON이었던 유저에게 권한 위임 시
COMMON role이 삭제되지 않는 버그를 발견하여 이를 수정하였습니다.
추가로 동아리장 관련 권한 위임 로직을 주석 처리하였고,
권한 위임 API의 body DTO의 circleId도 주석 처리하였습니다.
개발기간:

fix: 권한 위임 시 COMMON role이 삭제되지 않는 버그 수정

---

src/main/java/net/causw/adapter/persistence/user/User.java
src/main/java/net/causw/application/dto/circle/ExportCircleMemberToExcelResponseDto.java
src/main/java/net/causw/application/dto/form/response/reply/ReplyUserResponseDto.java
src/main/java/net/causw/application/dto/user/UserCreateRequestDto.java
src/main/java/net/causw/application/dto/user/UserFindIdRequestDto.java
src/main/java/net/causw/application/dto/user/UserFindPasswordRequestDto.java
src/main/java/net/causw/application/dto/user/UserResponseDto.java
src/main/java/net/causw/application/dto/user/UserUpdateRequestDto.java
src/main/java/net/causw/application/dto/userCouncilFee/CreateUserCouncilFeeWithFakeUserRequestDto.java
src/main/java/net/causw/application/dto/userCouncilFee/UserCouncilFeeResponseDto.java
src/main/java/net/causw/application/user/UserService.java

hotfix : 전화번호 양식 통일

---

src/main/java/net/causw/application/userAcademicRecord/UserAcademicRecordApplicationService.java

학적 상태 중복 신청 시 closed 처리가 Repository.save 메서드를 호출하지 않아 제대로 DB에 반영 안 되는 문제가 있었습니다.
제대로 Repository.save 호출해 DB에 저장되도록 버그 픽스했습니다.
이외에도 로직 설명하는 주석 코드에 맞춰 간단히 수정했습니다.
개발기간: 30분

fix: 학적 상태 중복 신청 시 closed 처리 제대로 DB에 반영 안 되는 문제 해결

---

src/main/java/net/causw/application/user/UserService.java

사용자가 휴대폰번호가 없을 경우가 고려가 안되어있어서 휴대폰번호는 프론트에서 받긴하지만 사용하지 않는것으로 임시조치했습니다
개발기간:

hotfix : 비밀번호 찾기 수정

---

src/main/java/net/causw/application/post/PostService.java

hotfix : 게시글 썸네일 첫번째 사진 파일로 수정

---

src/main/java/net/causw/adapter/persistence/repository/user/UserRepository.java
src/main/java/net/causw/application/user/UserService.java

hotfix : 아이디 찾기 수정(전화번호 제외)

---

src/main/java/net/causw/application/dto/user/UserFindIdRequestDto.java
src/main/java/net/causw/application/dto/user/UserFindPasswordRequestDto.java
src/main/java/net/causw/application/user/UserService.java

hotfix : 아이디, 비밀번호 찾기 전화번호 삭제

---

src/main/java/net/causw/application/dto/user/UserUpdateRoleRequestDto.java

동아리 기능 삭제에 따라 권한 위임 시 동아리id를 입력하지 않아도 되도록 수정하였습니다.
개발기간:

hotfix: 권한 위임 시 동아리 id 미입력을 허용하도록 수정

---

src/main/java/net/causw/adapter/web/PostController.java

#816 
게시글 즐겨찾기에 대한 API 메서드 변경이 필요한 과업인것으로 이해하였기에 수행했습니다.
다만, 기존 로직에 대한 테스트코드는 작성하지 못했습니다.
이후 스프린트에서 진행하겠습니다.
개발기간:

feat: 즐겨찾기 취소 API 메서드 PUT에서 DELETE 로 변경

---

src/main/java/net/causw/adapter/web/VoteController.java

#812 
투표 생성시 유효성 검사가 제대로 진행되지 않아 발생하고 있던 이슈였고, `@Valid` 어노테이션을 추가하여 유효성 검사 진행되도록 수정했습니다.
투표 도메인 관련 테스트코드 작성은 아직 진행하지 못한 상태입니다.
개발기간:

fix: 투표 생성 시 validation 적용되지 않는 이슈

---

src/main/java/net/causw/application/dto/ceremony/CreateCeremonyNotificationSettingDto.java

#781 
경조사 설정시 lombok getter 에러로 인해 정상적인 boolean 값을 인지하지 못해서 수정하였습니다.
개발기간:

hotfix : 경조사 설정 dto lombok getter에러로 인한 수정

---

src/main/java/net/causw/adapter/web/CeremonyController.java
src/main/java/net/causw/application/ceremony/CeremonyService.java
src/main/java/net/causw/application/dto/ceremony/CeremonyResponseDto.java
src/main/java/net/causw/application/dto/notification/CeremonyNotificationDto.java
src/main/java/net/causw/domain/model/enums/ceremony/CeremonyCategory.java
src/test/java/net/causw/application/notification/CeremonyNotificationServiceTest.java

#781 
관리자의 경조사 목록 및 사용자의 경조사 목록 확인시 적절하지 못한 dto를 공급하고 있어, id,title, body를 가지고 있는 CeremonyNotificationDto로 변경하였습니다.
개발기간:

hotfix : 경조사 반환 CeremonyNotificationDto로 변경

---

.github/workflows/dev-cd.yml
.github/workflows/dev-ci.yml
.github/workflows/main-cd.yml
.github/workflows/main-ci.yml

chore: CD의 아티팩트 이름과 경로 수정 등

---

.github/workflows/dev-cd.yml
.github/workflows/main-cd.yml

hotfix: 배포 전 빌드 작업을 build에서 bootJar로 변경

---

.github/workflows/dev-cd.yml
.github/workflows/main-cd.yml

hotfix: 아티팩트 업로드시 디렉토리 구조 유지 문제 해결 

---

app-main/src/main/java/net/causw/app/main/domain/validation/UserRoleValidator.java

[게시글 작성 권한](https://www.notion.so/2463d138d33c80f69660ceaf23608a29)
내용을 상세히 적어주세요.
개발기간:

fix: 접근 권한 에러 메시지 사용자용으로 변경

---

.gemini/config.yaml
.gemini/styleguide.md

#915 
Gemini 코드 리뷰 도구의 기본 설정 파일과 코드 리뷰 스타일 가이드를 추가합니다.
이는 코드 리뷰 자동화 및 일관성 유지를 목표로 합니다.
개발기간:

chore: Gemini 설정 및 코드 리뷰 스타일 가이드 추가

---

.github/workflows/dev-cd.yml
.github/workflows/main-cd.yml
app-main/gradle/flyway/flyway-config.gradle

#939
- app-main/gradle/flyway/flyway-config.gradle 파일에 환경별 설정 추가
- dev-cd.yml 파일에서 옵션 넣는 부분 삭제 및 repair 명령어 실행 추가
- main-cd.yml 파일에서 옵션 넣는 부분 삭제 및 repair 명령어 실행 추가
개발기간:

[Infra] github actions에서 flyway 환경별 설정 적용 및 repair 후 실행하도록 수정

---

app-main/gradle/flyway/flyway-config.gradle

chore: test환경 설정 추가

---

app-main/src/main/java/net/causw/app/main/domain/model/entity/user/User.java

hotfix : 프로필 전화번호 업데이트 수정

---

app-main/src/main/java/net/causw/app/main/dto/comment/ChildCommentResponseDto.java
app-main/src/main/java/net/causw/app/main/dto/comment/CommentResponseDto.java
app-main/src/main/java/net/causw/app/main/dto/post/PostsResponseDto.java
app-main/src/main/java/net/causw/app/main/service/comment/ChildCommentService.java
app-main/src/main/java/net/causw/app/main/service/comment/CommentService.java
app-main/src/main/java/net/causw/app/main/service/post/PostService.java
app-main/src/main/java/net/causw/app/main/service/user/UserService.java

fix: 익명 댓글의 유저 정보가 감춰지지 않는 이슈

---

app-main/src/main/java/net/causw/app/main/dto/comment/ChildCommentResponseDto.java
app-main/src/main/java/net/causw/app/main/dto/comment/CommentResponseDto.java
app-main/src/main/java/net/causw/app/main/dto/post/PostsResponseDto.java
app-main/src/main/java/net/causw/app/main/service/comment/ChildCommentService.java
app-main/src/main/java/net/causw/app/main/service/comment/CommentService.java
app-main/src/main/java/net/causw/app/main/service/post/PostService.java
app-main/src/main/java/net/causw/app/main/service/user/UserService.java

* feat: commentDtoMapper에 익명 유저 관련 메서드 추가
* fix: 기존 유저정보 익명처리하지 않던곳 수정
* revert: setDisplayName 삭제했던 부분 되돌림
* feat: childCommentService 에서도 setDisplayWriterNickname 수행하도록 수정
내용을 상세히 적어주세요.
개발기간:

fix: 익명 댓글의 유저 정보가 감춰지지 않는 이슈 (#957)

---

app-main/src/main/java/net/causw/app/main/domain/model/entity/userInfo/UserCareer.java
app-main/src/main/java/net/causw/app/main/dto/userInfo/UserCareerDto.java
app-main/src/main/java/net/causw/app/main/service/userInfo/UserInfoService.java
app-main/src/main/resources/db/migration/V20250831140709__ModifyUserCareerEndDateNullable.sql
app-main/src/test/java/net/causw/app/main/service/userInfo/UserInfoServiceTest.java

#964 
재직중인 회사는 종료일이 없음. 따라서 null값을 허용하도록 함
프론트에서 달력을 선택하지 않으면 기본값이 0이라서 현재 로컬에서는 실패하지만 스웨거에서는 잘 됩니다!
개발기간: 1d

[FIX] 현재 재직중인 경력 추가할 수 있도록 변경

---

app-main/src/main/java/net/causw/app/main/controller/LockerController.java
app-main/src/main/java/net/causw/app/main/domain/validation/ExtendLockerExpiredAtValidator.java
app-main/src/main/java/net/causw/app/main/domain/validation/LockerAccessValidator.java
app-main/src/main/java/net/causw/app/main/domain/validation/LockerExpiredAtValidator.java
app-main/src/main/java/net/causw/app/main/dto/locker/LockerExtendPeriodRequestDto.java
app-main/src/main/java/net/causw/app/main/dto/locker/LockerRegisterPeriodRequestDto.java
app-main/src/main/java/net/causw/app/main/dto/locker/LockerResponseDto.java
app-main/src/main/java/net/causw/app/main/repository/locker/LockerRepository.java
app-main/src/main/java/net/causw/app/main/service/locker/LockerActionExtend.java
app-main/src/main/java/net/causw/app/main/service/locker/LockerActionRegister.java
app-main/src/main/java/net/causw/app/main/service/locker/LockerActionReturn.java
app-main/src/main/java/net/causw/app/main/service/locker/LockerService.java
global/src/main/java/net/causw/global/constant/MessageUtil.java
global/src/main/java/net/causw/global/constant/StaticValue.java
global/src/main/java/net/causw/global/exception/ErrorCode.java

feat : 사물함 연장기능 main 반영

---

app-main/src/main/java/net/causw/app/main/domain/model/enums/uuidFile/FilePath.java

#971 
이미지 개수 상한을 20개로 수정했습니다.
개발기간:

feat: 게시물 개수 상한 변경

---

app-main/src/main/java/net/causw/app/main/service/crawler/CrawledToPostTransferService.java
app-main/src/main/java/net/causw/app/main/service/crawler/CrawlingScheduler.java
app-main/src/test/java/net/causw/app/main/service/crawler/CrawledToPostTransferServiceTest.java

#976 
- 크롤링 시간을 매시각 정시로 변경했습니다. (1시간마다 크롤링, 5분후 게시)
- 게시글 생성 과정에서 푸시 알림을 보내도록 수정했습니다.
x
테스트는 개발계 머지된 후 해보겠습니다.
개발기간: 3h

[Feat] 소프트 공지 크롤링 푸시 알림

---

app-main/src/main/java/net/causw/app/main/service/crawler/CrawledToPostTransferService.java

#979 
- 수정된 게시글은 알림을 전송하지 않고
- 새로 발견되어 작성된 게시글만 알림을 전송합니다.
x
개발기간: 30m

hotfix: 크롤링 알림 오류 수정

---

app-main/src/main/java/net/causw/app/main/service/user/useCase/RegisterGraduatedUsersUseCaseService.java

feat: CSV 파일 내의 이메일, 전화번호, 학번 중복 검사 추가

---

app-main/src/main/java/net/causw/app/main/domain/model/entity/user/User.java

#1001 
- 문제 해결을 위해 임시로 fcm 토큰을 eagerLoading으로 전환합니다.
개발기간:

feat: fcm 토큰 eagerLoading으로 롤백
