docker-compose.yaml

- None
로컬 테스트 진행 시 사용할 수 있는 Docker-compose 파일입니다. 앱 또한 docker로 구동하는 것을 고려하여 docker-compose로 구성했습니다.
이 PR이 머지되는 경우, Pull 받으신 후 터미널에서 다음 명령어를 이용할 수 있습니다.
```
docker-compose -f docker-compose.yaml up -d   // 실행
docker-compose -f docker-compose.yaml down   // 종료 및 이미지 삭제
```
그 외에도 `docker ps` 와 같은 명령어들이 있으니 검색해보면서 공부해보시면 좋습니다.
우선은 `application.yaml` 파일에서 지정한, 로컬용 id / pw를 입력해 두었는데, 추후 만약 서버에서 이 파일로 db를 구동하게 되면 환경변수로 입력하도록 할 예정입니다. (그럴 경우 이 파일도 바뀌어야 합니다)
- Add docker-compose file

[feat] docker file to run database in local test

---

src/main/java/net/causw/application/dto/ExceptionDto.java
src/main/java/net/causw/domain/exceptions/BadRequestException.java
src/main/java/net/causw/domain/exceptions/BaseRuntimeExeption.java
src/main/java/net/causw/domain/exceptions/ErrorCode.java
src/main/java/net/causw/domain/exceptions/InternalServerException.java
src/main/java/net/causw/domain/exceptions/UnauthorizedException.java
src/main/java/net/causw/infra/port/UserPortImpl.java
src/main/java/net/causw/web/GlobalExceptionHandler.java

- #20 
Back-end 앱 전체에서 사용할 기본 Exception Model입니다.
- 앱 내에서 발생한 모든 에러는 `web/GlobalExceptionHandler` 에서 처리합니다. 우선은 `400 Bad Request` 발생 시 이를 처리하는 `handleBadRequestException` 메소드를 만들었으며, 정의한 에러 외의 모든 에러를 처리하는 `unknownException` 메소드를 만들어 두었습니다. 이는 `500 Internal Server Error` 타입으로 클라이언트에게 전달됩니다.
- 에러 모델은 `domain/exceptions/` 패키지 내부에 정의했습니다. `BaseRuntimeException` abstract class에서 기본적인 틀을 다루며, 필드로는 간단하게 `errorCode` 와 `message` 를 갖습니다.
- 우선은 하위 클래스로 `BadRequestException` 과 `InternalServerException` 을 두었으며, 이용 방법은 간단하게, 로직 구현 할 때 예외 처리 시 부합하는 에러 클래스 객체를 생성해서 `throw` 하면 됩니다.
=> 예제로 `UserPortImpl` 에서 `findById` 진행 시 유저가 없는 경우, `BadRequestException` 을 던져줍니다.
- ErrorCode의 경우에는 노션에 정리해두겠습니다. 추후 구현하시면서 새로운 에러 타입이 필요한 경우, 혹은 에러 코드가 필요한 경우 만들어서 쓰시고 노션에만 잘 정리해주세요.

feat: impl basic exception model

---

src/main/java/net/causw/adapter/persistence/Board.java
src/main/java/net/causw/adapter/persistence/Comment.java
src/main/java/net/causw/adapter/persistence/CommentRepository.java
src/main/java/net/causw/adapter/persistence/Post.java
src/main/java/net/causw/adapter/persistence/User.java
src/main/java/net/causw/adapter/persistence/port/CommentPortImpl.java
src/main/java/net/causw/adapter/web/CommentController.java
src/main/java/net/causw/application/CommentService.java
src/main/java/net/causw/application/dto/CommentCreateRequestDto.java
src/main/java/net/causw/application/dto/CommentDetailDto.java
src/main/java/net/causw/application/dto/CommentFullDto.java
src/main/java/net/causw/application/dto/CommentResponseDto.java
src/main/java/net/causw/application/spi/CommentPort.java

comment entity 구현
- findById api만 우선 구현
- 1:N 관계에 있어서, 테이블마다 이상한 컬럼이 생성되어 이에 대해 mappedBy로 변경

feat: comment entity 구현, 1:N entity mappedBy 수정, findById, create 구현

---

src/main/java/net/causw/adapter/persistence/UserCircle.java
src/main/java/net/causw/adapter/persistence/port/UserCirclePortImpl.java
src/main/java/net/causw/adapter/web/CircleController.java
src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/application/spi/UserCirclePort.java
src/main/java/net/causw/domain/exceptions/ErrorCode.java
src/main/java/net/causw/domain/model/CircleDomainModel.java
src/main/java/net/causw/domain/model/UserCircleStatus.java
src/main/java/net/causw/domain/validation/UserCircleStateAwaitValidator.java
src/main/java/net/causw/domain/validation/UserEqualValidator.java
src/test/groovy/net/causw/application/CircleServiceTest.groovy

- #85 
유저 소모임 신청 승인 / 거절
- 기존 `UserCirclePortImpl` 의 `accept` 를 제거하고 `updateStatus()` 로 통일하였으며, 이에 대한 선택 주체를 `UserCircleService` 로 넘겼습니다: Service 레벨에서의 과한 코드 중복 방지
- 소모임장에 한정하여 `AWAIT` 상태인 신청을 `Accept` 혹은 `Reject` 상태로 변경할 수 있는 기능을 구현했습니다.
- 관리자 (ADMIN) 도 해당 API 의 권한을 갖도록 추후 업데이트가 필요합니다.

feat: accept & reject user of circle

---

src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
src/main/java/net/causw/adapter/persistence/port/CirclePortImpl.java
src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/CircleService.java
src/main/java/net/causw/application/spi/CirclePort.java
src/main/java/net/causw/domain/model/BoardDomainModel.java
src/main/java/net/causw/domain/model/CircleDomainModel.java
src/test/groovy/net/causw/application/BoardServiceTest.groovy
src/test/groovy/net/causw/application/CircleServiceTest.groovy

Circle, Board 의 Domain model의 리팩토링
- Default 값 지정을 Domain model 내부에서 지정하는 형태로 변경
- Circle domain model의 Constraint validator 추가

fix: refactor circle & board domain model

---

src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
src/main/java/net/causw/adapter/web/BoardController.java
src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/dto/BoardUpdateRequestDto.java
src/main/java/net/causw/application/spi/BoardPort.java
src/main/java/net/causw/domain/model/BoardDomainModel.java
src/test/groovy/net/causw/application/BoardServiceTest.groovy

- #69 
Implement to delete board
- 보드 삭제 구현
- 보드 업데이트 시 소모임 id 확인 방법을 BoardUpadateRequestDto에서 조회한 BoardDomainModel로 수정

feat: Implement to delete board

---

src/main/java/net/causw/CauswApplication.java
src/main/java/net/causw/adapter/persistence/BaseEntity.java
src/main/java/net/causw/adapter/persistence/Board.java
src/main/java/net/causw/adapter/persistence/Comment.java
src/main/java/net/causw/adapter/persistence/Post.java
src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
src/main/java/net/causw/adapter/persistence/port/CommentPortImpl.java
src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
src/main/java/net/causw/adapter/web/CommentController.java
src/main/java/net/causw/adapter/web/PostController.java
src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/CommentService.java
src/main/java/net/causw/application/PostService.java
src/main/java/net/causw/application/dto/BoardResponseDto.java
src/main/java/net/causw/application/dto/BoardUpdateRequestDto.java
src/main/java/net/causw/application/dto/CommentCreateRequestDto.java
src/main/java/net/causw/application/dto/CommentResponseDto.java
src/main/java/net/causw/application/dto/PostCreateRequestDto.java
src/main/java/net/causw/application/dto/PostResponseDto.java
src/main/java/net/causw/application/spi/BoardPort.java
src/main/java/net/causw/application/spi/CommentPort.java
src/main/java/net/causw/application/spi/PostPort.java
src/main/java/net/causw/domain/model/BoardDomainModel.java
src/main/java/net/causw/domain/model/CommentDomainModel.java
src/main/java/net/causw/domain/model/PostDomainModel.java
src/test/groovy/net/causw/application/BoardServiceTest.groovy
src/test/groovy/net/causw/application/CircleServiceTest.groovy

Board, Post, Comment의 리팩토링 수행
- Comment -> Post -> Board -> Circle 순서로 이어지는 관계에서 성능을 고려하여 Domain Level에서 Comment - Post 사이의 연관 관계를 잘라냈습니다 (CommentDomainModel에서는 Post Id만 보유하도록)
- ResponseDto와 DomainModel에 대한 전반적인 수정을 진행했습니다.
- Comment, Post의 일부 API에 대한 validation은 리팩토링 PR의 규모가 너무 커지는 것 같아 TODO로 남겨두었습니다. 다음 PR에서 TC와 함께 구현하도록 하겠습니다.

fix: refactor board, post, comment structure

---

src/main/java/net/causw/application/dto/CommentResponseDto.java

Comment response 수정
- 작성자 입학년도 추가
- 작성자 id 삭제 (기존에 updatable, deletable 을 위해 넣었으나, 파라미터 추가했으므로 프론트에서 불필요)
- parent comment id 삭제 (작성 시에도, 프론트에서 위치 확인 가능하다고 함)

fix: modify comment response

---

src/main/java/net/causw/application/LockerActionDisable.java
src/main/java/net/causw/application/LockerActionEnable.java
src/main/java/net/causw/application/LockerActionRegister.java
src/main/java/net/causw/application/LockerActionReturn.java
src/main/java/net/causw/application/LockerService.java
src/test/groovy/net/causw/application/LockerServiceTest.groovy

DomainModel의 of 메소드 사용 줄이기
- LockerService update, updateLocation 함수에서 of말고 setter 사용
- TC에 of로 object 매핑해주는부분 삭제

refac: LockerService update 메소드 내부 수정

---

src/main/java/net/causw/adapter/persistence/port/ChildCommentPortImpl.java
src/main/java/net/causw/adapter/persistence/port/CommentPortImpl.java

Post findById 호출 시 Internal Server Error 발생 현상 수정
- JPA에서 반환하는 Page의 content list는 immutable list이기 때문에 sort가 불가 -> 제거
- 다시 정렬을 하거나, Pageable을 custom하여 해결이 가능하지만, 불필요한 작업으로 고려되어 프론트와의 협의를 통해 역순으로 전달하면 프론트에서 뷰 구성 시 정렬하는 것으로 결정

fix: internal server error on get post caused by comment sort

---

src/main/java/net/causw/application/dto/ChildCommentResponseDto.java
src/main/java/net/causw/application/dto/CommentResponseDto.java
src/main/java/net/causw/domain/model/StaticValue.java

- #278 
삭제된 댓글의 content 수정
- String 값 static value 이용
-

fix: refactor content in CommentResponseDto for deleted case

---

src/main/java/net/causw/adapter/persistence/LockerRepository.java
src/main/java/net/causw/adapter/persistence/port/LockerPortImpl.java
src/main/java/net/causw/adapter/web/LockerController.java
src/main/java/net/causw/application/LockerActionEnable.java
src/main/java/net/causw/application/LockerService.java
src/main/java/net/causw/application/dto/LockerAllLocationResponseDto.java
src/main/java/net/causw/application/spi/LockerPort.java

- #301 
findAllLocations 에 본인 사물함 정보 포함
- LockerPort에 `findByUserId` 신규 구현
- `LockerLocationResponseDto` 의 수정
- Locker `findAll` 의 리스트를 번호 오름차순으로 정렬되도록 수정

fix: refactor locker findAllLocations to include my locker information

---

src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/UserService.java

- #311 
관리 페이지를 위한 user `findById` API 구현
- 기존 API들 중 `LEADER_CIRCLE` 의 `ResponseDto` 가 잘못 구성된 경우의 수정
- 기존 `/me` API 에서 사용하던 `findById` 에 오버로딩 구현: 학생회장 / 소모임장의 회원 관리 페이지를 위한 API

feat: user findById for searching another user case

---

src/main/java/net/causw/adapter/persistence/LockerLocation.java
src/main/java/net/causw/adapter/persistence/port/DomainModelMapper.java
src/main/java/net/causw/adapter/persistence/port/LockerLocationPortImpl.java
src/main/java/net/causw/application/LockerService.java
src/main/java/net/causw/application/dto/LockerLocationCreateRequestDto.java
src/main/java/net/causw/application/dto/LockerLocationResponseDto.java
src/main/java/net/causw/application/dto/LockerLocationUpdateRequestDto.java
src/main/java/net/causw/application/dto/LockerLogDetailDto.java
src/main/java/net/causw/application/dto/LockerMoveRequestDto.java
src/main/java/net/causw/application/dto/LockerUpdateRequestDto.java
src/main/java/net/causw/domain/model/LockerLocationDomainModel.java

Locker entity의 불필요한 부분 제거
- `LockerLocation` 내부 `description` 제거
- `LockerLog` 내부 `message` 필드 프론트 요청 Dto 에서 제거

fix: refactor Locker Structure to remove unnecessary field

---

src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/domain/validation/GrantableRoleValidator.java

동문회장 지정 시 기존 동문회장의 권한이 변경되지 않던 현상 수정
기존 소모임장, 동문회장에 대한 권한 변경이 가능하던 현상 제거
=> 다른 소모임장, 동문회장을 지정하는 경우 자동으로 `COMMON` 으로 변경되므로, 직접 지정하는 case는 없음
- 
-

fix: bug at granting leader alumni

---

src/main/java/net/causw/application/UserService.java
src/test/groovy/net/causw/application/UserServiceTest.groovy

유저 재가입 시 기존 존재 여부를 검사하지 않고 favorite board가 계속하여 생성되는 현상 제거
- 
-

fix: exception in creating favorite board

---

src/main/java/net/causw/domain/exceptions/ErrorCode.java
src/main/java/net/causw/domain/validation/UserStateValidator.java

`Reject` 유저의 로그인 시 exception handling이 안되던 현상 수정
- 
-

fix: add exception handling for reject user sign-in

---

src/main/java/net/causw/adapter/persistence/BoardRepository.java
src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
src/main/java/net/causw/adapter/web/CommonController.java
src/main/java/net/causw/adapter/web/PostController.java
src/main/java/net/causw/application/HomePageService.java
src/main/java/net/causw/application/PostService.java
src/main/java/net/causw/application/UserService.java
src/main/java/net/causw/application/dto/post/BoardPostsResponseDto.java
src/main/java/net/causw/application/spi/BoardPort.java
src/test/groovy/net/causw/application/PostServiceTest.groovy

- #361
즐겨찾는 게시판 조회 / 초기화 로직 변경
- 기본 등록 로직의 변경 (가장 오래된 3개 -> `앱 공지사항`, `학생회 공지게시판`, `전체 자유게시판`)
- 기본 등록 시점의 변경 (유저 승인 시점 -> Home 화면 호출 시 즐겨찾는 게시판 존재여부 확인)
- 게시판 상세 (게시글 리스트 조회) API의 ResponseDto에 즐겨찾기 여부 포함

fix: favorite board initialize

---

src/main/java/net/causw/adapter/persistence/Locker.java
src/main/java/net/causw/application/LockerService.java
src/main/java/net/causw/application/dto/locker/LockerResponseDto.java
src/test/groovy/net/causw/application/LockerServiceTest.groovy

`LockerNumber` 필드의 Unique 옵션 제거에 따라, 본인의 사물함 표기 변경
- 
-

fix: modify locker response for duplicate locker number

---

src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
src/main/java/net/causw/adapter/web/BoardController.java
src/main/java/net/causw/application/BoardService.java
src/main/java/net/causw/application/spi/BoardPort.java

resolves #213
Add restoring board API
- BoardController, BoardService, BoardPort, BoardPortImpl 에 restore 관련 메서드를 추가해 restore board API를 구현
- 삭제되지 않은 게시판에 대한 restore 접근 제어를 위해 TargetIsNotDeletedValidator 추가
- 삭제된 게시판에 대해 restore하면 Board table의 is_deleted를 false로 변경
- Board delete와 restore에 대해 ADMIN 권한 검증 추가

feat: restore board

---

src/main/java/net/causw/adapter/persistence/Inquiry.java
src/main/java/net/causw/adapter/persistence/port/DomainModelMapper.java
src/main/java/net/causw/adapter/persistence/port/InquiryPortImpl.java
src/main/java/net/causw/adapter/persistence/port/InquiryRepository.java
src/main/java/net/causw/adapter/web/InquiryController.java
src/main/java/net/causw/application/InquiryService.java
src/main/java/net/causw/application/dto/inquiry/InquiryCreateRequestDto.java
src/main/java/net/causw/application/dto/inquiry/InquiryResponseDto.java
src/main/java/net/causw/application/spi/InquiryPort.java
src/main/java/net/causw/domain/model/InquiryDomainModel.java
src/main/java/net/causw/domain/model/StaticValue.java

resolves #394 
"문의하기 " 기능 기획시 1. 이메일을 통한 문의내용 발송 2. 채팅으로 문의 3. 게시판 형식으로 문의 세 가지 방식으로 기획 구성을 했습니다. 1,2 번의 방식은 별도의 이메일 로그인 구현, 웹소켓 적용 등 부가적인 의견을 여쭤봐야 할 것 같아 3번 컨셉으로 우선적으로 구현해보았습니다. 다른 분들의 "문의하기" 기획안을 듣고 3번 이외 다른 방식이 적절하다면 이에 맞춰 다시 진행하도록 하겠습니다. 이와 같은 방식이 적절하다면 구체적인 메서드, validation을 해당 풀리퀘릍 통해 추가할 예정입니다.
- "문의하기" 구현을 위해 "TB_INQUIRY"를 추가하였습니다
- Inquiry를 조회하기 위해 Id를 통해 조회하는 findById메서드를 구현하였습니다.
- Inquriy를 생성하기 위해 create 메서드를 구현하였습니다.
- Inquiry처리를 위해 부가적으로  InquiryController, InquriyService, InquriyRepository 등을 생성하였습니다.
Post를 레퍼런스로 작성하였으며 Post를 떠올리시면 이해하시기 쉬울 것 같습니다.
- Inquriy, InquiryController, InquriySerivce, InquriyPort, InquiryPortImpl, InquiryRepository, InquiryCreateRequestDto, InquriyResponseDto, InquiryDomainModel을 생성했습니다.
- InquriyDomainModel을 처리하기 위해 DomainModelMapper에 관련 메서드를 …

feat: Implement Inquiry

---

src/main/java/net/causw/config/swagger/SwaggerConfig.java

로그인 후 Access Token 관련 스웨거 내에서 인증 기능 부재로 Authorize 기능을 구현했습니다.
개발기간: 약 40분

feat : 스웨거 authorize 기능 구현

---

build.gradle

프론트 <-> 백엔드 / 백엔드 <-> 백엔드 소통을 위해 에러 로그를 공유할 수 있도록 디스코드에 연결했습니다.
스프링부트 단에서 Error 레벨의 로그가 발생하면 디스코드로 전송할 수 있도록 구현했습니다.
정보 채널 -> back-end-error 채널에 전송할 수 있도록 연결했습니다
gitignore 파일이 대부분이라 노션에 있는 파일 꼭 적용 부탁드립니다.
개발기간: 60m

[FEAT]: 백엔드 에러로그 Discord로 LogBack 설정 구현

---

.gitignore
src/main/resources/logback.xml

로컬에서는 webhook이 정상 동작하지만 개발계 서버에서는 webhook이 정상 동작하지 않는 이슈 해결
기존 logback.xml이 gitignore 처리 되어있었지만 이를 public으로 바꾸고 안의 민감정보(webhook-uri)를 gitignore 처리해준 뒤에 속성화 사용

fix: discord webhook 관련 gitignore 속성 수정

---

src/main/java/net/causw/adapter/web/CircleController.java
src/main/java/net/causw/config/swagger/SwaggerConfig.java

Issue #432 
기존 Swagger UI에서 user token을 request body로 받으려 해 모든 API 요청 시 request body에 중괄호가 2쌍 생성되어 json parsing error가 발생했었습니다.
SecurityContextHolder.getContext().getAuthentication().getPricipal()을 통해 Swagger UI에서 user token을 통해 상단 Authorize 버튼으로 인증을 하면 자동으로 request header에 user token을 넣어주는 방식으로 변경했습니다.
변경 후 Swagger UI
개발기간: 약 10시간

refactor : swagger 상에서 user token header로 받기(circle만)

---

src/main/java/net/causw/adapter/persistence/port/post/PostPortImpl.java
src/main/java/net/causw/adapter/persistence/post/Post.java
src/main/java/net/causw/adapter/persistence/repository/PostRepository.java
src/main/java/net/causw/adapter/persistence/user/User.java
src/main/java/net/causw/adapter/web/PostController.java
src/main/java/net/causw/application/comment/ChildCommentService.java
src/main/java/net/causw/application/comment/CommentService.java
src/main/java/net/causw/application/dto/post/BoardPostsResponseDto.java
src/main/java/net/causw/application/dto/post/PostCreateRequestDto.java
src/main/java/net/causw/application/dto/post/PostResponseDto.java
src/main/java/net/causw/application/dto/post/PostUpdateRequestDto.java
src/main/java/net/causw/application/dto/post/PostsResponseDto.java
src/main/java/net/causw/application/post/PostService.java
src/main/java/net/causw/application/spi/PostPort.java
src/main/java/net/causw/application/user/UserService.java

findAllAppNotice API는 프론트 단에서 구현되어 있지 않아서 당장은 사용하지 않습니다.
기존 코드가 역할만 동아리장인 것을 확인하기 때문에 타 동아리의 동아리장이면서 해당 동아리의 동아리 부원일 경우가 존재하기 때문에 권한에 대해서 수정하였습니다.
native 쿼리가 테이블을 인지하지 못하여 테이블 명을 데이터베이스와 동일하게 소문자로 변경해주었습니다.
swagger의 validator 응답값은 추후 추가할 예정입니다.
개발기간: 1주

feat : 게시글 API 검증 및 수정 / swagger 보강

---

src/main/java/net/causw/application/dto/post/PostsResponseDto.java

#439 
게시글 전체 조회 api에서 권한에 따라 삭제된 게시글도 확인할 수 있으므로 isDeleted 값을 함께 반환해서 프론트단에서 별도 정렬 가능하게 하기 위해 필요하여 추가하였습니다.
개발기간: 20분

hotfix : 게시글 전체 조회 api에서 게시글 삭제여부 추가

---

src/main/java/net/causw/adapter/persistence/port/post/PostPortImpl.java
src/main/java/net/causw/adapter/persistence/repository/PostRepository.java
src/main/java/net/causw/adapter/web/PostController.java
src/main/java/net/causw/application/circle/CircleService.java
src/main/java/net/causw/application/dto/post/PostResponseDto.java
src/main/java/net/causw/application/homepage/HomePageService.java
src/main/java/net/causw/application/post/PostService.java
src/main/java/net/causw/application/spi/PostPort.java
src/main/java/net/causw/application/user/UserService.java

#439 
post 관련 메서드명을 모두 아래와 같이 변경하여 게시글 관련 메서드임을 명시하였습니다.
(ex. findAll -> findAllPost)
게시글 검색 옵션이 기존 writer와 title에서 title검색으로만 변경하여서 옵션 선택 관련 부분을 삭제하였습니다.
postresponsedto에서 게시글이 속한 게시판의 전체 정보가 필요하지 않아서 프론트 측의 요청에 따라 boardname만을 전달해주도록 수정하였습니다.
타 동아리의 동아리장이지만 해당 동아리의 동아리 부원일 경우를 고려하여 권한을 수정하였습니다.
개발기간: 6시간

update : 게시글 API 요청사항 수정 및 개선

---

src/main/java/net/causw/adapter/persistence/port/user/UserPortImpl.java
src/main/java/net/causw/application/board/BoardService.java
src/main/java/net/causw/application/circle/CircleService.java
src/main/java/net/causw/application/comment/ChildCommentService.java
src/main/java/net/causw/application/comment/CommentService.java
src/main/java/net/causw/application/delegation/DelegationPresident.java
src/main/java/net/causw/application/post/PostService.java
src/main/java/net/causw/application/spi/UserPort.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/domain/validation/ContentsAdminValidator.java
src/main/java/net/causw/domain/validation/UserRoleValidator.java

#449 
enum 값들의 개수가 증가하면서 단순히 Role.LEADER_CIRCLE인지 확인하던 코드부분을 모두 LEADER_CIRCLE이라는 value를 포함하는지 확인하는 코드로 변경하였습니다. 
학생회장의 권한을 ADMIN과 동일하게 설정하는 바에 따라서 validator내부의 설정을 변경하여 학생회장의 권한을 수정하였습니다.
findByRole로 역할에 따라 유저를 검색하는 메서드의 인자를 기존 Role에서 String 타입으로 넘겨서 해당 문자열을 포함한 모든 역할을 검색할 수 있도록 변경하였습니다.
개발기간: 2일

refac : 동아리장 Enum 개수 증가로 인한 모든 service 단의 권한확인 방법 수정

---

src/main/java/net/causw/adapter/persistence/port/user/UserPortImpl.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/board/BoardService.java
src/main/java/net/causw/application/delegation/DelegationLeaderCircle.java
src/main/java/net/causw/application/delegation/DelegationPresident.java
src/main/java/net/causw/application/dto/user/UserResponseDto.java
src/main/java/net/causw/application/post/PostService.java
src/main/java/net/causw/application/spi/UserPort.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/domain/validation/GrantableRoleValidator.java

#450 
동아리장과 학생회장을 겸직할시에는 관리자 권한을 가진 학생회장의 권한으로 역할을 수행할 수 있도록 조건을 추가하였습니다.
권한을 위임해줄 시에 위임자의 권한 겸직과 피위임자의 권한 겸직을 모두 고려하여 기존 updateRole 로만 수행하던 것을 removeRole을 추가로 생성하여 위임자의 권한 변경을 별도로 처리하였습니다.
또한 동아리장을 역임하는 경우도 고려하여서 해당 id로 검색되는 동아리가 한개일 경우에만 removeRole을 통해 동아리장 권한을 박탈하도록 하였습니다.(2개 이상일 시에는 해당 동아리의 동아리장 정보는 바뀌나 위임자는 타 동아리의 동아리장이므로 enum 값 leader_circle 유지)
현재 접속한 사용자 본인의 정보 조회 메서드 명이 findbyuserid로 다른 유저 정보를 조회하는 메서드와 혼동이 생길것 같아 findcurrentuser로 변경하였습니다.
개발기간: 4일

refac : 권한 중첩 시 검증 로직 수정 및 추가

---

src/main/java/net/causw/adapter/persistence/port/mapper/DomainModelMapper.java
src/main/java/net/causw/adapter/persistence/port/user/UserPortImpl.java
src/main/java/net/causw/adapter/persistence/repository/UserRepository.java
src/main/java/net/causw/adapter/persistence/user/User.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/dto/user/UserSignInResponseDto.java
src/main/java/net/causw/application/dto/user/UserUpdateTokenRequestDto.java
src/main/java/net/causw/application/spi/UserPort.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/config/security/JwtAuthenticationFilter.java
src/main/java/net/causw/config/security/JwtTokenProvider.java
src/main/java/net/causw/config/security/WebSecurityConfig.java
src/main/java/net/causw/domain/model/user/UserDomainModel.java
src/main/java/net/causw/domain/model/util/StaticValue.java

feat: 토큰 로직 구현

---

src/main/java/net/causw/adapter/web/CommonController.java
src/main/java/net/causw/application/homepage/HomePageService.java

#448 
common API 검증 완료하였습니다.
홈페이지에서 조회되는 게시판의 조건을 즐겨찾기한 게시판 -> 동아리에 속하지 않은 게시판으로 변경하였습니다.
운영상으로 동아리에 속하지 않는 게시판은 학생회 게시판이기 때문에 조건을 변경하였고, 추후 학년별 게시판 생성을 염두에 두었습니다.
현재는 동아리에 속하지않는 게시판 더미데이터가 많아서 홈페이지에 다양한 게시판이 출력되지만 실제로는 그렇게 되지 않습니다.
게시판과 함께 조회되는 게시글은 최근 게시글 3개입니다.
개발기간: 2시간

feat : 홈페이지 화면에서 조회되는 게시판 및 게시글 조건 변경 및 common API 검증 완료

---

src/main/java/net/causw/adapter/persistence/port/user/UserPortImpl.java
src/main/java/net/causw/adapter/persistence/repository/UserRepository.java
src/main/java/net/causw/application/dto/user/UserPrivilegedResponseDto.java
src/main/java/net/causw/application/user/UserService.java

권한 관리 관련 오류 사항입니다.
leader_circle 역할을 가진 사용자의 동아리를 찾을 때로 변경하였고, 특별한 권한을 가진 사용자 확인 시 활성화 사용자만 가능하게 변경하였습니다.
특별한 권한을 가진 사용자 중 학생회장도 확인할 수 있도록 변경하였습니다. 
개발기간:

hotfix : 권한 관리 시 학생회장 권한인 사용자 확인 가능하게 dto 변경 / 특별한 권한을 가진 사용자 확인 시 활성화 사용자만 가능하게 변경

---

src/main/java/net/causw/adapter/persistence/user/UserAdmission.java
src/main/java/net/causw/adapter/persistence/user/UserAdmissionLog.java
src/main/java/net/causw/application/user/UserService.java

유저를 상태로 분류하여 검색하는 과정에서 sql오류가 발생하여 테이블 명을 소문자로 변경하여서 해결하였습니다. 
비활성 사용자의 경우 동아리를 확인하지 않도록 변경하였습니다.
개발기간:

hotfix : 유저 상태별로 검색하는 과정에서 비활성 사용자의 경우 동아리를 체크하지 않도록 하였고, 테이블명을 변경하였습니다.

---

src/main/java/net/causw/application/circle/CircleService.java
src/main/java/net/causw/application/post/PostService.java
src/main/java/net/causw/domain/validation/UserRoleValidator.java

동아리장이 게시글을 조회할 때 해당 게시글의 게시판이 동아리에 속하지 않을 경우 필터링하는 과정에서 null 값에 대한 예외처리를 해주지 않아서 수정하였습니다.
_N_ 조건을 고려하여 rolevalidator를 수정하였습니다.
동아리 게시판이 자동 생성될 때 게시판명에 해당 동아리의 이름이 포함되도록 수정하였습니다.
개발기간:

hotfix : 게시글 조회 시 동아리에 속하지 않는 경우에 대한 예외처리, _N_조건을 위한 rolevalidator 변경, 동아리 게시판 이름 및 카테고리 규칙 수정

---

src/main/java/net/causw/adapter/persistence/port/board/BoardPortImpl.java
src/main/java/net/causw/adapter/persistence/repository/BoardRepository.java
src/main/java/net/causw/application/board/BoardService.java
src/main/java/net/causw/application/homepage/HomePageService.java
src/main/java/net/causw/application/post/PostService.java
src/main/java/net/causw/application/spi/BoardPort.java

#487 
#487 과 동일하게 isCircleLeader의 로직에 동아리가 존재하지 않을 경우의 예외처리를 추가하였습니다.
findAllBoard의 로직을 수정하여서 동아리장과 일반 유저의 경우 본인이 속한 동아리의 게시판과 일반게시판을 확인할 수 있게 변경하였습니다. 삭제된 게시판의 경우 추후 별도의 관리 페이지가 만들어졌을때 별도로 동아리장이 본인의 동아리의 것들만 관리할 수 있게 생성할 예정입니다.
개발기간:

hotfix : findAllBoard 로직을 수정하여서 동아리장과 일반 유저의 경우 본인이 속한 동아리의 게시판과 일반 게시판을 확인하게 수정하였습니다.

---

src/main/java/net/causw/application/circle/CircleService.java

#503 
동아리 정보 업데이트 시 사진이 있을 경우 제대로 불러 와지지 않아 수정 페이지가 제대로 안 뜨는 문제 수정
동아리 업데이트 DTO에서 사진이 빈 칸이거나 null일 시 기존 사진 url 데이터를 그대로 유지 시키는 방식으로 수정
개발기간: 1시간

hotfix : circle update 메서드 수정

---

build.gradle
src/main/java/net/causw/adapter/persistence/port/user/UserPortImpl.java
src/main/java/net/causw/adapter/persistence/repository/UserRepository.java
src/main/java/net/causw/application/locker/LockerActionRegister.java
src/main/java/net/causw/application/spi/UserPort.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/config/redis/RedisConfig.java
src/main/java/net/causw/domain/model/util/RedisUtils.java
src/main/java/net/causw/domain/validation/LockerTimePassedValidator.java

#502 
refreshToken을 DB에 저장하는 방식에서 Redis를 도입하여 Redis에 저장하는 방식으로 바꿨습니다.
아직 User Entity에 있는 RefreshToken 변수와 DB의 RefreshToken column은 지우지 않았습니다. 
서비스가 안정되면 그 때 지우도록 하겠습니다.
application.yml 노션에 업데이트 하겠습니다. (redis 관련 변수)
개발기간: 6시간

fix : refreshToken 로직 개선

---

src/main/java/net/causw/application/circle/CircleService.java

#512 
동아리장 권한을 가진 사람이 해당 동아리 회장이 아님에도 동아리원을 확인할 수 있던 버그 수정
validator를 한 층 추가했습니다. 근데 코드 가동성상으로 이게 괜찮을지 논의해주세요!
개발기간: 10분

fix : 해당 동아리 회장이 아님에도 동아리원을 확인할 수 있던 버그 수정

---

src/main/java/net/causw/application/circle/CircleService.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/domain/validation/UserStateIsDropOrIsInActiveValidator.java

유저 관리 시 추방과 탈퇴 유저를 모두 복구 가능하도록 validator를 생성하였습니다.
동아리 공지게시판이 생성될 때 별도로 카테고리를 분리하기 위해서 '동아리 공지 게시판'으로 변경하였습니다.
개발기간:

hotfix : 유저 관리에서 탈퇴 유저와 추방유저를 모두 복구 가능하도록 변경

---

src/main/java/net/causw/adapter/persistence/port/user/UserPortImpl.java
src/main/java/net/causw/adapter/persistence/repository/UserRepository.java

#529 
여러개의 상태를 한번에 반환하게 쿼리를 짜는 과정에서 name이 들어가지 않을 경우 오류가 발생했습니다.
기존 jpa 자동생성 쿼리로 수정하려고 하였으나 findbystateandname의 native 쿼리를 수정하여서 적용하여 에러를 수정하였습니다.
개발기간: 20분

hotfix : 추방 및 탈퇴 유저를 관리할 때 이름이 들어가지 않을 경우 오류가 발생하는 현상을 수정하였습니다.

---

src/main/java/net/causw/adapter/persistence/port/comment/ChildCommentPortImpl.java
src/main/java/net/causw/adapter/persistence/port/comment/CommentPortImpl.java
src/main/java/net/causw/adapter/persistence/port/post/PostPortImpl.java
src/main/java/net/causw/adapter/persistence/repository/ChildCommentRepository.java
src/main/java/net/causw/adapter/persistence/repository/CommentRepository.java
src/main/java/net/causw/adapter/persistence/repository/PostRepository.java
src/main/java/net/causw/adapter/web/ChildCommentController.java
src/main/java/net/causw/application/circle/CircleService.java
src/main/java/net/causw/application/comment/ChildCommentService.java
src/main/java/net/causw/application/comment/CommentService.java
src/main/java/net/causw/application/dto/comment/ChildCommentResponseDto.java
src/main/java/net/causw/application/dto/comment/CommentResponseDto.java
src/main/java/net/causw/application/homepage/HomePageService.java
src/main/java/net/causw/application/post/PostService.java
src/main/java/net/causw/application/spi/ChildCommentPort.java
src/main/java/net/causw/application/spi/CommentPort.java
src/main/java/net/causw/application/spi/PostPort.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/domain/model/comment/CommentDomainModel.java

#539 
댓글과 대댓글의 기능을 개선하려고 합니다.
특정 게시물의 모든 댓글 수를 가져오는 쿼리를 작성하였습니다. 수정해야 할 부분이 있다면 알려주세요.
- 댓글이 삭제되어도 댓글에 달려 있던 대댓글은 유지
- 게시물/댓글/대댓글 join하여 한방 쿼리로 count
- 댓글 조회에 대댓글 조회를 포함시켰기 때문에 대댓글 조회 기능을 삭제하였습니다.
개발기간: 1주

fix : 댓글 및 대댓글 기능 개선

---

src/main/java/net/causw/application/board/BoardService.java
src/main/java/net/causw/application/circle/CircleService.java
src/main/java/net/causw/application/comment/ChildCommentService.java
src/main/java/net/causw/application/comment/CommentService.java
src/main/java/net/causw/application/common/CommonService.java
src/main/java/net/causw/application/delegation/DelegationLeaderAlumni.java
src/main/java/net/causw/application/delegation/DelegationLeaderCircle.java
src/main/java/net/causw/application/delegation/DelegationPresident.java
src/main/java/net/causw/application/homepage/HomePageService.java
src/main/java/net/causw/application/inquiry/InquiryService.java
src/main/java/net/causw/application/locker/LockerActionExtend.java
src/main/java/net/causw/application/locker/LockerActionFactory.java
src/main/java/net/causw/application/locker/LockerActionRegister.java
src/main/java/net/causw/application/locker/LockerActionReturn.java
src/main/java/net/causw/application/locker/LockerService.java
src/main/java/net/causw/application/post/PostService.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/domain/model/util/MessageUtil.java

#538
중복되는 하드코딩 문자열을 MessageUtil을 통해 중앙 통제하고자 합니다.
"id checked, but exception occured" 예외처리 문자열 앞에 해당 domain명이 붙는 게 필수적인지 의문이 있습니다!
일단은 MessageUtil에서 매개변수로 받아 해당 문자열을 반환하는 것으로 처리했습니다.
중복 제거가 목적이기에, 하드코딩된 문자열이 1개거나 하나의 파일에만 존재해 확장성이 없는 경우는 제외했습니다.
하드코딩된 또다른 문자열인 "LEADER_CIRCLE"의 경우 Role 구조 개편을 앞두고 있기에 보류했습니다.
주요 Service의 하드코딩된 한글 에러메시지에 "삭제할, 수정할" + "OO가 없습니다" 등의 추가 접두사가 붙어 상수 문자열을 활용할 수가 없는데,해당 메시지에서 데이터의 용도보다는 존재 여부가 더 가치있는 정보이기에 접두사가 존재하는 문장들을 모두 수정하고 단일화된 상수 문자열로 대체할 것을 건의합니다. 하드코딩된 문자열은 최대한 지양하는 것이 바람직하다고 생각합니다.
개발기간: 1주

Refactor: 하드코딩된 문자열 제거

---

build.gradle
src/main/java/net/causw/adapter/persistence/comment/ChildComment.java
src/main/java/net/causw/adapter/persistence/comment/Comment.java
src/main/java/net/causw/adapter/persistence/port/mapper/DomainModelMapper.java
src/main/java/net/causw/adapter/persistence/port/post/PostPortImpl.java
src/main/java/net/causw/adapter/persistence/post/Post.java
src/main/java/net/causw/application/comment/ChildCommentService.java
src/main/java/net/causw/application/comment/CommentService.java
src/main/java/net/causw/application/dto/board/BoardResponseDto.java
src/main/java/net/causw/application/dto/comment/ChildCommentResponseDto.java
src/main/java/net/causw/application/dto/comment/CommentResponseDto.java
src/main/java/net/causw/application/dto/post/BoardPostsResponseDto.java
src/main/java/net/causw/application/dto/post/PostResponseDto.java
src/main/java/net/causw/application/dto/post/PostsResponseDto.java
src/main/java/net/causw/application/dto/util/DtoMapper.java
src/main/java/net/causw/application/dto/util/StatusUtil.java
src/main/java/net/causw/application/homepage/HomePageService.java
src/main/java/net/causw/application/post/PostService.java

#545 
직전 PR에 대한 충돌 이슈 해결 후 다시 올리는 PR입니다.
* Service는 Port, DomainModel에 의존하지 않고 Repository와 직결되어야 합니다.
* Service 메서드는 아래와 같은 구조를 가지게 됩니다.
* 1. 필요한 Entity를 조회
* 2. 조회한 Entity에 대한 Validation
* 3. 추가 비즈니스 로직(수정, 삭제 등)
* 4. Dto로 반환
* MapStruct 라이브러리를 통해 Dto의 생성 과정을 from/of 없이 컴파일 타임에 자동화합니다. 
* 실제 Dto를 생성하는 코드는 build/classes/java/main/net/causw/application/dto/util에서 확인하실 수 있습니다.
특이사항으로는, DtoMapper를 수정한 직후 첫 컴파일된 Impl의 경우엔 getter로 필드에 접근하고, 그 이후부턴 빌더패턴으로 접근하고 있는 것으로 확인했습니다.
[코딩 컨벤션과 함께 예시 코드를 참고해주세요.](https://www.notion.so/dustbox-j/2024-78104a49bb394387ae19c191cac7455c?pvs=4)
* Dto에 수정/삭제 가능 여부를 판정하던 비즈니스 로직을 StatusUtil에서 관리하도록 수정했습니다. (일반적으로 비즈니스 로직은 Dto 내부에 배치하지 않아야 합니다.)
* Dto에 존재하는 from, of 메서드는 더 이상 사용되지 않고, 모든 Dto 생성은 DtoMapper가 통제하게 됩니다. (다만 리팩토링 완료 전까지는 아직 PortImpl 등과의 의존성이 남아있는 것을 …

refactor: Post & Comment & ChildComment Port 제거 (#545)

---

src/main/java/net/causw/adapter/persistence/board/Board.java
src/main/java/net/causw/adapter/persistence/board/FavoriteBoard.java
src/main/java/net/causw/application/board/BoardService.java
src/main/java/net/causw/application/circle/CircleService.java
src/main/java/net/causw/application/comment/ChildCommentService.java
src/main/java/net/causw/application/comment/CommentService.java
src/main/java/net/causw/application/dto/board/BoardOfCircleResponseDto.java
src/main/java/net/causw/application/dto/board/BoardResponseDto.java
src/main/java/net/causw/application/dto/util/DtoMapper.java
src/main/java/net/causw/application/homepage/HomePageService.java
src/main/java/net/causw/application/user/UserService.java

#545 
- UserService, CircleService 그리고 HomaPageService에서 BoardPort 제거 및 Board 관련 Dto에서의 of/from 메서드를 DtoMapper를 적용하여 Dto 생성을 자동화하였습니다.
- BoardOfCircleResponseDto의 경우, board와 post의 두 entity를 입력으로 받는 toBoardOfCircleResponseDto에서 하나의 entity에 대해 매핑할 때와 다르게 모든 타겟에 매핑하지 않은 경우 모호성(ex. BoardOfCircleResponseDto의 id에 2개의 entity 중에서 어떤 entity의 id가 매핑될 것인지)이 발생하여 사진과 같이 모두 매핑해 주었습니다.
실행을 통해 모든 타켓에 매핑되는 것을 확인하였습니다.
수정해야 할 사항이 있다면 알려주세요.
개발기간: 2주

refactor : BoardService port 제거 및 구조 재정비

---

src/main/java/net/causw/adapter/web/BoardController.java
src/main/java/net/causw/adapter/web/ChildCommentController.java
src/main/java/net/causw/adapter/web/CircleController.java
src/main/java/net/causw/adapter/web/CommentController.java
src/main/java/net/causw/adapter/web/CommonController.java
src/main/java/net/causw/adapter/web/LockerController.java
src/main/java/net/causw/adapter/web/PostController.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/config/security/SecurityService.java

#567 
#540 
controller 별로 preauthorize를 적용해서 토큰을 통해 api 의 사용 접근을 제한하였습니다.
현재는 NONE역할을 제외하고는 모두 접근이 가능한 api 가 다수 존재합니다. 이 경우 내부에 조건문 로직으로 관리자일 경우와 아닐 경우에 기능이 달라지게 되는데 논의를 통해 별도 api를 생성할 지 현상 유지를 할지 정해야 할 것 같습니다.
securityservice를 별도 생성하여서 기본적으로 ACTIVE 상태와 NONE이 무조건 아니어야 하는 경우를 캡슐화하였습니다. 그 외에는 역할 별로 달라지는 경우이기 때문에 hasAnyRole을 사용하였습니다. 
현재 삭제되지 않은 불필요 validator는 동현님 작업 이후에 상의 후 삭제할 예정입니다
개발기간:

refactor : controller에 preauthorize 적용으로 api 별 접근 가능 권한 설정

---

src/main/java/net/causw/application/locker/LockerActionExtend.java
src/main/java/net/causw/application/locker/LockerActionRegister.java
src/main/java/net/causw/domain/model/util/MessageUtil.java
src/main/java/net/causw/domain/model/util/StaticValue.java
src/main/java/net/causw/domain/validation/ExtendLockerExpiredAtValidator.java
src/main/java/net/causw/domain/validation/LockerExpiredAtValidator.java
src/main/java/net/causw/domain/validation/LockerExtendAccessValidator.java
src/main/java/net/causw/domain/validation/LockerInUseValidator.java

#583 
사물함의 연장날짜가 expiredat과 동일하면 이미 연장했다고 다루도록 로직 변경
flag에 LOCKER_EXTEND 추가(연장 날짜에 맞는지 확인하기 위함)
없습니다.

feat : locker 연장 구현

---

src/main/java/net/causw/CauswApplication.java
src/main/java/net/causw/adapter/persistence/repository/UserRepository.java
src/main/java/net/causw/adapter/persistence/user/User.java
src/main/java/net/causw/application/comment/ChildCommentService.java
src/main/java/net/causw/application/comment/CommentService.java
src/main/java/net/causw/application/post/PostService.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/domain/exceptions/ErrorCode.java
src/main/java/net/causw/domain/model/enums/UserState.java
src/main/java/net/causw/domain/validation/UserStateIsDeletedValidator.java
src/main/java/net/causw/domain/validation/UserStateIsDropOrIsInActiveValidator.java
src/main/java/net/causw/domain/validation/UserStateValidator.java

#591 
Scheduler로 자정마다 state가 INACTIVE인 사용자들 중에 updated_at이 현재 시점으로부터 5년 이상 차이나면 개인정보를 삭제하도록 하였으며 state를 DELETED로 업데이트 되도록 하였습니다.
추가적으로, DELETED 상태인 사용자가 작성하였던 게시물이나 댓글, 대댓글에는 더 이상 좋아요를 추가할 수 없도록 하였고 댓글에는 새로운 대댓글을 추가하지 못하도록 Validator를 추가하였습니다.
UserState DELETED가 추가된 것을 프론트 측에는 아직 적용되지 않았기 때문에 임시적으로 테스트하였던 DELETED로 변경된 컬럼을 INACTIVE로 변경해 두었습니다.
개발기간: 2일

feature : 탈퇴 회원 계정 삭제

---

src/main/java/net/causw/adapter/persistence/port/user/UserPortImpl.java
src/main/java/net/causw/adapter/persistence/repository/UserRepository.java
src/main/java/net/causw/application/dto/user/UserFindPasswordRequestDto.java
src/main/java/net/causw/application/spi/UserPort.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/config/mail/MailConfig.java
src/main/java/net/causw/infrastructure/GoogleMailSender.java

🚩 관련사항
#601
📢 전달사항
임시 비밀번호 발급 기능을 리팩토링했습니다.
1. 피그마에 따라 기존 코드에 더해 전화번호를 받을 수 있도록 수정했습니다.
2. GoogleMailSender  클래스 속성 내부 JavaMailSender를 Bean으로 인식하지 못하는 이슈가 발견되어 별도의 MailConfig 클래스를 정의하고 JavaMailSender를 수동으로 Bean으로 등록해 줬습니다. 이때 필요한 민감한 정보는 @Value를 통해 application.yml에서 주입 받았습니다. (참고: https://developer-nyong.tistory.com/56)
3. 이메일 HTML 디자인을 수정했습니다.
4. 현재 MailConfig의 Debug가 true로 설정되어 있는데 아래 이슈 해결 후 최종 프로덕션에서는 false로 설정되는게 좋을 것 같습니다.
-> 이전과 달리 Gmail 내부 처리에 의해 중요 메일로 마킹됩니다. (노란색 북마크 표시)
API 테스트는 Gmail, 네이버메일, outlook 세 가지 계정에서 진행했습니다. (네이버 메일 사진과 outlook 추가 첨부)
Gmail과 네이버메일에서는 전혀 문제가 없으나 Outlook에서는 스팸 필터 처리가 되는 이슈가 존재합니다.
트러블 슈팅으로 시도한 방법은 다음과 같습니다.
- JavaMailSender의 property 수정(SSL enable, 587 port 대신 SSL 전송에 사용되는 465 port로 변경, 신뢰할 서버 smtp.gmail.com으로 설정 등등 (모든 설정 다 통하지 않았음)
- HTML, CSS 수정 및 …

refactor: 임시 비밀번호 발급 및 메일 전송

---

.github/workflows/dev.yml
.github/workflows/main.yml

- #616
> Github workflow 내부 자바 버전이 현 Springboot 3에 적합하지 않아 17로 조정하였습니다.
> (실제 파이프라인에서 발생하던 로그 확인 결과 로컬에서 Java 11로 현 프로젝트를 실행할 때 발생하던 에러와 동일했습니다.)
> 현재 workflow 내부에서 AccessKey에 직접 접근하고 있는데, 이를 AWS IAM의 Role 기반으로 개편할 수 있다면 좋을 듯 합니다.
> 자세한 것은 아래 링크를 참고해주세요.
https://minemanemo.tistory.com/139
개발기간: 1일

Devops: workflow 빌드 에러 해결

---

src/main/java/net/causw/adapter/persistence/repository/ChildCommentRepository.java
src/main/java/net/causw/adapter/persistence/repository/CommentRepository.java
src/main/java/net/causw/adapter/persistence/repository/FavoritePostRepository.java
src/main/java/net/causw/adapter/persistence/repository/PostRepository.java
src/main/java/net/causw/adapter/web/ChildCommentController.java
src/main/java/net/causw/adapter/web/CommentController.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/dto/post/PostsResponseDto.java
src/main/java/net/causw/application/dto/user/UserPostsResponseDto.java
src/main/java/net/causw/application/dto/util/DtoMapper.java
src/main/java/net/causw/application/user/UserService.java

https://github.com/CAUCSE/CAUSW_backend/issues/596
- 노션의 기록 page를 위한 3가지 API를 작성하였습니다. ( 유저가 작성한 게시글 기록은 리팩토링, 나머지 2개는 새롭게 작성)
- 기존의 유저가 작성한 게시글 기록은 API 가 /posts 였었는데, 새로운 기록 API를 추가하면서 동일한 기능의 API를 의미를 명확히 하기 위해 /posts/written으로 변경하였습니다. 기존과의 호환성 때문에 기존의 API를 Controller단에 남겨 두기는 하였지만, 추후에 이 API를 삭제해도 될것 같습니다. 해당 부분은 주석으로 FIXME 처리 해 놓았습니다. 
- 가장 최근의 Develop랑 충돌 해결 완료 했고, Mapper의 필드명을 분명하게 수정완료했습니다.
- 오류가 나는 nativeQuery를 동일한 기능의 JPQL 쿼리로 변경하였습니다.
-  PostsResponseDto에 content 속성을 새롭게 추가하였습니다. Post 관련 ResponseDTO에  투표가 있는지, 설문지가 있는지 여부를 나타내는 Bool Type 변수를 추후 추가하여야 합니다.
- 기록 API의 경우 에브리타임처럼 최신 게시글일수록 먼저 조회되게 수정 작업 완료했습니다.
1. 유저가 작성한 게시글 기록
게시글 생성 기준 최신글 먼저 조회
2. 유저가 즐겨찾기한 게시글 기록 (수정 후 테스트)
게시글 생성 기준 최신 글이 먼저 조회 되게 수정.
3. 유저가 단 댓글들의 게시글 목록 기록 ( 수정 후 테스트)
게시글 생성 기준 최신 글이 먼저 조회 되게 수정.
기타 참고사항을 …

refactor:  유저기록을 위한 API 추가

---

src/main/java/net/causw/application/board/BoardService.java
src/main/java/net/causw/application/calendar/CalendarService.java
src/main/java/net/causw/application/circle/CircleMemberService.java
src/main/java/net/causw/application/circle/CircleService.java
src/main/java/net/causw/application/comment/ChildCommentService.java
src/main/java/net/causw/application/comment/CommentService.java
src/main/java/net/causw/application/common/CommonService.java
src/main/java/net/causw/application/crawler/WebCrawlerService.java
src/main/java/net/causw/application/event/EventService.java
src/main/java/net/causw/application/excel/CircleExcelService.java
src/main/java/net/causw/application/excel/CouncilFeeExcelService.java
src/main/java/net/causw/application/form/FormService.java
src/main/java/net/causw/application/homepage/HomePageService.java
src/main/java/net/causw/application/inquiry/InquiryService.java
src/main/java/net/causw/application/locker/LockerService.java
src/main/java/net/causw/application/post/PostService.java
src/main/java/net/causw/application/semester/SemesterService.java
src/main/java/net/causw/application/storage/StorageManager.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/application/userAcademicRecord/UserAcademicRecordApplicationService.java
src/main/java/net/causw/application/userCouncilFee/UserCouncilFeeService.java
src/main/java/net/causw/application/uuidFile/CleanUnusedUuidFileService.java
src/main/java/net/causw/application/uuidFile/UuidFileService.java
src/main/java/net/causw/domain/aop/LogAspect.java
src/main/java/net/causw/domain/aop/annotation/MeasureTime.java

- #658
> 현재 nohup.out에 기록된 로그를 분석하는 과정에서 어떤 메서드가 얼마나 실행되었는지 온전하게 분간하기 어렵습니다. 
> 가시성 높은 모니터링을 위해 Service 내부 모든 메서드가 실행될 때마다 아래와 같은 형태의 로그가 자동 출력되도록 설정했습니다. 
> "실행된 메서드: updateUser, 실행시간 = 5ms"
위 이미지처럼 Service 내부 메서드 실행 시 자동으로 로깅됩니다.
개발기간: 1일

chore: AOP 기반 메서드별 이름/실행시간 로깅 #658

---

src/main/java/net/causw/application/dto/util/dtoMapper/CircleDtoMapper.java

CircleDtoMapper의 toCircleResponseDto 메소드를 사용했을 때 mainImage가 매핑되어 있지 않아 null로 받는 오류가 있어
직접 매핑을 해주었습니다.
개발기간:

hotfix: toCircleResponseDto를 사용했을 때 mainImage가 null이 되는 오류 수정

---

src/main/java/net/causw/application/user/UserService.java

https://github.com/CAUCSE/CAUSW_backend/issues/690
프로필 이미지 null값 넣을 시 에러가 발생해서 해당 오류 수정하였습니다.
기본적으로 user의 프로필 이미지를 받아오며 해당api(개인정보 수정)에서 프로필 사진을 보내지 않았을 경우 수정하지 않도록 로직 수정하였습니다.
이미 프로필 사진이 있는 사람이 파일을 안보냈을 경우 기존의 사진을 유지
프로필 이미지가 없는 사람이 파일을 안보냈을 경우 null값 유지(기본 이미지)
개발기간:

hotfix: 프로밀 및 증빙서류 이미지 null값 에러 수정

---

src/main/java/net/causw/application/circle/CircleService.java
src/main/java/net/causw/application/form/FormService.java

동아리 정보 수정 시 mainImage를 null로 보내면 500 에러가 발생하는 문제가 있었습니다.
이는 동아리 mainImage가 null이 아니어야 했기 때문이었으므로,
현재 동아리 mainImage가 null이고, 수정 시에도 mainImage를 null로 유지하는 경우 400번대 에러가 발생하도록 하였습니다.
또한 현재 동아리 mainImage가 null이 아니고, 수정 시 mainImage를 null로 설정하면,
동아리 mainImage가 바뀌지 않도록 설정하였습니다.
+ 추가로 신청서 관련 에러가 있어 수정한 후 이 pr에 함께 push하였습니다.
개발기간:

hotfix: 동아리 수정 시 mainImage가 null이고 현재 mainImage도 null인 경우 예외 발생

---

src/main/java/net/causw/application/dto/form/response/QuestionSummaryResponseDto.java
src/main/java/net/causw/application/dto/util/dtoMapper/FormDtoMapper.java
src/main/java/net/causw/application/form/FormService.java

신청서 결과 요약 조회 시 반환하는 Dto에 중복 응답 가능 여부와 총 응답수를 나타내는 필드를 추가하였습니다.
또한 결과 요약 조회를 하는 메소드에서 각 필드에 값을 할당하도록 하였습니다.
개발기간:

hotfix: 신청서 결과 요약 조회 시 중복 응답 가능 여부와 총 응답수를 반환하도록 변경

---

src/main/java/net/causw/adapter/persistence/repository/post/PostRepository.java

QA Test 도중 총댓글의 수가 잘못 나타나는 버그가 발견되어 총 댓글의 수가 올바르게 반환되도록 쿼리문을 수정하였습니다.
기존
4개인데 댓글 수 3개로 표시
수정 후
수정후 댓글수가 올바르게 4개 반환됨을 확인 할 수 있습니다.
개발기간:

fix: 댓글+대댓글의 수가 올바르도록 수정

---

src/main/java/net/causw/adapter/persistence/repository/userAcademicRecord/UserAcademicRecordApplicationRepository.java
src/main/java/net/causw/adapter/persistence/repository/uuidFile/UserAcademicRecordApplicationAttachImageRepository.java
src/main/java/net/causw/application/user/UserService.java

유저 삭제 시 해당 유저가 재학 인증 기록과 재학 인증 이미지가 있을 때 삭제되지 않는 오류를 해결하였습니다.
유저가 삭제될 때 해당 기록과 이미지도 함께 삭제되도록 하였습니다.
개발기간:

hotfix: 유저 삭제시 재학인증 기록, 이미지 미삭제 오류 해결

---

src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/domain/exceptions/NotFoundException.java

#748 <- 해당 이슈에 검증 과정 기록해 놓았습니다.
이번 PR에서는 다음과 같은 변경 사항이 적용되었습니다:
- 에러 클래스 추가:
NotFoundException 클래스를 새로 생성하여, BadRequestException 대신 사용하도록 수정했습니다.
더 정확한 예외 처리를 위해, 리소스가 존재하지 않을 때 NotFoundException을 사용합니다.
- 비밀번호 찾기 API 개선:
UserService에서 비밀번호 변경 전에 메일 전송을 먼저 수행하도록 로직 순서를 수정했습니다.
dirty checking을 활용하여 userRepository.save() 호출을 제거했습니다.
findByEmailAndNameAndStudentIdAndPhoneNumber 메서드 호출 시, DTO 필드 값에 trim()을 적용해 불필요한 공백이 제거되도록 했습니다.
- Controller 리턴 타입 변경:
findPassword 메서드의 리턴 타입을 UserResponseDto에서 void로 수정했습니다. 이 메서드는 비밀번호 재설정 메일 전송을 담당하기 때문에, 별도의 응답 DTO가 필요하지 않습니다.

 [FIX] 비밀번호 재발급 정상 작동 검증 및 로직 개선 

---

src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/UserAcademicRecordLogAttachImage.java
src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/UserAdmissionLogAttachImage.java

academic record log가 동일한 파일 entity row를 fk로 참조하지 못했던 문제를 @OneToOne에서 @ManyToOne으로 바꿔 해결했습니다. (unique 제약 조건 제거)
개발기간: 1일

fix: uuidfile 객체 OneToOne -> ManyToOne으로 버그 픽스

---

src/main/java/net/causw/adapter/persistence/repository/user/UserAdmissionRepository.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/domain/model/util/MessageUtil.java

- PUT: updateAdmission API 삭제(미사용, createAdmission으로 전체 대체)
- createAdmission에 UserState AWAIT / REJECT일 때만 가능하도록 validation 추가
개발기간: 1시간

fix: User Admission API 수정

---

src/main/java/net/causw/adapter/persistence/repository/userAcademicRecord/UserAcademicRecordApplicationRepository.java
src/main/java/net/causw/adapter/web/UserAcademicRecordApplicationController.java
src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/application/userAcademicRecord/UserAcademicRecordApplicationService.java

- user admission
- user admission 거절 시 user state AWAIT로 변경
- user academic record
- user academic record create 시 대상 사용자의 변경 타겟 학적 상태가 재학인 경우, 대기 중인 이미 신청한 학적 정보 신청서가 있는지 확인하고, 있다면 닫음 처리
- semester service 사용, 중복 메서드 제거
개발기간: 1시간

fix: user admission 거절 시 user state 관리 및 user academic status 로직 수정

---

src/main/java/net/causw/application/semester/SemesterService.java
src/main/java/net/causw/application/userCouncilFee/UserCouncilFeeService.java
src/main/java/net/causw/domain/model/util/MessageUtil.java

기존 학적 상태 등록(재학 등록)을 하지 않은 사용자에 대해 학생회비 등록을 시도할 시 바로 500번대 에러가 뜨는 상황에서 정확히 validation을 하도록 수정했습니다.
개발기간:

fix: 학생회비 등록 예외 핸들링 추가

---

src/main/java/net/causw/application/user/UserService.java
src/main/java/net/causw/domain/model/util/MessageUtil.java

- #774
* 기존 회원가입 API는 입학년도(즉, 학번의 앞 4자리)와 학번이 동일하지 않는 잘못된 요청을 그대로 처리하고 있었습니다. 이를 방지하고자 학번 앞 4자리와 입학년도를 매핑하여 예외처리를 추가하였습니다.

fix: 회원가입 API 유효하지 않은 요청 예외처리 추가

---

src/main/java/net/causw/adapter/web/BoardController.java
src/main/java/net/causw/adapter/web/CalendarController.java
src/main/java/net/causw/adapter/web/CircleController.java
src/main/java/net/causw/adapter/web/CommonController.java
src/main/java/net/causw/adapter/web/EventController.java
src/main/java/net/causw/adapter/web/FormController.java
src/main/java/net/causw/adapter/web/LockerController.java
src/main/java/net/causw/adapter/web/SemesterController.java
src/main/java/net/causw/adapter/web/StorageController.java
src/main/java/net/causw/adapter/web/UserAcademicRecordApplicationController.java
src/main/java/net/causw/adapter/web/UserController.java
src/main/java/net/causw/adapter/web/UserCouncilFeeController.java
src/main/java/net/causw/config/security/SecurityService.java

해당 API에서 발생하는 에러를 조사하던 중, `hasAnyRole('ADMIN', PERSIDENT', ...)` 해당 코드에서 **PERSIDENT**로 작성이 된 오타 때문에 에러가 발생하는 것을 발견했습니다.
단순히 오타만 수정하면 에러는 해결되겠지만, 추후 유지 보수나 기능 확장 시 기존 방식과 같이 단순히 SpEL에 텍스트를 넣는 건 휴먼 에러 발생 가능성이 높다고 판단되어 SpEL 내부에서 Role enum 클래스의 name을 참조하는 방식을 사용하려 했으나,
```java
// SpEL은 별도의 context를 사용하기 때문에 import 문이 소용 없어서 class 경로를 직접 지정해줘야 함
hasAnyRole(T(net.causw.domain.model.enums.user.Role).ADMIN.toString(), T(net.causw.domain.model.enums.user.Role).PRESIDENT.toString(), T(net.causw.domain.model.enums.user.Role).VICEPRESIDENT.toString())
```
이런 방식으로 사용해야하는 문제가 있었습니다.
따라서 비록 hasAnyRole처럼 간단하게 다양한 Role 조합 검사를 수행할 수 있는 편리성을 떨어지지만, `SecurityService.java`에 공통 메서드를 등록해 사용하는 방식이 낫겠다 판단되어 해당 방식으로 에러 수정 및 리펙토링을 진행했습니다.
개발기간: 3시간

fix: Role 검사 로직 통합(SecurityService)

---

.gitignore
build.gradle
src/main/java/net/causw/adapter/persistence/locker/LockerLocation.java
src/main/java/net/causw/adapter/persistence/locker/LockerName.java
src/main/java/net/causw/adapter/persistence/push/Ceremony.java
src/main/java/net/causw/adapter/persistence/repository/push/CeremonyRepository.java
src/main/java/net/causw/adapter/persistence/user/User.java
src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/CeremonyAttachImage.java
src/main/java/net/causw/adapter/web/CeremonyController.java
src/main/java/net/causw/adapter/web/PushController.java
src/main/java/net/causw/application/ceremony/CeremonyService.java
src/main/java/net/causw/application/dto/ceremony/CeremonyResponseDTO.java
src/main/java/net/causw/application/dto/ceremony/CreateCeremonyRequestDTO.java
src/main/java/net/causw/application/locker/LockerService.java
src/main/java/net/causw/application/notification/FirebasePushNotificationService.java
src/main/java/net/causw/config/firebase/FirebaseConfig.java
src/main/java/net/causw/config/security/WebSecurityConfig.java
src/main/java/net/causw/domain/model/enums/ceremony/CeremonyCategory.java
src/main/java/net/causw/domain/model/enums/ceremony/CeremonyState.java
src/main/java/net/causw/domain/model/util/MessageUtil.java

경조사 기능 구현 및 사물함 dto 변경입니다.
사물함 Dto의 경우에는 LockeName이라는 필드를 추가하여 second, third, fourth로 층 정보를 얻을 수 있게 변경하였습니다.
경조사 api를 구현하였습니다.
푸시알람에 대한 일반적인 config를 추가하였고, 경조사 api를 일단 프론트와 맞춰보고, 푸시알람을 붙히는 방향으로 일단 개발하였습니다.
경조사 api를 연동하여 안정화 한 뒤 푸시알람 설정 및 배치 기능을 붙히겠습니다.

경조사 기능 구현 

---

src/main/resources/logback-spring.xml

기존 logback.xml에서는 `QA` 서버 오류만 디스코드로 출력하고 있었는데, 
`dev` 서버 익셉션을 출력하도록 바꿨습니다.
기존에는 익셉션 스택 트레이스를 전부 출력했는데,
보기 쉽도록 상위 10줄만 출력하게 바꿔봤습니다

fix: logback 익셉션 디스코드 웹훅 설정 업데이트

---

src/main/java/net/causw/adapter/persistence/repository/flag/FlagRepository.java
src/main/java/net/causw/application/dto/locker/LockersResponseDto.java
src/main/java/net/causw/application/locker/LockerActionRegister.java
src/main/java/net/causw/application/locker/LockerService.java

기존 사물함을 가지고 있을 경우 다른 사물함을 선택할 때 자동으로 변경되는 로직에 문제가 발생하여 강제로 flush를 통해 db가 업데이트 되게 하였습니다.
dto에는 lockerPeriod를 사용하여 현재 사물함의 신청 상태를 반환합니다.(LOCKER_ACCESS, LOCKER_EXTEND, NULL을 반환합니다
개발기간:

feat : 사물함 로직 수정 및 사물함 신청 상태 dto 추가 

---

src/main/java/net/causw/adapter/persistence/repository/event/EventRepository.java
src/main/java/net/causw/application/event/EventService.java
src/test/java/net/causw/application/event/EventServiceTest.java

https://www.notion.so/1b93d138d33c813782a5f5045e07401e?pvs=4
노션을 통해 배정받은 `배너 반환 시 등록시간 역순으로 정렬` 이슈에 대한 풀리퀘스트 입니다.
해당 업무 수행하면서 관련된 `EventService` 의 단위 테스트 코드 또한 작성했습니다.
확인해주시면 감사하겠습니다.
개발기간: 약 3일

fix: 이벤트 순서 정렬 기준 명시

---

src/main/java/net/causw/application/excel/CouncilFeeExcelService.java
src/main/java/net/causw/application/excel/UserExcelService.java
src/main/java/net/causw/application/userCouncilFee/UserCouncilFeeService.java
src/test/java/net/causw/application/excel/ExcelAbstractServiceTest.java
src/test/java/net/causw/application/user/UserServiceTest.java
src/test/java/net/causw/application/userCouncilFee/UserCouncilFeeServiceTest.java
src/test/java/net/causw/domain/model/util/ObjectFixtures.java

주요 변경 사항은 다음과 같습니다.
1. 학생회비 납부자 엑셀 내용 수정
- 학적 상태 영어에서 한글로 변경
- 졸업 유형 영어에서 한글로 변경
- 학생회비 환불되지 않은 경우 환불 시점 0에서 ""으로 수정
2. 엑셀 서비스 구현 클래스의 테스트를 파라미터화 테스트로 변경
- 엑셀 서비스 구현 클래스들(UserExcelService, CouncilFeeExcelService)의 테스트 케이스가 동일함
- 유지보수 용이성을 위해 기존의 UserExcelServiceTest를 삭제하고 ExcelAbstractServiceTest에서 모든 엑셀 서비스 구현 클래스들을 파라미터화 테스트로 한 번에 테스트 할 수 있도록 변경
3. 테스트에 ObjectFixtures 적용 및 일부 변수 불변으로 변경
- ObjectFixtures 클래스를 추가하여 객체의 필드 값이 테스트 내에서 중요한 경우 실제 객체를 사용하여 테스트 (객체의 필드 값이 테스트 내에서 중요하지 않은 경우 모킹)
- 테스트 내에서 변경되지 않는 전역 변수들 static final로 변경 (BeforeEach에서 제거)
유닛 테스트
- ExcelAbstractServiceTest
- UserCouncilFeeServiceTest
API 테스트
API 테스트 결과 파일
개발기간:

fix: 학생회비 납부자 목록 엑셀 내용 수정

---

src/main/java/net/causw/adapter/persistence/vote/VoteOption.java
src/main/java/net/causw/application/vote/VoteService.java
src/main/java/net/causw/domain/model/util/MessageUtil.java
src/test/java/net/causw/application/vote/VoteServiceTest.java
src/test/java/net/causw/domain/model/util/ObjectFixtures.java

#820 
- 820번 풀리퀘스트와 관련하여, 미비사항으로 작성했던 투표 도메인 서비스 단위 테스트를 추가했습니다.
- 테스트 중 투표 재시작 로직과 관련하여 예외처리 메시지가 로직과 부합하지 않는 부분을 확인하여 수정하였습니다. c38fec5e4c3e4c31759114bd42ec5e8a38171a6a
- `ObjectFixture` 부분을 좀더 리팩토링해보면 어떨까 합니다. 확실히 재사용성 측면에서 좋은 방법인 것 같은데, 
엣지 케이스 테스트 측면에서 필드 수정을 하거나 하기가 쉽지 않다는 부분이 있었습니다.
저의 경우에는 그럴때 모킹(mocking)을 사용하긴 했습니다. 하지만 이런 부분들도 `ObjectFixture` 클래스를 리팩토링하여 해결할 수 있지 않을까 합니다.
개발기간: 1d

test: 투표 도메인 테스트 작성

---

src/main/java/net/causw/adapter/persistence/notification/Notification.java
src/main/java/net/causw/application/dto/ceremony/CeremonyResponseDto.java
src/main/java/net/causw/application/dto/notification/NotificationResponseDto.java
src/main/java/net/causw/application/dto/util/dtoMapper/CeremonyDtoMapper.java
src/main/java/net/causw/application/dto/util/dtoMapper/NotificationDtoMapper.java
src/main/java/net/causw/application/notification/BoardNotificationService.java
src/main/java/net/causw/application/notification/CeremonyNotificationService.java
src/main/java/net/causw/application/notification/CommentNotificationService.java
src/main/java/net/causw/application/notification/PostNotificationService.java
src/test/java/net/causw/application/notification/CommentNotificationServiceTest.java
src/test/java/net/causw/application/notification/NotificationLogServiceTest.java
src/test/java/net/causw/application/notification/PostNotificationServiceTest.java

경조사, 알람 개발중 프론트 측의 요청사항 해결을 위한 작업입니다.
###경조사 수정사항
경조사 정보 중 신청자의 학번, 이름이 누락되어 applicantStudentId, applicantName으로 dto에 반환값을 추가하였습니다.
###일반알람 수정사항
알람 기능중 일반 알람에서 페이지 라우팅을 위해 기존 targetId에 추가로 게시판 ID를 요청받았습니다. 
현재 구조상 경조사 알람과 함께 NotificationResponseDto로 공통으로 관리하고, 게시판 id 추가로 위해서 별도의 dto로 분리하는 것보단 targetParentId라는 파라미터를 추가해 공통적으로 관리하면서 추후 확장성을 증대시키는 방향으로 수정을 진행하였습니다.
참고할점은 위와같은 방식으로 수정을 진행하면서 경조사 알람에도 targetParentId가 null값으로 반환되는 상황입니다. 
개발기간:

hotfix : notificationLog에 targetParentId 파라미터 추가, 경조사 정보에 신청자 학번/이름 추가

---

.github/workflows/dev-cd.yml
.github/workflows/main-cd.yml

#842 
main dev 브랜치에서 깃허브 액션 cd 스크립트를 통한 배포 완료 시 배포 상태를 전달하는 단계를 추가했습니다.
아래 secret들을 추가했습니다.
- `DISCORD_BACKEND_ROLE_ID` : 디스코드 내 `Backend` 역할 id
- `DISCORD_DEPLOY_WEBHOOK_URL_DEV` : `backend-dev-deploy` 채팅 채널 웹훅 url
- `DISCORD_DEPLOY_WEBHOOK_URL_MAIN` : `backend-main-deploy` 채팅 채널 웹훅 url
추후, 역할 변경이나, 웹훅 url에 변경이 일어날 경우 해당 secrets를 수정해주시기 바랍니다.
- 성공 시 예시
- 실패 시 예시
개발기간: 3h

chore: 배포 상태 알림 디스코드 봇 관련 cd 스크립트 수정

---

build.gradle
src/main/java/net/causw/domain/aop/LogAspect.java
src/main/java/net/causw/global/filter/RequestLoggingFilter.java
src/main/java/net/causw/global/filter/StatusCaptureWrapper.java
src/main/resources/logback-spring.xml

#845
**이번 풀리퀘스트는 그라파나 로키에서 데이터를 분석하기 위해서 로그의 형식을 수정하고, 사용자의 모든 api 요청에 대해서 분석하기 위한 발판을 마련하는 풀리퀘스트입니다.**
관련해서 이슈와 레퍼런스들을 잘 읽어주시면 감사하겠습니다.
- 그라파나 > 로키에서 로그 데이터를 분석하기 위해서, 파일로 저장되는 로그의 포맷을 json 형식으로 수정했습니다.
- 사용자 요청에 대한 데이터를 축적하고 오류에 대해 빠르게 접근하기 위해 HTTP 요청 당 메타데이터를 저장하는 로그 필터를 추가하였습니다.
- 개발환경에서의 로그 또한 파일로 저장하기 위해 `DEV_FILE` 이라는 appender를 추가하였습니다.
json 형식으로 로그가 잘 노출되는지 확인하고 싶으시다면, `logback-spring.xml` 파일에서
```
<springProfile name="local">
<root level="INFO">
<appender-ref ref="CONSOLE"/>
</root>
</springProfile>
```
부분을
```
<springProfile name="local">
<root level="INFO">
<appender-ref ref="CONSOLE_JSON"/>
</root>
</springProfile>
```
부분으로 변경하시고 테스트 해보시면 됩니다.
개발기간:  5h

chore: 로그 분석을 위한 로그 파일 형식 수정 및 HTTP 요청당 로그 필터 추가

---

app-main/src/main/resources/db/migration/V20250803171739__add_graduation_to_ceremony_category_enum.sql

#894 
경조사 테이블 (tb_ceremony)의 ceremony_category 필드는 현재 enum값으로 처리되어있음 (MARRIGE, FUNERAL, GRADUATION, ETC)
그러나 현재 dev DB에서는 이 중 GRADUATION이 누락되어있음.
따라서 이를 해결하기 위해 flyway 마이그레이션 스크립트를 추가
(sql문으로 즉각 수정이 가능하나. flyway 사용 목적에 맞게 스크립트 추가)
x
개발기간: 0.5h

hotfix: 카테고리 enum 누락 해결

---

app-main/src/main/java/net/causw/app/main/controller/CeremonyController.java
app-main/src/main/java/net/causw/app/main/dto/notification/CeremonyListNotificationDto.java
app-main/src/main/java/net/causw/app/main/dto/util/dtoMapper/NotificationDtoMapper.java
app-main/src/main/java/net/causw/app/main/repository/ceremony/CeremonyRepository.java
app-main/src/main/java/net/causw/app/main/service/ceremony/CeremonyService.java

#903 
https://www.notion.so/2463d138d33c80f89d03fa73e3d24b67?source=copy_link
관리자의 경조사 관리 페이지에서 대기중인 경조사 목록이 최신순으로 정렬되지 않아 이를 해결합니다.
또한 해당 페이지의 디자인이 변경되면서 이에 따라 DTO를 수정합니다.
내 경조사 목록도 동일하게 수정합니다.
**전체 경조사 승인 대기 목록 조회 (관리자용) `/api/v1/ceremony/list/await`**
**사용자 본인의 경조사 신청 내역 조회 `/api/v1/ceremony`**
x
개발기간: 1h

fix: 경조사 관리 목록 정렬 & 내 경조사 목록 정렬 및 DTO 수정

---

app-main/src/main/java/net/causw/app/main/dto/ceremony/CreateCeremonyNotificationSettingDto.java
app-main/src/main/java/net/causw/app/main/repository/notification/CeremonyNotificationSettingRepository.java
app-main/src/main/java/net/causw/app/main/service/userAcademicRecord/UserAcademicRecordApplicationService.java
app-main/src/main/resources/db/migration/V20250809015435__CreateDefaultCeremonyNotificationSettings.sql

#900 
https://www.notion.so/2463d138d33c80d89716de573cf1ff1f?source=copy_link
현재 경조사 알림이 전달되기 위해서는 사용자가 경조사 알림 생성(`POST /api/v1/ceremony/notification-setting`)을 직접 실행해야 `CeremonyNotificationSetting`이 생성되어 알림이 전달 가능해집니다.
따라서 회원가입 시(정확히는 학적 승인 시)에 자동적으로 초기 설정 (전체 학번에게 받음)으로 알림 설정이 생성되게 구현하였습니다.
tb_user에서 해당 회원의 id 확인
tb_ceremony_push_notification에서 알림 설정 생성 확인 (is_set_all이 true)
이후 경조사 알림 승인 시
이렇게 알림이 정상적으로 수신된 것을 확인할 수 있음
x
개발기간: 2h

bug: 경조사 알림 최초 설정 오류 해결

---

app-main/src/main/java/net/causw/app/main/domain/model/entity/user/User.java
app-main/src/main/java/net/causw/app/main/domain/model/entity/userAcademicRecord/UserAcademicRecordLog.java
app-main/src/main/java/net/causw/app/main/domain/model/entity/userCouncilFee/CouncilFeeFakeUser.java
app-main/src/main/java/net/causw/app/main/domain/model/entity/userCouncilFee/UserCouncilFeeLog.java
app-main/src/main/java/net/causw/app/main/service/circle/CircleService.java
app-main/src/main/resources/db/migration/V20250811211017__ModifyAllStudentIdNullable.sql

#910 
- 회원가입 후 학적인증 에러가 발생
- 그 외 학번관련해서 null로 받는데, 다른 엔티티에서도 null을 허용으로 하도록 함
update로직에서 이메일까지 update하는 로직을 빼먹었었는데, 추가했습니다!
개발기간: 1d

hotfix : 학적인증 과정에서 학번 null 에러 발생

---

app-main/src/main/java/net/causw/app/main/controller/ChildCommentController.java
app-main/src/main/java/net/causw/app/main/controller/CommentController.java
app-main/src/main/java/net/causw/app/main/repository/comment/LikeChildCommentRepository.java
app-main/src/main/java/net/causw/app/main/repository/comment/LikeCommentRepository.java
app-main/src/main/java/net/causw/app/main/service/comment/ChildCommentService.java
app-main/src/main/java/net/causw/app/main/service/comment/CommentService.java
global/src/main/java/net/causw/global/constant/MessageUtil.java

https://www.notion.so/2463d138d33c80d6bf30eb7bf01e7fd1?source=copy_link
게시글의 좋아요 취소를 @bingle625 이 개발한 히스토리가 있어 댓글, 대댓글에도 적용하여 취소 API를 개발하였습니다.
댓글 좋아요 삭제
대댓글 좋아요 삭제
개발기간:

feat : 댓글/대댓글 좋아요 취소 기능 추가

---

app-main/src/main/java/net/causw/app/main/dto/report/ReportedCommentNativeProjection.java
app-main/src/main/java/net/causw/app/main/dto/report/ReportedCommentResponseDto.java
app-main/src/main/java/net/causw/app/main/dto/report/ReportedPostNativeProjection.java
app-main/src/main/java/net/causw/app/main/dto/report/ReportedPostResponseDto.java
app-main/src/main/java/net/causw/app/main/dto/report/ReportedUserResponseDto.java
app-main/src/main/java/net/causw/app/main/dto/util/dtoMapper/ReportDtoMapper.java
app-main/src/main/java/net/causw/app/main/repository/report/ReportRepository.java

#927 
- 신고된 유저 응답 DTO에 유저 상태 필드를 추가하여, 신고된 유저의 상태 정보를 반환하도록 개선합니다.
- 신고된 사용자 목록을 조회할 때, 사용자 상태를 기준으로 우선 정렬한 후 신고 횟수를 기준으로 정렬하도록 변경합니다. 이를 통해 관리자는 활성 상태의 신고된 사용자를 먼저 확인할 수 있습니다.
- 신고된 게시글 및 댓글 조회 시 작성자의 유저 상태 정보를 함께 반환하도록 기능을 추가합니다. 이를 통해 신고된 게시글/댓글을 처리할 때 작성자의 상태를 고려하여 더욱 효과적인 관리가 가능해집니다.
| 기능 | 이미지 | 설명 |
|------|--------|------|
| 신고 유저 리스트 |<img width="1415" height="590" alt="image" src="https://github.com/user-attachments/assets/3837d826-3809-4ebb-9afb-9631bd879cfe" />| userState로 반환 |
| 신고 콘텐츠 목록 (게시물) | <img width="1397" height="499" alt="image" src="https://github.com/user-attachments/assets/cd966db4-9930-4625-9f9d-03de3aceb904" /> | userState로 반환 |
| 신고 콘텐츠 목록 (댓글,대댓글) | <img width="1403" height="511" alt="image" src="https://github.com/user-attachments/assets/302c8ff8-113c-43ac-bc …

feat: 신고 콘텐츠 목록 & 신고 유저 리스트 페이지 응답 데이터 수정

---

app-main/src/main/java/net/causw/app/main/dto/util/dtoMapper/UserDtoMapper.java
global/src/main/java/net/causw/global/constant/StaticValue.java

#930 
https://www.notion.so/2513d138d33c807abedce69139d30b13?source=copy_link
1. 현재 운영계에 전화번호가 없는 사용자가 존재하지만 개발과정에서 phoneNumber는 nullable = false인 상태가 되었습니다.
2. DB마이그레이션에 대한 대책으로 전화번호가 없는 사용자에 대해서 임의로 'temp-' prefix를 붙여 전화번호를 저장합니다.
3. 'temp-' prefix를 기준으로 '전화번호 없음'을 반환합니다.
- 해당 코드는 임시 코드로 'temp-' prefix가 DB에서 사라진다면 삭제해야 합니다.
- 동문수첩 이외에 전화번호를 사용하는 곳은 학생회비 관리 부분이 있지만 당장의 우선순위가 아니라고 판단해 동문수첩에만 임시 적용하였습니다.
개발기간:

hotfix : 운영계 DB phoneNumber Null 이슈 해결

---

app-main/src/main/java/net/causw/app/main/dto/user/UserUpdateRequestDto.java
app-main/src/main/java/net/causw/app/main/service/user/UserService.java
app-main/src/main/java/net/causw/app/main/service/userInfo/UserInfoService.java

#941 
@pattern으로 형식 검사하고 있었는데, 이걸 지웠음
그리고 userInfo/me에서는 전화번호 수정을 할 때 형식검사를 진행해야하므로 Validator로 형식검사함
다른 곳에서 UserUpdateRequestDto를 쓰고 있기 때문에 dto에서 전화번호를 제외하지 않았음.
개발기간: 1d

[BUG] 회원 정보 수정 시 전화번호 수정란이 없지만 전화번호 형식 에러 뜸

---

app-main/src/main/java/net/causw/app/main/controller/UserController.java
app-main/src/main/java/net/causw/app/main/dto/user/UserRecoverRequestDto.java
app-main/src/main/java/net/causw/app/main/infrastructure/security/SecurityEndpoints.java
app-main/src/main/java/net/causw/app/main/service/user/UserService.java
app-main/src/test/java/net/causw/app/main/service/user/UserServiceTest.java
global/src/main/java/net/causw/global/constant/MessageUtil.java

#942 
1. 현재까지 ACTIVE와 DROP에 대해 중복 체크를 하고 있었음
2. INACTIVE인 경우에는 중복체크를 하지 않고, 탈퇴한 사용자와 같은 이메일이나, 같은 전화번호를 쓴 경우에 update처리를 해서 복구로 간주했음.
3. 이때 누군가가 이메일이나, 전화번호를 잘못쳐서 탈퇴한 사용자의 정보를 뺏는다면 문제가 생길 수 있다고 생각함
4. 따라서, 탈퇴한 사용자는 로그인 시에 계정을 복구하시겠습니까? 알림/버튼이 나와서 동의하면 state를 ACTIVE로 변경해 복구하는 방식으로 하자고 이야기가 나옴.
1. INACTIVE인 사용자의 이메일, 닉네임, 학번, 전화번호를 회원가입 시 중복체크에 포함시킴
2. INACTIVE인 경우 로그인했을때 에러를 반환하고, 프론트에서 INACTIVE에러를 받게되면, 모달을 띄움
3. 이후 사용자가 복구하시겠습니까? 라는 질문에 예를 답하면 status는 ACTIVE, Role은 COMMON으로 변경해 복구할 수 있도록 하고 토큰을 발급함
해주세요.
개발기간: 1d

[FEATURE] 탈퇴 회원에 대한 회원가입, 복구 처리

---

app-main/src/main/java/net/causw/app/main/service/user/UserService.java
app-main/src/main/java/net/causw/app/main/service/userInfo/UserInfoService.java
app-main/src/test/java/net/causw/app/main/service/userInfo/UserInfoServiceTest.java
global/src/main/java/net/causw/global/constant/MessageUtil.java

[탈퇴 회원에 대한 회원가입, 복구 처리](https://www.notion.so/2533d138d33c804bbddfd6126159617c)
동문수첩 수정시 닉네임, 전화번호는 user의 필드이므로 userService의 update로 변경합니다.
따라서 닉네임, 전화번호의 중복 체크도 userService로 통합합니다.
개발기간:

fix: 동문수첩의 전화번호 중복 체크 대상에 탈퇴 유저 추가

---

app-main/src/main/java/net/causw/app/main/controller/UserAcademicRecordApplicationController.java
app-main/src/main/java/net/causw/app/main/dto/user/UserAcademicStatusNoteUpdateDto.java
app-main/src/main/java/net/causw/app/main/dto/userAcademicRecordApplication/UserAcademicRecordInfoResponseDto.java
app-main/src/main/java/net/causw/app/main/service/userAcademicRecord/UserAcademicRecordApplicationService.java

[비고 따옴표 포함되어 오는 이슈](https://www.notion.so/2523d138d33c801d97badfeb630191c9)
@RequestBody String으로 직접 비고 내용을 받아와서 따옴표가 파싱되지 않고 그대로 저장되고 있었습니다.
DTO로 비고 내용을 받아와 저장하도록 변경하고, 응답 DTO 반환 전 따옴표를 제거합니다.
- 비고 갱신시 따옴표 없이 DB에 저장
- 따옴표 포함하는 비고의 따옴표 제거후 반환
개발기간: 1h

fix: 학적 상태 비고에 따옴표를 포함하하지 않고 저장, 반환하도록 수정

---

app-main/build.gradle
app-main/src/main/java/net/causw/app/main/controller/UserController.java
app-main/src/main/java/net/causw/app/main/domain/model/entity/notification/CeremonyNotificationSetting.java
app-main/src/main/java/net/causw/app/main/domain/model/entity/user/User.java
app-main/src/main/java/net/causw/app/main/domain/model/enums/user/Role.java
app-main/src/main/java/net/causw/app/main/domain/model/enums/user/RoleGroup.java
app-main/src/main/java/net/causw/app/main/domain/policy/RolePolicy.java
app-main/src/main/java/net/causw/app/main/dto/user/BatchRegisterResponseDto.java
app-main/src/main/java/net/causw/app/main/dto/user/CreateGraduatedUserCommand.java
app-main/src/main/java/net/causw/app/main/dto/user/UserPrivilegedResponseDto.java
app-main/src/main/java/net/causw/app/main/dto/util/dtoMapper/UserDtoMapper.java
app-main/src/main/java/net/causw/app/main/infrastructure/querydsl/QuerydslConfig.java
app-main/src/main/java/net/causw/app/main/infrastructure/security/userdetails/CustomUserDetailsService.java
app-main/src/main/java/net/causw/app/main/repository/circle/query/CircleQueryRepository.java
app-main/src/main/java/net/causw/app/main/repository/user/query/UserQueryRepository.java
app-main/src/main/java/net/causw/app/main/service/circle/CircleEntityService.java
app-main/src/main/java/net/causw/app/main/service/user/UserEntityService.java
app-main/src/main/java/net/causw/app/main/service/user/UserService.java
app-main/src/main/java/net/causw/app/main/service/user/useCase/FindPrivilegedUsersUseCaseService.java
app-main/src/main/java/net/causw/app/main/service/user/useCase/RegisterGraduatedUsersUseCaseService.java
app-main/src/main/resources/db/migration/V20250921152909__ModifyUserRoleField.sql

#981 
간만입니다.
- 이번 풀리퀘스트에서는 크자회 운영자 `ALUMNI_MANAGER` role을 추가했습니다.
`ALUMNI_MANAGER` 의 경우 기존 크자회 운영자와 완전히 같은 권한을 가지도록 했습니다.
Role 관련해서 심도깊게 확인해주시면 감사하겠습니다.
제가 놓친 부분이 있을 수도 있어서요..
- queryDSL 을 도입했습니다.
동적 쿼리를 꼭 써야하는 코드들은 아니었습니다만,, 추후 있을 리팩토링에서 n+1 문제를 효과적으로 해결하기 위해서 queryDSL 을 도입하는 것이 불가피하다는 판단이었습니다.
queryDSL 레포지토리를 만드실 때에는 일단은 `repository/query/{Domain이름}QueryRepository` 로 작명하는 것을 임시 원칙으로 하겠습니다. 유념해주세요!
- `/api/v1/users/privileged` 에서 발생하던 n+1 문제를 해결했습니다.
쿼리로그를 처음으로 켜본거 같은데 이 GET 요청 한번 날리는데 1만줄의 쿼리가 발생하더군요,,(format_sql=true여서 그렇긴하지만)
n+1 문제를 해결하면서 겸사겸사 User에 붙어있던 eager 로딩을 제거했습니다.
++) eager 로딩 사용할 때에는 정말 필요할까,,? 라는 생각을 한번 해보는 것도 좋을거 같아요..
개발기간:

feat: ALUMNI_MANAGER 역할 추가 및 queryDSL 도입

---

app-main/src/main/java/net/causw/app/main/controller/UserInfoController.java
app-main/src/main/java/net/causw/app/main/domain/model/entity/user/User.java
app-main/src/main/java/net/causw/app/main/domain/model/entity/uuidFile/joinEntity/UserProfileImage.java
app-main/src/main/java/net/causw/app/main/dto/userInfo/UserInfoSearchCondition.java
app-main/src/main/java/net/causw/app/main/dto/userInfo/UserInfoSearchConditionDto.java
app-main/src/main/java/net/causw/app/main/repository/userInfo/UserInfoRepository.java
app-main/src/main/java/net/causw/app/main/repository/userInfo/query/UserInfoQueryRepository.java
app-main/src/main/java/net/causw/app/main/repository/userInfo/query/UserInfoQueryRepositoryImpl.java
app-main/src/main/java/net/causw/app/main/service/userInfo/UserInfoService.java
app-main/src/main/java/net/causw/app/main/service/userInfo/useCase/query/SearchUserInfoListUseCaseService.java

Close #992 
전체 사용자 리스트 조회 API에 검색 조건을 추가하여 사용자를 검색하는 기능을 구현했습니다.
- 이름, 직업, 경력에 대한 키워드 검색 기능 추가
- 입학 년도 범위 검색 기능 추가
- 학적 상태 필터링 기능 추가
- 기존 검색 API 제거
- User 엔티티의 Locker, CeremonyNotificationSetting, UserProfileImage 필드에 대해 Lazy Loading을 적용했습니다.
- 기존의 `/api/v1/users-info/search` 엔드포인트를 삭제하고, 해당 기능을 `/api/v1/users-info` 엔드포인트로 합쳤습니다.
- queryDSL을 사용하여 검색 API를 개발했습니다. 참고해주시면 감사하겠습니다.
- user 리스트를 조회할 경우 쿼리를 통해 확인해보니 `user.locker` 와 `user.ceremonyNotificationSetting` 에 대해서도 계속 쿼리를 요청하고 있어서 n+1 문제가 발생하고 있습니다.
문제는 얘네를 동문수첩 검색 로직상 사용하지 않고 있는데, 쿼리를 하고 있다는 겁니다. 처음에는 이게 eager 로딩 설정이 되어있어서 그런줄 알았는데, lazy 로딩으로 변경한 후에도 계속 해당 속성들에 대한 n+1 문제가 발생합니다.
userInfo.user를 매퍼에서 사용할 때에 모종의 이유로 locker와 ceremonyNotificationSetting 에 대해서도 요청을 하는것 같은데, 일단은 동문수첩 검색시 해당 속성들도 fetchJoin 을 진행하게 하여 n+1 문제는 막았습니다.
정확히 왜 이런 문제가 …

feat: 동문수첩 리스트 검색 api 구현

---

app-main/src/main/java/net/causw/app/main/domain/model/entity/user/User.java
app-main/src/main/java/net/causw/app/main/domain/resolver/DepartmentResolver.java
app-main/src/main/java/net/causw/app/main/dto/user/CreateGraduatedUserCommand.java
app-main/src/main/java/net/causw/app/main/dto/user/GraduatedUserCommand.java
app-main/src/main/java/net/causw/app/main/dto/user/GraduatedUserRegisterRequestDto.java
app-main/src/main/java/net/causw/app/main/service/user/UserService.java
app-main/src/main/java/net/causw/app/main/service/user/useCase/RegisterGraduatedUsersUseCaseService.java
global/src/main/java/net/causw/global/constant/MessageUtil.java

close #988 
회원 등록 구글폼 응답에 포함된 입학년도 값으로 운영계 회원 일괄 등록 전에 학과/학부명 상수화 반영했습니다.
이미 가입 신청된 경우, 가입 신청 승인된 경우, 학적 인증된 경우에 따른 예외처리도 추가헸습니다.
로컬에서 운영계 DB 데이터로 테스트했을 때 일괄 등록이 정상적으로 이루어졌고,
등록된 계정으로 여러 기능 테스트한 결과 정상 동작했습니다.
- 게시글, 동문수첩 조회
- 댓글, 글, 경조사, 게시글 좋아요, 게시글 찜 생성 
- 동문수첩, 회원정보, 비밀번호 수정
- 경조사 알림 및 게시글 알림 수신
개발기간:

refactor: 졸업생 일괄 등록 기능에 학과/학부명 상수화 반영 및 예외처리
